### ISSUE TITLE
Revisitação: Desenvolvimento de mecanismos para inferência e ajuste de periodicidade ao longo do tempo

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C01#14]
A frequência de atualização das informações de muitos sites é desconhecida. Portanto, é necessário criar mecanismos que controlem e armazenem quando uma determinada fonte sofreu alterações, de modo a descobrir a periodicidade em que os dados são atualizados, impactando diretamente na frequência de revisitação da mesma.

**Comment by elvesrodrigues** [comment]
Artigos relacionados:
- [Junghoo Cho and Hector Garcia-Molina. 2003. Effective page refresh policies for Web crawlers. ACM Trans. Database Syst. 28, 4 (December 2003), 390–426. DOI:https://doi.org/10.1145/958942.958945](https://dl.acm.org/doi/10.1145/958942.958945)
- [Cho, Junghoo & Garcia-molina, Hebj & Icejfix, Principaladvisei. (2001). Crawling The Web: Discovery And Maintenance Of Large-Scale Web Data. ](https://oak.cs.ucla.edu/~cho/papers/cho-thesis.pdf)

**Comment by elvesrodrigues** [comment]
Resultados preliminares para estimadores de acesso regular: https://github.com/elvesrodrigues/estimators/blob/master/main.ipynb

**Comment by elvesrodrigues** [comment]
Esta issue foi dividida em outras menores, sendo:
- https://github.com/MPMG-DCC-UFMG/C04/issues/236
- https://github.com/MPMG-DCC-UFMG/C04/issues/237
- https://github.com/MPMG-DCC-UFMG/C04/issues/238
