### ISSUE TITLE
Desenvolvimento de mecanismos para versionamento

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C01#16]
## Comportamento esperado

Controle de versão das coletas para quando um dado for alterado, adicionado ou excluído. É preciso um mecanismo para registrar tudo feito na coleta (valores e URLs geradas, passo executados de fato, links navegados)  para que seja possível revisitar no futuro.

## Comportamento atual

Atualmente, as coletas são executadas através de instâncias que possuem apenas um período de execução, mas não temos os registros das requisições feitas ou dos dados coletados de fato.

## Passos para reproduzir o erro

Não se aplica.

## Especificações da Coleta

Não se aplica.

**Comment by rennancordeiro** [comment]
Substituída pela #735
