### ISSUE TITLE
Seleção: Desenvolver mecanismos para o processamento de formulários dinâmicos

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C01#2]

**Comment by TalesPanoutsos** [comment]
Exemplo de lista de passos:
step_list = [
&emsp;                       [print,['Teste']]
&emsp;                       [str,[0124],'replace',['4','3'],'find',['3']],
&emsp;                       [np.array,[Action([test, 'T', 'shape']).execute()], 'sum', []],
&emsp;                       [select,[drive, xpath, step_list_select]]
&emsp;                       [select,[drive, xpath, [
&emsp;&emsp;                                              [passo1],
&emsp;&emsp;                                              [passo2],
&emsp;                       ]]],
&emsp;                       [if_equal,[x,y,[                       
&emsp;&emsp;                                              [passos ser executado caso x == y]
&emsp;                       ],[
&emsp;&emsp;                                              [passos ser executado caso x != y]
&emsp;                       ]]]
#lembrar que caso x ou y seja uma função, passa-la em forma de step, pois caso contrário ela seria executada quando essa a lista fosse instanciada
&emsp;		       ]
