### ISSUE TITLE
Melhorias do sistema de exibição de logs

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#211]
Os logs das coletas passarão a serem enviados para o Kafka, sendo consumidos pelo banco de dados. A interface passará a consumir os logs armazenados no banco para exibí-los.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/211?planning-poker) with ZenHub @brenomatos @lucasaug @louisaturn
