### ISSUE TITLE
Investigação da Ferramenta Playwright

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#2321]
Epic que descreve a investigação da ferramenta Playwright, o levantamento de seus requisitos, suas possíveis integrações e seus diferenciais. O objetivo dessa investigação é apresentar o Playwright como uma alternativa ao Puppeteer no nosso sistema e avaliar a possibilidade de uma transição.

> Eu encontrei o Playwright por acaso, quando fizemos aquele esforço de organizar as issues em Epics e calcular a dificuldade delas (Poker Planning). Buscando fazer estimativas melhores nas issues da Epics de Processamento Dinâmico e de Issues Gerais, pesquisei coisas relacionadas a elas, que envolviam orquestração do Puppeteer com o Scrapy, instabilidade de coletas que envolviam o processamento dinâmico, além de outras features necessárias relacionadas às instâncias de browsers criadas. Alguns exemplos: Inserção de cookies, manejo de abas, downloads do dinâmico, integração de rotação de IPs, coleta em casos com iframes.
> Lendo sobre o Playwright, senti que as diferenças entre ele e o Puppeteer poderiam fazer muita diferença na resolução dos nossos desafios atuais.

**Comment by rennancordeiro** [comment]
@lucasaug e @louisaturn Podem criar issues das etapas que vocês ja fizeram e também que ainda precisam fazer e associar a essa epic? O objetivo é documentar todo o progresso feito em relação à investigação da viabilidade dessa ferramenta.

**Comment by rennancordeiro** [comment]
Olá @louisaturn e @lucasaug, como todas as issues foram finalizadas e já temos outra epic dos passos seguintes relativos ao Playwright, posso fechar essa epic e dar como finalizada?

**Comment by lucasaug** [comment]
De acordo!
