### ISSUE TITLE
Teste inicial de Integração do Playwright com nosso sistema

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#2326]
Após o levantamento dos requisitos para o uso do Playwright (#2325) , iniciamos a investigação da integração dele no nosso sistema para avaliar a possibilidade de seu uso no Processamento Dinâmico.

**Comment by lucasaug** [comment]
Uma investigação inicial foi feita no sistema distribuído para analisar a viabilidade do uso do Playwright. O esforço inicial foi de garantir que os requisitos da biblioteca do Playwright fossem atendidos (#2325) e o sistema continuasse funcionando corretamente. Com algumas atualizações de bibliotecas e pequenas mudanças no código, foi possível atender esses requisitos, e até o momento todas as funcionalidades do sistema parecem estar intactas. Além disso, também foi possível atender os requisitos da biblioteca Scrapy-Playwright.
A seguir, fizemos uma tradução inicial dos passos disponíveis para utilizar as chamadas do Playwright no lugar das do Pyppeteer. Também foram necessárias algumas alterações na geração de código como um todo. A maioria dos passos pôde ser traduzida preliminarmente sem nenhum problema, e a adaptação para a sintaxe do Playwright foi bem simples.
Com essa versão inicial prototipada, verificamos a viabilidade de utilizar a biblioteca Scrapy-Playwright, para evitar que tenhamos que manter um middleware próprio para essa integração. Uma preocupação que tínhamos era que essa biblioteca não fosse flexível o suficiente para permitir a integração com o nosso módulo de passos. Após alguns testes iniciais, a biblioteca pareceu bastante flexível, e até o momento não foi observado nenhum empecilho em utilizá-la com o mecanismo de passos.
Em conclusão, a migração para o Playwright parece bem viável. Os requisitos puderam ser atendidos sem problemas e tivemos algumas evidências práticas de que a tradução poderá ser feita sem nenhum entrave muito grande. Como essa primeira avaliação foi bem sucedida, continuaremos com a criação de uma versão inicial do sistema com o Playwright em X. O código dessa implementação está disponível na branch X.
