### ISSUE TITLE
Coleta - Licitações de Contagem

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C01#283]
http://www.contagem.mg.gov.br/?se=licitacoes_fechados&pagina=4

**Comment by gabrielcrds** [comment]
Na verdade esse precisa de coletor dinâmico para baixar os arquivos.

**Comment by aluiza22** [comment]
Foi possível fazer a coleta com as configurações avançadas, mas alguns arquivos (.doc) não foram baixados pelo webdriver não salvar automaticamente os arquivos, e sim abrir uma tela do sistema.
