### ISSUE TITLE
Coleta - Licitações de Juiz de Fora

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C01#284]
https://www.pjf.mg.gov.br/secretarias/cpl/editais/resultados/2019/janeiro/index.php

Edit: Veja comentários.

**Comment by gabrielcrds** [comment]
Conferindo sobre usar nome do mês nas urls com template.

**Comment by gabrielcrds** [comment]
A partir da url abaixo e pegando links em tags option atributo value, é possível descobrir todas as urls. Porém, não da pra baixar os arquivos pequeno com o wget por causa de problemas de certificado da página. É possível com scrapy, então temos que esperar alterações feitas em #356 

https://www.pjf.mg.gov.br/secretarias/cpl/editais/resultados/outros_anos.php

**Comment by gabrielcrds** [comment]
Da erro de ssl nos arquivos mesmo fazendo a coleta com o scrapy, então é impossível baixar os arquivos com as configurações possíveis.

**Comment by caiocvsilva** [comment]
A mesma coleta foi pedida em #561 . Logo as duas serão unificadas.
