### ISSUE TITLE
Coleta - Licitações de Uberaba

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#297]
http://www.uberaba.mg.gov.br/portal/conteudo,29557

**Comment by caiocvsilva** [comment]
Ao tentar diagnosticar a página, fui recebido por uma mensagem de ausência de SSL e ao clicar em alguns links fui redirecionado para páginas de fraude.

**Comment by caiocvsilva** [comment]
Este mesmo pedido foi feito na issue #624, que possui mais informações sobre a coleta. Portanto, esta será arquivada, para que o esforço seja focado na issue #624 .
