### ISSUE TITLE
Coleta - Licitações de Belo Horizonte

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#299]
https://prefeitura.pbh.gov.br/licitacoes

**Comment by brenomatos** [comment]
Depende da implementação da funcionalidade "for each" para navegar nas páginas
![image](https://user-images.githubusercontent.com/19504276/119858222-a4b6cc00-beea-11eb-95cb-585482c17a7b.png)

**Comment by caiocvsilva** [comment]
Esta coleta se encontra fora do template e não está sendo necessária no momento. Caso ela seja requerida no futuro, favor abrir uma nova issue seguindo o [template](https://github.com/MPMG-DCC-UFMG/C01/wiki/Template-de-Issue-(outros-trilhas)).
