### ISSUE TITLE
Resolver problemas com acesso concorrente no banco

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#307]
Atualmente utilizamos um banco de dados SQLite para armazenar dados do sistema, porém estamos tendo alguns problemas para acesso concorrente (tive alguns problemas onde o módulo de downloads de arquivos tentava escrever muitas vezes seguidas no banco e falhava). Avaliar outras alternativas possíveis, ou se existe alguma forma de melhorar a performance do SQLite nesse caso.

Caso usemos um SGBD diferente, verificar com o pessoal do MP se já existe uma estrutura com esse SGBD que possa ser re-usada.

**Comment by louisaturn** [comment]
Acrescentando informações nesta issue: após alguns testes, descobri que o novo sistema de logs contribui com o problema do trancamento do banco. Ao realizar uma coleta com a opção "baixar arquivos" habilitada, o módulo Log Writer atrapalha o funcionamento correto do File Downloader, devido ao acesso constante ao banco.

**Comment by rennancordeiro** [comment]
No novo sistema distribuido, estamos usando Postgres, logo, esse problema será resolvido.
