### ISSUE TITLE
Executáveis binários no repositório

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#330]
Atualmente, estamos armazenando dependências do sistema no repositório. Isso é um problema, visto que possíveis atualizações nessas ferramentas deverão ser feitas manualmente. Além disso, essas dependências contêm arquivos binários, cujo armazenamento não é aconselhável no Git. Precisamos encontrar uma alternativa para inclusão essas dependências.

**Comment by louisaturn** [comment]
Os últimos passos relacionados a essa issue estão relacionados ao script de build dos componentes do Scrapy Cluster realizados pela @LorenaMendes e à busca de ferramentas semelhantes ao Maven para uso em Python. Uma solução pode ser o uso do software [PyBuilder](https://pybuilder.io/), a ser estudado no retorno das atividades.

**Comment by rennancordeiro** [comment]
Esses executáveis já foram removidos aqui:https://github.com/MPMG-DCC-UFMG/C01/commit/d7b2057d319f9f3b3af11e0691205550e8ee59d8
