### ISSUE TITLE
Tirar configuração de templated URLs da spider

### ISSUE THREAD

**Issue by LorenaMendes** [MPMG-DCC-UFMG/C01#361]
Atualmente, a função generate_initial_requests() é chamada no start_requests() da spider. Contudo, essa função não é usada no Scrapy Cluster, sendo necessário executá-la em outro lugar que tenha acesso ao config (por exemplo no parse ou no crawler manager). Acredito que a melhor opção seja no crawler manager para não gerar execução repetitiva disso durante a coleta.

**Comment by rennancordeiro** [comment]
A adaptação de TempatedURLs para Scrapy Cluster já está documentada em outras issues
