### ISSUE TITLE
Pequena melhoria: formulário de download de arquivos: extensões permitidas

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#369]
Ao configurar um coletor, a decisão de baixar arquivos permite que o usuário escolha as extensões de arquivos a serem coletadas.

"Extensões de arquivo permitidas (separado por vírgula):"

Quando realizei minha primeira coleta com a interface, notei que o preenchimento "pdf, zip" (com espaço) não compreende a segunda extensão como um tipo permitido, como o preenchimento "pdf,zip". 

Tecnicamente, a instrução está correta, porém pode ser um pouco ambígua.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/369?planning-poker) with ZenHub @brenomatos @lucasaug @louisaturn
