### ISSUE TITLE
Coleta - Licitações de Bocaina de Minas

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C01#382]
https://www.camarabocainademinas.mg.gov.br/licitacoes-2018/

**Comment by aluiza22** [comment]
O link dá "Página não encontrada", mas navegando pelo site encontrei esse novo link de licitações: https://www.camarabocainademinas.mg.gov.br/publicacoes/licitacoes-e-contratos/ porém, não tem nada listado, nenhum links.
