### ISSUE TITLE
Coleta - Licitações de Bias Fortes

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C01#387]
https://pm-biasfortes.publicacao.siplanweb.com.br/licitacoes/painel

**Comment by caiocvsilva** [comment]
Os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/licitacoes_bias_fortes/data. Caso haja algum problema com a coleta, informe por meio dessa issue.
