### ISSUE TITLE
Melhorar a utilização das dependências do Scrapy Cluster

### ISSUE THREAD

**Issue by LorenaMendes** [MPMG-DCC-UFMG/C01#392]
Atualmente, Kafka, Zookeeper e Redis são instalados localmente com o projeto (via install.py). Uma possível melhoria é usar as instalações que já estão nas máquinas (quando existirem), usando senhas e demais parâmetros específicos passados pelas pessoas administradoras.

**Comment by rennancordeiro** [comment]
Issue defasada
