### ISSUE TITLE
Monitoramento de progresso de coleta

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#397]
Implementação de um sistema de monitoramento de progresso de uma coleta, isto é, qual proporção da coleta toda já foi efetuada em um dado momento. A issue #172 tratava dessa tarefa, cuja solução foi desenvolvida na branch `issue-172`. Essa solução não foi integrada, porém, devido aos seguintes impedimentos:

- A solução não funcionaria em um ambiente distribuído
- A solução trava o banco de dados SQLite, sendo necessário o uso de outro SGBD (ver issue #307)

A solução utiliza requisições a URLs do próprio sistema para avisar quando a coleta a uma URL foi agendada e quando foi executada. A cada requisição, um valor no banco de dados é alterado, e a proporção coletada exibida na interface é igual ao (número de páginas coletadas)/(número de páginas agendadas).

Os próximos passos são
- Atualizar a branch `issue-172` com o master
- Resolver a issue #307 para impedir o travamento do banco de dados
- Alterar a implementação para transmitir os dados de agendamento/coleta do Scrapy pelo Kafka

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/397?planning-poker) with ZenHub @brenomatos @lucasaug @louisaturn

**Comment by lucasaug** [comment]
A branch do sistema distribuído já tem uma implementação desse mecanismo com os problemas resolvidos, e como essa branch entrará na master futuramente, essa questão está concluída.
