### ISSUE TITLE
Melhoria na notificação de erros no extrator de conteúdo de arquivos binários

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#401]
Dependendo de características de alguns PDFs a serem processados, o Apache Tika levanta algumas mensagens de erros. Deve-se conferir a essência desses erros coletados e cobrí-los com tratamento especial e/ou mensagens de exceção mais explicativas.

Exemplo de mensagem de erro obtida:

"message: <class 'TypeError'>-As tabelas não puderam ser acessadas devido a: Command '['java', '-Dfile.encoding=UTF8', '-Dorg.slf4j.simpleLogger.defaultLogLevel=off', '-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog', '-jar', '/home/elves/WorkSpaces/MPMG/tasks/doing/356/C04/venv/lib/python3.7/site-packages/tabula/tabula-1.0.4-jar-with-dependencies.jar', '--pages', '1', '--guess', '--format', 'JSON', '--silent', '/home/elves/test/sao_lourenco/data/files/06d791472d538b45351bac0b06f1f5fe.pdf']' returned non-zero exit status 1."

**Comment by rennancordeiro** [comment]
Funcionalidade de extração de binários foi removida, o que remove a necessidade dessa issue.
