### ISSUE TITLE
Erros dos testes de unidade do binary extractor

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#406]
Os testes relativos ao extrator de conteúdos de arquivos binários está com erros na detecção de arquivos do tipo Excel. Aparentemente, trata-se de uma atualização da biblioteca XLDR, que passa a suportar apenas os arquivos de extensão .xls:

https://xlrd.readthedocs.io/en/latest/
"This library will no longer read anything other than .xls files. For alternatives that read newer file formats, please see http://www.python-excel.org/."

Portanto, tanto os testes quanto o módulo ExcelExtractor deverão ser atualizados.

**Comment by lucasaug** [comment]
Esse problema foi resolvido na issue #443.
