### ISSUE TITLE
Integração do form parser no mecanismo de processamento dinâmico

### ISSUE THREAD

**Issue by TalesPanoutsos** [MPMG-DCC-UFMG/C01#412]
Para o mecanismo dos passos conseguir atomizar bastante os passos em mini-coletas, é necessário que ele saiba de antemão por onde seus "for"s estão percorrendo, assim ele pode executar cada possibilidade de valor para o iterador do for simultaneamente. Também temos que na maioria das vezes, os fors vão ser utilizados para percorrer opções de selects. Porém, nós só sabemos essas opções durante a execução dos passos, quando a função opcoe_em descobre eles. O mecanismo de form parser vem para preprocessar os passos, mudando os lugares onde tem o uso da função opcoes_em pela lista de opcoes daquele select, porém antes da execução, claro se isso for possível. Dessa forma, como sabemos por onde alguns "for"s, vão estar iterando, podemos rodas cada iteração desse for simultaneamente.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/412?planning-poker) with ZenHub @louisaturn @matheusfebarbosa

**Comment by lucasaug** [comment]
Acredito que não seja necessário utilizar o módulo form parser pra isso, já que em tempo de execução do coletor dinâmico já estaremos com a página aberta, e mandar mais uma requisição à página, especialmente envolvendo um módulo que lida estaticamente com a página (e portanto pode não refletir o que aparece pro dinâmico) parece uma potencial fonte de travamentos e bugs. Além disso, pensando em paralelização de passos, acredito que não haja motivo para limitar essa frente ao passo "for", já que temos vários passos de iteração no sistema. Também é necessário considerar a possibilidade de uma iteração influenciar a próxima, inviabilizando essa paralelização. De toda forma podemos pensar futuramente em o que fazer com essa issue, mas acredito que são necessárias mais evidências da necessidade dessa frente, visto que deve ser uma investigação bem longa e exigir muitos recursos.
