### ISSUE TITLE
Despesa com viagens

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C01#42]
http://transparencia.mg.gov.br/estado-pessoal/viagens

**Comment by LorenaMendes** [comment]
Página apresenta erro de _timeout_ desde 23/02/2020, impedindo a coleta durante os últimos dias.

**Comment by louisaturn** [comment]
Retornei essa issue para "TO DO" por se tratar de uma coleta mal sucedida. Foi realizada no início de 2020 como coleta emergencial, portanto seu coletor não chegou a ser configurado no nosso sistema atual. Ela está na lista de fontes cuja urgência de coleta será avaliada pelo pessoal do MP.

**Comment by brenomatos** [comment]
Olá @rafaelglater , poderia refazer a issue de acordo com nosso template disponível [aqui](https://github.com/MPMG-DCC-UFMG/C01/wiki/Template-de-Issue-(outros-trilhas)), por favor? Estávamos discutindo essa issue e ficamos em dúvida sobre exatamente o que deve ser coletado, etc.

**Comment by caiocvsilva** [comment]
@rafaelglater, Favor atualizar a issue de acordo com o [tamplate](https://github.com/MPMG-DCC-UFMG/C01/wiki/Template-de-Issue-(outros-trilhas)) , caso ela não seja atualizada em 7 dias, a mesma será fechada.
