### ISSUE TITLE
Remoção de códigos antigos do repositório

### ISSUE THREAD

**Issue by rennancl** [MPMG-DCC-UFMG/C01#4249]
## Comportamento Esperado
Que todos códigos sejam usados. Deve fazer uma pesquisa profunda para avaliar o que pode ser removido. 

## Comportamento Atual
Temos standalone-crawlers e módulos ultrapassados no src, que devem ser removidos pois não são usados e não se aplicam mais

**Comment by lucasaug** [comment]
O caso específico dos códigos que utilizam o Pyppeteer estão cobertos pela issue https://github.com/MPMG-DCC-UFMG/C01/issues/4320, pois em alguns casos deve ser feita a remoção, e em outros deve ser feita a tradução do código para o Playwright.
