### ISSUE TITLE
Portal AMM (Associação Mineira de Municípios)

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#430]
URL base: http://www.diariomunicipal.com.br/amm-mg/

**Comment by brenomatos** [comment]
Utiliza páginas dinâmicas. Ao clicar em uma data no calendário, um pop-up aparece com os arquivos disponíveis para download
![image](https://user-images.githubusercontent.com/19504276/117342063-2cc02d80-ae79-11eb-9692-4d6fb34a567f.png)

**Comment by caiocvsilva** [comment]
Esta coleta foi finalizada e os dados se encontram em /datalake/ufmg/webcralwerc01/PortalAMM/diarioMunicipal/data. Caso seja necessário, favor abrir issue.
