### ISSUE TITLE
Correção de bug de permanência de coletores na execução Docker standalone

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#434]
Ao configurar um sistema por uma execução do sistema em uma imagem Docker, as configurações do coletor desaparecem. Desejamos que, na mesma imagem, a configuração seja mantida em sua reexecução.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/434?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by elvesrodrigues** [comment]
Acredito que esse problema já foi resolvido na versão dockerizada atual da solução distribuída, que será a nova branch master em breve. Ainda assim, adicionarei minha expectativa de story point.
