### ISSUE TITLE
Portal Transparência Juiz de Fora

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#442]
Deve ser feita de todo o site (com a profundidade máxima que pode ser alcançada) e deve manter todas as páginas do domínio.
Essa coleta será usada pela F01 que faz o processamento de portais da transparência.

URL: https://www.pjf.mg.gov.br/transparencia/

**Comment by brenomatos** [comment]
Obs: Algumas telas são facilmente coletáveis (html puro). Outras precisam de clique de botão para realizar download.

**Comment by caiocvsilva** [comment]
Essa issue foi dividida em issues mais específicas e com demandas atuais, como #795 #556 #866 . Portanto, está issue será fechada. Caso necessária, poderá ser reaberta.
