### ISSUE TITLE
Adaptar o crawler manager para a solução distribuida baseada em Scrapy Cluster.

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#444]

**Comment by elvesrodrigues** [comment]
`Crawler Manager` já foi incorporado na arquitetura atual proposta da solução distribuída ([PR-695](https://github.com/MPMG-DCC-UFMG/C01/pull/695)). Sendo o responsável por gerenciar os `Spider Managers` que executam em distribuído, controlando os spiders.
