### ISSUE TITLE
Inclusão do método HTTP na requisição do Puppeteer

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#448]

**Comment by lucasaug** [comment]
Lembrando de incluir o body da requisição no Puppeteer também, pois possivelmente vamos incluir a configuração desse elemento na interface também (e a coleta puramente estática já passa esse body pra requisição).

**Comment by lucasaug** [comment]
Na issue #509 a passagem do método e conteúdo da requisição passa a ser usada efetivamente. Dessa forma, incluí a passagem desses dados para o Pyppeteer na branch respectiva à essa issue.
