### ISSUE TITLE
Integração do mecanismo de passo com a importação de configurações

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#449]

**Comment by louisaturn** [comment]
Após a integração do mecanismo de loading dos passos, o sistema se torna capaz de carregar os passos dos coletores importados. Porém, esse carregamento não é automático: é necessário abrir a aba de processamento dinâmico para que isso ocorra. Além disso, temos um problema quando tentamos importar um coletor após configurar alguns passos. Neste caso, os passos do JSON de configuração são desprezados ao salvar o coletor - como documentado aqui pelo @caiocvsilva: https://github.com/MPMG-DCC-UFMG/C01/issues/281#issuecomment-931405725

Dessa forma, optamos por fechar essa issue com a entrada da [PR 281](https://github.com/MPMG-DCC-UFMG/C01/pull/281) e abrir novas issues para especificar os comportamentos esperados:
https://github.com/MPMG-DCC-UFMG/C01/issues/775
https://github.com/MPMG-DCC-UFMG/C01/issues/776
