### ISSUE TITLE
Adaptação da resolução do Playwright para configuração da página

### ISSUE THREAD

**Issue by rennancl** [MPMG-DCC-UFMG/C01#450]
## Comportamento Esperado
Desejamos que seja possível configurar a resolução de execução do navegador na coleta dinâmica. O usuário terá a possibilidade de escolher a resolução desejada. Essa resolução pode ser escolhida com a escolha de uma largura e altura arbitrária, como também através de uma lista de resoluções usuais na indústria.

## Comportamento Atual
O navegador do Playwright é executado sempre na resolução de 1280 x720, que pode alterar a visibilidade de alguns elementos em páginas responsivas.

## Especificações da Coleta

Coletas dinâmicas em páginas recursivas

**Comment by louisaturn** [comment]
Olá pessoal!
Precisamos atualizar essa especificação caso ele se aplique ao processamento dinâmico com Playwright. Se não, podemos fechá-la :)

**Comment by lucasaug** [comment]
Atualizei a especificação da issue para refletir a mudança para o Playwright.
