### ISSUE TITLE
Problema em downloads específicos na coleta de São Bento Abade

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#452]
## Comportamento Esperado
Todos os arquivos que passem pela filtragem especificada em uma coleta devem ser coletados.

## Comportamento Atual
Ao coletar os dados de São Bento Abade (https://www.saobentoabade.mg.gov.br/site/index.php/editais?limit=0) percebi uma certa inconsistência no download dos arquivos. Na primeira vez que coletei, o arquivo referente à "PL 044/2020" não foi baixado. A coleta foi encerrada e depois tentei executá-la novamente. Dessa vez o arquivo foi baixado com o nome "8c4f1ed703dd032c596deeb76e7d1696.zip".

Acredito que essa inconsistência pode ter a ver com arquivos grandes sendo baixados próximos do fim do processo de coleta, mas não tenho certeza. Como esse é um bug intermitente, pode ser difícil de reproduzir. Além disso, é um bug antigo, então talvez não ocorra mais, mas é necessário checar. Também pode funcionar diferentemente no sistema distribuído.

## Passos para reproduzir o erro

  1. Configurar uma coleta para os editais de São Bento Abade.
  2. Executar a coleta e verificar se o arquivo indicado foi coletado.
  3. Em caso negativo, confirma-se o erro. Em caso positivo, é recomendado repetir o teste algumas vezes. Caso o arquivo seja coletado todas as vezes, talvez não seja mais possível reproduzir o erro.

## Especificações da Coleta
Não disponível.

**Comment by lucasaug** [comment]
Investigando outras coletas, suspeito que o sinal `spider_closed` está sendo disparado pela Spider cedo demais. Talvez quando não há mais links para coletar ele finaliza, mesmo se ainda houverem arquivos ou páginas sendo baixadas. Investigar essa direção.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/452?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by elvesrodrigues** [comment]
@caiocvsilva e @matheusfebarbosa eu dei **8 pontos** para essa issue por considerar que, como documentado nela, o problema ocorre às vezes sim e outras não, reproduzi-lo pode não ser simples. Ou mesmo validar que a solução esteja válida.

Porém, comparado a outras issues, acho que 8 pontos é mesmo um pouco de exagero. Então vou alterar minha pontuação para 5, tendo como pontuação final 5 para a issue (pela regra que definimos de planning poker).

**Comment by caiocvsilva** [comment]
Este erro aparentemente está relacionado a issue #931, por este motivo esta será fechada.
