### ISSUE TITLE
Problemas na visualização da configuração de "Tratamento"

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#453]
A tela de Tratamento na configuração de um coletor não reflete adequadamente o estado configurado. Temos dois problemas:

- Ao criar uma nova coleta, os checkboxes no fim da página de Tratamento (com os textos " Manter valores faltantes", "Elementos não-visíveis devem ser capturados" e "Decodificar datas") são exibidos desmarcados. Porém, analisando o página, vemos que os inputs possuem o valor "True". Ao salvar a configuração, podemos confirmar que o valor errado foi salvo checando a entrada criada no banco de dados.

- Suponha que configuramos uma coleta, preenchemos dados na seção "Tratamento" e salvamos. Ao abrir a coleta recém-criada em modo de edição, os dados de tratamento não são exibidos.

Da forma atual, a página pega os campos da seção Tratamento e gera um JSON que é inserido em um input hidden na página, e a seguir mandado pro servidor e salvo. Acredito que modificar para incluir esses parâmetros como parte do modelo CrawlRequest e usar os próprios forms do Django pra renderizar os campos resolveria ambos os problemas. A função de importação da parte de Tratamento em `create_crawler.js` deve ser removida nesse caso, e também seria necessário corrigir o acesso aos parâmetros de Parsing no "caminho" do servidor até a spider.

**Comment by louisaturn** [comment]
Após discussões, optamos por desativar todos os módulos de extração dos conteúdos coletados. Módulos **parsing_html** e **binary_extractor** serão deletados do repositório.

**Comment by louisaturn** [comment]
Issue da deleção dos módulos: #481
