### ISSUE TITLE
Portal Transparência Sete Lagoas

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#456]
Deve ser feita de todo o site (com a profundidade máxima que pode ser alcançada) e deve manter todas as páginas do domínio.
Essa coleta será usada pela F01 que faz o processamento de portais da transparência.

URL: https://transparencia.setelagoas.mg.gov.br/

**Comment by brenomatos** [comment]
É possível baixar um pdf com todos os registros em cada categoria. Os dados são apresentados, inicialmente, de forma tabular. Para exportá-los é necessário clicar no botão PDF
![image](https://user-images.githubusercontent.com/19504276/117341650-c9ce9680-ae78-11eb-9724-3a642c8ae560.png)
