### ISSUE TITLE
Coleta de documentos de obras TCE-MG

### ISSUE THREAD

**Issue by pedroharaujo** [MPMG-DCC-UFMG/C01#472]
**Comportamento Esperado**
Requisição da extração de documentos pdf relativos aos contratos e html  com informações das obras listadas no portal geoobras do TCE-MG. Objetifica-se a extração de documentos de obras públicas de Minas Gerais através dos quais seja possível extrair a data de início da obra e prazo de término, viabilizando o monitoramento do estágio da obra.

**Comportamento Atual**
Até o momento, não possuímos dados confiáveis referentes às licitações e contratações das obras.

**Localização**
Não se aplica.

**Detalhes da Fonte**
Os dados a serem extraídos podem ser encontrados no portal geoobras do TCE-MG, no link [https://geoobras.tce.mg.gov.br/cidadao/] (https://geoobras.tce.mg.gov.br/cidadao/) após realização da consulta para determinado conjunto de parâmetros.  São de nosso interesse as obras vinculadas à área de educação (escolas, creches, quadras esportivas, coberturas de quadras esportivas e afins) de todos os munícipios de MG. 
Ao acessar as informações de determinada obra, deseja-se a extração do html da página disponível na aba “Dados da Obra”, bem como a extração dos documentos de contrato, disponíveis na aba “Documentos”  - “Contratação” e dos cronogramas físico financeiros do licitante vencedor, disponível em “Documentos” – “Licitação” – “Licitante Vencedor”.

**Detalhes da Trilha**
Os dados aqui solicitados são de interesse da trilha F05, sob coordenação de Matheus Barros (matheusbarrosp@gmail.com).

**Screenshots e Links**
Os screenshots a seguir demonstram o processo de uma busca manual para a obra “COBERTURA DA QUADRA DO BAIRRO CAMPOS ELÍSEOS” no município de Alfenas a partir do portal geoobras com comentários sobre os dados a serem extraídos.

![i1](https://user-images.githubusercontent.com/52477401/118557558-b9050700-b73b-11eb-9c82-3b9fbe123f0b.png)

![i2](https://user-images.githubusercontent.com/52477401/118557590-c1f5d880-b73b-11eb-9ac1-07a5b0ef5334.png)

![i3](https://user-images.githubusercontent.com/52477401/118557641-dcc84d00-b73b-11eb-9b73-24a152150a6c.png)

O conteúdo dessa página deve ser extraído - html.

![i4](https://user-images.githubusercontent.com/52477401/118557665-e356c480-b73b-11eb-8c33-9f64978cfff6.png)

O arquivo destacado deve ser extraído - pdf.

![i5](https://user-images.githubusercontent.com/52477401/118557683-e8b40f00-b73b-11eb-978b-5c341082319c.png)

O documento em destaque também deve ser extraído - pdf.

**Comment by caiocvsilva** [comment]
@pedroharaujo e @matheusbarrosp, esta fonte apresenta uma complexidade maior do que o sistema de coletas atual está preparado para atender, principalmente em relação aos arquivos a serem baixados. Entretanto, todas as páginas HTML pedidas foram coletadas com sucesso e se encontram em /datalake/ufmg/webcrawlerc01/dados_obras_tce_mg/data/raw_pages

Até o final desta semana poderemos dar uma atualização melhor sobre a coleta dos arquivos pedidos.

**Comment by caiocvsilva** [comment]
Atualização:

@pedroharaujo e @matheusbarrosp O sistema atual não consegue realizar o download de todos os arquivos baixados de forma filtrada, atendendo ao pedido da coleta, devido à forma em que eles são carregados no site. Entretanto, para que a trilha f05 não seja penalizada, foram criados dois coletores voltados apenas ao download de arquivos desta fonte.
Os coletores criados não conseguem fazer distinção do Beneficiário das obras, no caso Educação. Portanto, podem existir arquivos que pertencem a outras categorias.

Os arquivos se encontram em:
Contratante: /datalake/ufmg/webcrawlerc01/doc_obras_tce_mg_c/data/files
Licitante Vencedor: /datalake/ufmg/webcrawlerc01/doc_obras_tce_mg_lv/data/files

Atualmente, existem atualizações do sistema em teste que permitiriam a coleta unificada desta fonte. Assim que as mesmas forem implementadas poderá ser realizada uma recoleta da fonte, caso necessário.

Caso haja algum problema com os dados além dos já comentados, favor entrar em contato.
