### ISSUE TITLE
[35-consulta-a-pregoes] Arquivos salvos com extensão fora do padrão

### ISSUE THREAD

**Issue by gabriel-cangucu** [MPMG-DCC-UFMG/C01#482]
### Comportamento esperado

É esperado que os arquivos contidos no _datalake_ tenham extensões reconhecíveis, como PDF, TXT e XLS, para que seja possível manipulá-los utilizando funções do Python.

### Comportamento atual

Alguns arquivos estão com suas extensões em formato não reconhecível. Por exemplo, alguns arquivos compactados em /datalake/ufmg/c04/35-consulta-a-pregoes.zip estão com suas extensões no formato _pdf<número>_, o que prejudica o processamento automático e a contagem desses arquivos.

### Localização

/datalake/ufmg/c04/35-consulta-a-pregoes.zip

### Detalhes da fonte

Os arquivos com extensão não reconhecível foram obtidos descompactando-se o arquivo ZIP.

### Detalhes da trilha

Trilha: M03
Responsável: Gabriel Lima
Email: gabriel.lima@dcc.ufmg.br

### Screenshots e links

![img_issue](https://user-images.githubusercontent.com/33326107/119565158-fc84f400-bd7f-11eb-9f04-ccb34d2fb9b6.png)

**Comment by rennancordeiro** [comment]
@gabriel-cangucu Essa coleta foi feita antes do sistema que temos atualmente, ainda nos primeiros meses de 2020, isso significa que não segue os padrões de nomenclatura de arquivos atuais, que eu acredito já incluir as extensões corretamente. Por conta disso, a única solução seria refazer a coleta, assim, irei fechar essa issue!

Se o dado for necessário, podemos refazer a coleta no sistema atual, nesse caso, você poderia abrir uma nova issue com esse pedido, por favor?
