### ISSUE TITLE
Coleta de dados dos pagamentos de servidores da prefeitura de Governador Valadares.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#487]
## Comportamento Esperado
Requisição da extração de html com informações a respeito de pagamentos de servidores da cidade de Governador Valadares. A extração tem o objetivo de obter dados como matrícula, nome, cargo, remuneração, pensões e outros dados que possibilitem o monitoramento dos pagamentos recebidos pelos servidores da prefeitura de Governador Valadares.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Governador Valadares, no link (https://transparencia.valadares.mg.gov.br/servidores-por-nomes).
Para essa coleta, é necessário a filtragem por competência, que vai do período de 01/2013 até 04/2021 (ou mais atual possível). São de nosso interesse os dados de todos os servidores encontrados em cada período de competência, sendo esses dados as páginas html encontradas ao clicar em “Matrícula” de cada servidor.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir demonstram o processo de uma busca manual para os dados de um servidor na competência de 04/2021.

![passo1](https://user-images.githubusercontent.com/72928223/120331707-70fdec80-c2c4-11eb-8d2a-fb0745b80639.png)
![passo2](https://user-images.githubusercontent.com/72928223/120331765-7eb37200-c2c4-11eb-8490-dcc654944a3f.png)
![passo3](https://user-images.githubusercontent.com/72928223/120331773-8115cc00-c2c4-11eb-81b0-d592dadafcfa.png)
![passo4](https://user-images.githubusercontent.com/72928223/120331782-82df8f80-c2c4-11eb-958a-4183a5206b8f.png)

O conteúdo dessa última página deve ser extraído para cada servidor em cada período de competência - html.

**Comment by caiocvsilva** [comment]
Paginação no estilo 1,2,3,4,5...,76 não funciona com o para cada. URL parametrizada é possível, porem não é fácil encontrar os limites dos parâmetros.

**Comment by caiocvsilva** [comment]
@carbo6ufmg , Esta coleta foi finalizada, os dados encontram-se em /datalake/ufmg/webcrawlerc01/GovernadorValadares/servidores/. Caso haja algum problema, por favor relatar em issue.
