### ISSUE TITLE
Botões de ação na listagem de coletores

### ISSUE THREAD

**Issue by aluiza22** [MPMG-DCC-UFMG/C01#490]
## Comportamento Esperado
Pensando na facilidade de uso, seria interessante ter os botões para executar, parar e editar coletores já no painel que lista as coletas.

## Comportamento Atual
Hoje quando um coletor é salvo, o usuário é direcionado para a listagem e precisa entrar nos detalhes do coletor para poder executá-lo.

## Screenshots
Segue sugestão:
![SU01-painel_coletores](https://user-images.githubusercontent.com/20428782/120370664-e4165b80-c2e2-11eb-8ff7-533c2ea833c3.png)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/490?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn
