### ISSUE TITLE
Dicas e instruções de uso nos formulários

### ISSUE THREAD

**Issue by aluiza22** [MPMG-DCC-UFMG/C01#493]
## Comportamento Esperado
Pequenas dicas de uso pelos campos dos formulários melhoraria a experiência do usuário e a eficácia das coletas.

## Comportamento Atual
Alguns campos necessitam de instruções para serem utilizados da melhor forma possível. 

## Screenshots
Sugestão:
![SU05-dicas_sistema](https://user-images.githubusercontent.com/20428782/120371581-05c41280-c2e4-11eb-9c87-bdb32232a9c4.PNG)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/493?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn

**Comment by aluiza22** [comment]
Fechada com a PR #2557
