### ISSUE TITLE
Melhoria na apresentação dos logs

### ISSUE THREAD

**Issue by aluiza22** [MPMG-DCC-UFMG/C01#494]
## Comportamento Esperado
Mostrar mais linhas dos logs, com um mecanismo de rolagem ou um botão para abrir o arquivo ou mostrá-lo integralmente.

## Comportamento atual
Na página da coleta são apresentadas apenas as últimas linhas dos logs, e alguns erros ou comportamentos acabam não sendo acessíveis dessa forma. 

## Screenshots
Sugestão:
![SU06-log_completo](https://user-images.githubusercontent.com/20428782/120371786-4de33500-c2e4-11eb-9c72-a6c44f8f9500.PNG)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/494?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn

**Comment by louisaturn** [comment]
Pessoal, como discutimos no discord (canal de usabilidade), a apresentação de logs desenvolvida no ano passadopareceu satisfatória. A PR dela é essa aqui: https://github.com/MPMG-DCC-UFMG/C01/issues/211. Decidimos por fechá-la porque esse sistema de logs foi integrado (e melhorado! pelo Elves) ao sistema distribuído.
Parece estranho eu dizer isso, mas faz sentido colocar essa issue como dependente da entrada do sistema do distribuído?

**Comment by caiocvsilva** [comment]
O sistema atual já possui um botão que apresenta o log bruto na página de detalhes do coletor. Caso haja necessidade, essa issue poderá ser reaberta.
