### ISSUE TITLE
Coleta de dados das licitações da prefeitura de Governador Valadares.

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#497]
## Comportamento Esperado
Requisição da extração de html com informações a respeito das licitações da cidade de Governador Valadares. A extração tem o objetivo de obter dados como número/ano do edital, modalidade, objeto, status, cópia digital dos editais de licitação, cópia digital de todos os documentos relativos à licitação e divulgação do resultado da licitação.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da fonte
Os dados a serem extraídos podem ser encontrados no seguinte link: https://transparencia.valadares.mg.gov.br/licitacoes. Para essa coleta é necessário filtrar os dados por status especificando como “todos” (o que não é o padrão da página). São de nosso interesse as informações de todas as licitações, sendo esses dados as páginas html encontradas ao clicar no primeiro item de cada card de licitação, "número da licitação”.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e links (caso necessário)
Os screenshots a seguir demonstram o processo de uma busca manual para os dados da licitação “CO - 1/2021”.
![licitacoes1](https://user-images.githubusercontent.com/34161223/120483482-86d4e580-c388-11eb-9a27-851549b863c0.png)
![licitacoes2](https://user-images.githubusercontent.com/34161223/120483494-89cfd600-c388-11eb-98ce-506f83de41fd.png)
![licitacoes3](https://user-images.githubusercontent.com/34161223/120483505-8ccac680-c388-11eb-8cf0-c5338cd86868.png)
![licitacoes4](https://user-images.githubusercontent.com/34161223/120483513-8e948a00-c388-11eb-9270-cc9987220245.png)

**Comment by caiocvsilva** [comment]
@RitaRez, os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/licitacoes_governador_valadares/data. Caso haja algum problema com a coleta, informe por meio dessa issue.
