### ISSUE TITLE
Coleta de dados dos concursos públicos da prefeitura de Governador Valadares.

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#498]
## Comportamento Esperado
Requisição da extração de html com informações a respeito dos concursos públicos da cidade de Governador Valadares. A extração tem o objetivo de obter dados como cópia digital do edital de concurso, status, resultado, atos de nomeação, divulgação de recursos e respectivas decisões.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da fonte
Os dados a serem extraídos podem ser encontrados no seguinte link: https://transparencia.valadares.mg.gov.br/downloads/categoria/concurso-publico---edital-no-001-2019-002-2019-e-003-2019/94. São de nosso interesse as informações de todos os concursos, sendo esses dados todos os cards e pdfs anexados a estes.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e links (caso necessário)
O screenshot a seguir mostra os dados de interesse do edital do concurso Nº 027/2020/DRH:
![concursos1](https://user-images.githubusercontent.com/34161223/120485267-4d04de80-c38a-11eb-9470-6ecbdbf7faf8.png)

**Comment by caiocvsilva** [comment]
@RitaRez, os dados desta coleta já se encontram disponíveis em `/datalake/ufmg/webcrawlerc01/concursos_governador_valadares/data.` Caso haja algum problema com a coleta, informe por meio dessa issue.
