### ISSUE TITLE
Coleta de dados das contas públicas de Governador Valadares.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#503]
## Comportamento Esperado
Requisição da extração de pdf com informações a respeito das contas públicas da cidade de Governador Valadares. A extração tem o objetivo de obter dados como balancete da receita orçamentária, balancete da despesa orçamentária, relatórios de gestão fiscal, repasses e demais arquivos a respeito das contas públicas de Governador Valadares.
## Comportamento Atual
Não se aplica.
## Localização
Não se aplica.
## Detalhes da fonte
Os dados a serem extraídos podem ser encontrados no seguinte link: https://transparencia.valadares.mg.gov.br/contas-publicas.
São de nosso interesse mais de 536(até o momento) arquivos pdf a respeito das contas públicas, para cada item disponível no link é encontrado uma página que contém o arquivo pdf.
## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
O screenshot a seguir mostra como chegar a um arquivo de interesse.
![passo1](https://user-images.githubusercontent.com/72928223/121181247-2cc89a00-c838-11eb-9ef8-e93b9f0afe5c.png)

**Comment by caiocvsilva** [comment]
@carbo6ufmg , os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/contas_governador_valadares/data. Caso haja algum problema com a coleta, informe por meio dessa issue.
