### ISSUE TITLE
Coleta de dados da Estrutura Organizacional de Governador Valadares.

### ISSUE THREAD

**Issue by asafeclemente** [MPMG-DCC-UFMG/C01#505]
## Comportamento Esperado
Requisição da extração de html com informações a respeito da Estrutura Organizacional da cidade de Governador Valadares. A extração tem o objetivo de obter os dados:  **Endereço**, **Telefone**, **Horário de atendimento** e Registro das **competências** de cada Órgão Municipal ou Unidades administrativas, para que seja feito o monitoramento das Informações institucionais do município de Governador Valadares.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Governador Valadares, no link (https://transparencia.valadares.mg.gov.br/organograma).
Para essa coleta, é necessário expandir a árvore de opções e acessar cada um dos links como será detalhado nas screenshots.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir demonstram o processo de uma busca manual para essas informações.

1.  Clicar em “Expandir todos”.

![Screenshot from 2021-06-08 10-16-14](https://user-images.githubusercontent.com/54844202/121194927-8be0db80-c845-11eb-8923-aef5d82eae6f.png)

2.  Abrir cada uma das linhas.
![Screenshot from 2021-06-08 10-19-31](https://user-images.githubusercontent.com/54844202/121195050-a7e47d00-c845-11eb-8ace-3757ab06d8be.png)

Por exemplo a “Gerência de Manutenção” se obtém:
 
![Screenshot from 2021-06-08 10-19-57](https://user-images.githubusercontent.com/54844202/121195066-ac109a80-c845-11eb-96af-12fb0a5304dc.png)

**Comment by aluiza22** [comment]
@asafeclemente , os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/est_org_gov_valadares/data. Caso haja algum problema com a coleta, informe por meio dessa issue.
