### ISSUE TITLE
Coleta de páginas html do Portal de Transparência de Governador Valadares.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#506]
## Comportamento Esperado
Requisição da extração de páginas html do portal de transparência da prefeitura de Governador Valadares. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Governador Valadares.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Governador Valadares, nos seguintes links:

•https://transparencia.valadares.mg.gov.br/transparencia
•https://transparencia.valadares.mg.gov.br/servico-de-informacao-ao-cidadao
•https://transparencia.valadares.mg.gov.br/perguntas-frequentes
•https://transparencia.valadares.mg.gov.br/acessibilidade
•https://transparencia.valadares.mg.gov.br/ouvidoria

Para essa coleta, é necessário aguardar o carregamento da página

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by caiocvsilva** [comment]
@carbo6ufmg , os dados desta coleta já se encontram disponíveis em: 

 /datalake/ufmg/webcrawlerc01/transparencia_governador_valadares/data
/datalake/ufmg/webcrawlerc01/cidadao_governador_valadares/data/
/datalake/ufmg/webcrawlerc01/perguntas_governador_valadares/data/
/datalake/ufmg/webcrawlerc01/acessibilidade_governador_valadares/
/datalake/ufmg/webcrawlerc01/ouvidoria_governador_valadares/data/

Caso haja algum problema com a coleta, informe por meio dessa issue.
