### ISSUE TITLE
Permitir filtragem de limites para parâmetros injetados em formulários

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#518]
## Comportamento Esperado
A funcionalidade de filtrar limites de busca de parâmetros deve estar disponível em todos os módulos que utilizam os injetores.

## Comportamento Atual
A funcionalidade mencionada só é implementada nas Templated URLs.

## Passos para reproduzir o erro
Não aplicável.

## Especificações da Coleta
Não aplicável.

**Comment by lucasaug** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/518?planning-poker) with ZenHub @elvesrodrigues @rennancordeiro

**Comment by aluiza22** [comment]
Como a injeção de formulários foi removida do sistema (https://github.com/MPMG-DCC-UFMG/C01/issues/4248), esta issue será fechada. Caso surja a necessidade, poderá ser reaberta.
