### ISSUE TITLE
Erro de SSL em coleta de arquivos - Prefeitura de Olaria

### ISSUE THREAD

**Issue by brenomatos** [MPMG-DCC-UFMG/C01#527]
## Comportamento Esperado
Download dos arquivos de licitações da prefeitura de Olaria (2017-2021)

## Comportamento Atual
As coletas dos anos 2019-2021 funcionam corretamente. Nas coletas dos anos 2017 e 2018, ocorre o erro
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```
O erro interrompe a coleta. No caso, nenhum arquivo é baixado. O erro ainda deve ser investigado a fundo para entender melhor.

## Especificações da Coleta

  - URL Base: http://www.olaria.mg.gov.br/pagina-exemplo/processos-licitatorios-2017/
  - Explorar Link: Sim, profundidade 1
  - Baixar arquivos: extensões pdf,docx,doc,rar,zip
  
## Logs de Execução

[logs_execução.zip](https://github.com/MPMG-DCC-UFMG/C01/files/6711021/logs_execucao.zip)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/527?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by brenomatos** [comment]
O erro não pode ser mais reproduzido. Houveram atualizações no site.
