### ISSUE TITLE
Exploração e melhoria no sistema de injeção de valores

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#529]
## Comportamento Esperado
Os injetores de parâmetros devem contemplar todos os casos necessários para coletar as fontes de interesse.

## Comportamento Atual
Na avaliação do código que adiciona os injetores de parâmetros em formulários (https://github.com/MPMG-DCC-UFMG/C01/pull/519), foi notada a falta de algumas funcionalidades específicas na injeção de caracteres alfabéticos:

- Um parâmetro que permita passar um prefixo para cada sequência
- Um parâmetro que permita passar um sufixo para cada sequência
- Um parâmetro para informar o alfabeto a ser utilizado (quais caracteres usados para formar as palavras na sequência)

Avaliar se essa funcionalidade é necessária (se existem fontes que requerem essa flexibilidade do injetor), e se existem outras necessidades de injeção não contempladas nos tipos fornecidos.

## Passos para reproduzir o erro
Não aplicável.

## Especificações da Coleta
Não aplicável.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/529?planning-poker) with ZenHub @elvesrodrigues @lucasaug

**Comment by aluiza22** [comment]
Como a injeção de formulários foi removida do sistema (https://github.com/MPMG-DCC-UFMG/C01/issues/4248), esta issue será fechada. Caso surja a necessidade, poderá ser reaberta.
