### ISSUE TITLE
Injeção em formulários - notificações e exceções

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#531]
## Comportamento Esperado
Espera-se que o sistema notifique o usuário nos seguintes casos:

- Ao tentar injetar em um formulário que não existe na página;
- Quando o campo indicado não pôde ser identificado na página.

Além disso, o sistema pode apresentar, através dos logs de saída, as requisições feitas em tempo real.

## Comportamento Atual
Atualmente, não há avisos quando não se detecta formulários e campos. Também não é possível acompanhar as combinações de parâmetros que estão sendo injetadas. Dessa forma, o usuário tem pouca informação sobre as URLs que estão sendo exploradas e sobre o que houve nessas requisições.

## Passos para reproduzir o erro

Não aplicável

## Especificações da Coleta

Não aplicável

**Comment by louisaturn** [comment]
Observação: a identificação ou não de um formulário na página apenas passa a fazer sentido após a implementação das melhorias propostas na issue #528 .

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/531?planning-poker) with ZenHub @elvesrodrigues @lucasaug

**Comment by aluiza22** [comment]
Como a injeção de formulários foi removida do sistema (https://github.com/MPMG-DCC-UFMG/C01/issues/4248), esta issue será fechada. Caso surja a necessidade, poderá ser reaberta.
