### ISSUE TITLE
Detecção das opções em campos de formulários

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C01#532]
## Comportamento Esperado
Uitlizando a ferramenta de injetor de formulários, ao preencher um campo select de um formulário, espera-se que a ferramenta seja capaz de identificar as opções listadas.

## Comportamento Atual
Exemplo: [Página de licitações Prefeitura de Bias Fortes, modalidade convite](https://pm-biasfortes.publicacao.siplanweb.com.br/licitacoes/convite
).

![camposform](https://user-images.githubusercontent.com/48096245/124523030-a1590f00-ddcb-11eb-9883-c8263a4c6472.png)

Supondo a necessidade de injetar valores em "Natureza Procedimento", seria interessante que o injetor de parâmetros em formulários detectasse as opções para preencimento disponíveis ("AD - Adesão de Registro de Preço", "AG - Agricultura Familiar", etc).

## Passos para reproduzir o erro

Não aplicável

## Especificações da Coleta

Não aplicável

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/532?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn

**Comment by caiocvsilva** [comment]
Como a injeção de formulários foi removida do sistema (#4248), e suas funcionalidades foram passadas para o coletor dinâmico, esta issue será fechada. Caso surja a necessidade, poderá ser reaberta.
