### ISSUE TITLE
 Coleta de dados dos concursos públicos da prefeitura de Uberlândia. 

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#534]
## Comportamento Esperado
Requisição da extração de informações a respeito dos concursos da cidade de Uberlândia. A extração tem o objetivo de obter dados como nomeações, status de andamento, recursos e resultados.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Uberlândia).

## Detalhes da fonte
Os dados a serem extraídos podem ser encontrados no seguinte link: https://www.uberlandia.mg.gov.br/prefeitura/secretarias/administracao/concursos/concursos/.
São de nosso interesse todas as informações sobre os concursos na página.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links

Os screenshots a seguir mostram as informações de interesse da página:

![concursos](https://user-images.githubusercontent.com/34161223/124598860-76a69f00-de3b-11eb-8bb4-bcd562060a9c.PNG)
![concursos 2](https://user-images.githubusercontent.com/34161223/124598878-7ad2bc80-de3b-11eb-921c-1e471f6e8762.PNG)

Os screenshots a seguir mostram como chegar à lista de nomeações do cargo “Arquiteto”:

![nomeacoes](https://user-images.githubusercontent.com/34161223/124599086-a8b80100-de3b-11eb-9410-31ec00d3a708.PNG)
![nomeacoes2](https://user-images.githubusercontent.com/34161223/124599097-ab1a5b00-de3b-11eb-8ec9-cbac1c97fc15.PNG)

**Comment by caiocvsilva** [comment]
@RitaRez , os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/concursos_uberlandia/data. Caso haja algum problema com a coleta, informe por meio dessa issue.
