### ISSUE TITLE
Coleta de dados de informações municipais do portal de transparência de Uberlândia.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#539]
## Comportamento Esperado
Requisição da extração de html com informações a respeito das informações municipais da cidade de Uberlândia. A extração tem o objetivo de obter os dados:  Endereço, Telefone, Horário de atendimento e Registro das competências de cada Órgão Municipal ou Unidades administrativas, para que seja feito o monitoramento das Informações institucionais do município de Uberlândia.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Uberlândia).

## Detalhes da Fonte
Serão 2 fontes de coleta.
Para a primeira fonte, os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Uberlândia, no link: 
•https://www.uberlandia.mg.gov.br/portal-da-transparencia/atendimento-ao-publico/
Nessa coleta, é necessário expandir todas as categorias como será detalhado nas screenshots, desejamos o html dessa página.
Para a segunda fonte, os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Uberlândia, no link: 
•https://www.uberlandia.mg.gov.br/portal-da-transparencia/informacoes-municipais/
Nessa coleta, é necessário clicar em cada item que redireciona para outra página e então coletar o html da página redirecionada, detalhamento nas screenshots.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir demonstram o processo de uma busca manual para essas informações.
Para a primeira fonte:
![fonte1passo1](https://user-images.githubusercontent.com/72928223/124616976-f0935400-de4c-11eb-8f7b-8dcf0e704e31.png)
![fonte1passo2](https://user-images.githubusercontent.com/72928223/124616992-f426db00-de4c-11eb-84af-2e8daf717ee0.png)

Para a segunda fonte:
![fonte2passo1](https://user-images.githubusercontent.com/72928223/124617027-fb4de900-de4c-11eb-9ab3-9b7f22d2a583.png)
Clicar em cada item.
![fonte2passo2](https://user-images.githubusercontent.com/72928223/124617070-056fe780-de4d-11eb-8e19-875a5caa5653.png)

**Comment by brenomatos** [comment]
@carbo6ufmg os dados se encontram em:

/datalake/ufmg/webcrawlerc01/uberlandia_infos_municipais/data/raw_pages
/datalake/ufmg/webcrawlerc01/uberlandia_atendimento_publico/data/raw_pages

Caso haja algum problema, favor avisar nesta issue.

**Comment by CinthiaS** [comment]
Boa tarde, @brenomatos.

Seria possível colocar todos os dados de coleta em uma pasta para cada município?

Ou seja, ao invés de, /datalake/ufmg/webcrawlerc01/uberlandia_infos_municipais/data/raw_pages, os dados  do município de Uberlândia ficariam em /datalake/ufmg/webcrawlerc01/Uberlândia/

Obrigada!
