### ISSUE TITLE
Coleta das listas de medicamentos da CMED/ANVISA

### ISSUE THREAD

**Issue by pedrobrum** [MPMG-DCC-UFMG/C01#544]
## Comportamento Esperado

Requisição de coleta das listas de medicamento da CMED/ANVISA. É esperado que a coleta contenha os arquivos .xls disponíveis para cada ano e mês. A extração tem o objetivo de obter as listas de preços de medicamentos da ANVISA para que sejam tratadas e, futuramente, consumidas pelo Banco de Preços que está sendo desenvolvido pelo F03.

## Comportamento Atual

Não se aplica.

## Localização

Não possui nenhuma coleta atualmente.
Para fins de organização separar dados por ano.

## Detalhes da fonte

Os dados a serem extraídos podem ser encontrados na página de listas de preços da ANVISA, no seguinte link:

https://www.gov.br/anvisa/pt-br/assuntos/medicamentos/cmed/precos/anos-anteriores/anos-anteriores

A lista de preços dos medicamentos é atualizada anualmente em março. As listas estão separada por ano e por mês. São de nosso interesse todas as listas (de 2011 até o ano corrente), em formato .xls, presentes na segunda opção "2) Preços de Medicamentos para Compras Públicas".

## Detalhes da trilha

Trilha: F03
Responsável: Pedro Brum
Email: pedrobrum@dcc.ufmg.br

## Screenshots e links (caso necessário)
Como exemplo, na página de listas de preços da ANVISA, é esperado que se colete todos os arquivos para cada ano listados em "2) Preços de Medicamentos para Compras Públicas", conforme imagem a seguir:

![exemplo](https://user-images.githubusercontent.com/16280479/124757877-6a3a4900-df04-11eb-9133-a779e4bfa8a6.png)

**Comment by aluiza22** [comment]
@pedrobrum os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/medicamentos_cmed_anvisa/data/files. Porém, não foi possível filtrar os arquivos para download, todos os da lista foram baixados. Caso haja algum problema com a coleta, informe por meio desta issue.
