### ISSUE TITLE
 Coleta de dados da prestação de contas de Betim 

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#570]
## Comportamento Esperado
Requisição da extração da página contendo os arquivos referentes à prestação de contas da cidade de Betim. A extração tem o objetivo de obter todos os relatórios disponíveis na página. 

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Betim).

## Detalhes da fonte
http://servicos.betim.mg.gov.br/appsgi/servlet/teladinamica_q?ptprestacaocontas
São de nosso interesse o html da página e todos os arquivos presentes nessa.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram as informações de interesse da página:
![prestacao_contas](https://user-images.githubusercontent.com/34161223/125291256-90425d80-e2f7-11eb-9177-23cb494aded3.PNG)

**Comment by aluiza22** [comment]
@RitaRez os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/prestacao_contas_betim/data.  Caso haja algum problema com a coleta, informe por meio desta issue.

**Comment by carbo6ufmg** [comment]
Boa tarde, Ana Luiza.
Seria possível colocar todos os dados de coleta em uma pasta para cada município?
Por exemplo, para o município de Betim /datalake/ufmg/webcrawlerc01/Betim/prestacao_contas_betim/data e então todas as próximas coletas de Betim ficariam em /datalake/ufmg/webcrawlerc01/Betim/
Obrigado!

**Comment by aluiza22** [comment]
Bom dia, @carbo6ufmg ! Estamos movendo as coletas de Betim para contemplar a estrutura mencionada e vamos levar isso em conta para as próximas coletas.
