### ISSUE TITLE
 Coleta de dados do plano de metas do portal de transparência de Betim 

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#574]
## Comportamento Esperado
Requisição da extração das páginas contendo arquivos referentes aos planos de metas da cidade de Betim. A extração tem o objetivo de obter o html da página e arquivos presentes nessa.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.

Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Betim).

## Detalhes da fonte
http://servicos.betim.mg.gov.br/appsgi/servlet/teladinamica_q?ptplanometas
São de nosso interesse o html da página acima e ambos os arquivos de metas os quais o link se encontra na página.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram as informações de interesse da página:
![meta1](https://user-images.githubusercontent.com/34161223/125306599-bb33ae00-e305-11eb-827f-de6cc7cdb95f.png)

**Comment by aluiza22** [comment]
@RitaRez os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/plano_metas_betim/data. Caso haja algum problema com a coleta, informe por meio desta issue.

**Comment by aluiza22** [comment]
Coleta movida para /datalake/ufmg/webcrawlerc01/Betim/plano_metas_betim/data conforme solicitado na #570
