### ISSUE TITLE
Coleta de dados de informações institucionais do portal de transparência da prefeitura de Betim.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#576]
## Comportamento Esperado
Requisição da extração de arquivos com informações a respeito das informações municipais da cidade de Betim. A extração tem o objetivo de obter os dados:  Estrutura organizacional, Endereço, Telefone, Horário de atendimento e Registro das competências de cada Órgão Municipal ou Unidades administrativas, para que seja feito o monitoramento das Informações institucionais do município de Betim.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Betim).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Betim, no link: •http://servicos.betim.mg.gov.br/appsgi/servlet/teladinamica_q?ptinstitucional

Nessa coleta é necessário clicar em cada item que redireciona para o arquivo desejado.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
![passo1](https://user-images.githubusercontent.com/72928223/125457005-ffe6e976-e3b7-49c4-a037-6f5c0e5d256b.png)

**Comment by aluiza22** [comment]
@carbo6ufmg os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/Betim/infos_institucionais. Caso haja algum problema com a coleta, informe por meio dessa issue.
