### ISSUE TITLE
Coleta de dados das Leis Orçamentárias de Betim 

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#577]
## Comportamento Esperado
Requisição da extração da página e dos arquivos referentes às Leis Orçamentárias de Betim. A extração tem o objetivo de obter dados como PPA - Plano PluriAnual, LDO - Lei de Diretrizes Orçamentárias e LOA - Lei Orçamentária Anual. 

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Betim).

## Detalhes da fonte
http://servicos.betim.mg.gov.br/appsgi/servlet/teladinamica_q?ptorcamento
É de nosso interesse o html da página e os arquivos que tenham sua url na página acima. 

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram as informações de interesse da página:

![orcamentaria](https://user-images.githubusercontent.com/34161223/125457120-e590276c-e978-4570-94f7-7a9aa4dc3794.PNG)

**Comment by aluiza22** [comment]
@RitaRez os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/Betim/leis_orcamentarias_betim/data. Caso haja algum problema com a coleta, informe por meio desta issue.
