### ISSUE TITLE
Coleta de dados de Convênios de Montes Claros

### ISSUE THREAD

**Issue by asafeclemente** [MPMG-DCC-UFMG/C01#582]
## Comportamento Esperado
Requisição da extração de arquivos com informações a respeito dos convênios da cidade de  Montes Claros. A extração tem o objetivo de obter os dados de convênios Federias, Estaduais e Municipais.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Montes Claros).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Betim, a partir do link: 
https://transparencia.montesclaros.mg.gov.br/convenios

A partir da página base é necessário ir até "Convênios Geral" e na nova página obter o relatório de cada um deles.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
![Screenshot from 2021-07-13 12-06-29](https://user-images.githubusercontent.com/54844202/125476546-57a8783d-2504-41f3-8e86-1526cccd325e.png)

Obter o documento referente a cada um dos convênios:
![Screenshot from 2021-07-13 12-07-08](https://user-images.githubusercontent.com/54844202/125476553-ec66a2e0-a33a-439d-83da-0f5dd2e42cfd.png)

**Comment by aluiza22** [comment]
@asafeclemente os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/Montes_Claros/convenios. Caso haja algum problema com a coleta, informe por meio dessa issue.
