### ISSUE TITLE
Coleta de dados geral do portal de transparência da prefeitura de Betim.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#583]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Betim. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Betim.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Betim).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Betim, nos seguintes links:
•http://www.betim.mg.gov.br/home/41822%3B66975%3B03%3B0%3B0.asp
•http://servicos.betim.mg.gov.br/appsgi/servlet/teladinamica_q?ptleisacesso
•http://servicos.betim.mg.gov.br/appsgi/servlet/wmtranspinicial

E todos os html das páginas alcançáveis com 1 clique a partir de:
•http://servicos.betim.mg.gov.br/appsgi/servlet/wmtranspinicial

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by caiocvsilva** [comment]
@carbo6ufmg  A coleta dessa fonte foi realizada, com exceção da página principal, que ainda está sendo coletada. Os dados encontram-se em /datalake/ufmg/webcrawlerc01/Betim/, separados em leisdeacesso e transparencia. Caso haja algum problema com a coleta, favor informar por meio da issue.

**Comment by caiocvsilva** [comment]
@carbo6ufmg A coleta dessa fonte foi finalizada. Os dados encontram-se em /datalake/ufmg/webcrawlerc01/Betim/. Caso haja algum problema com a coleta, favor informar por meio da issue.
