### ISSUE TITLE
Coleta de dados das Informações sobre licitações de Montes Claros 

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#589]
## Comportamento Esperado
Requisição da extração do html das páginas referentes às licitações de Montes Claros. A extração tem o objetivo de obter dados como Unidade Gestora, descrição do objeto, tipo, situação, datas, número do processo, modalidade e valor.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/MontesClaros).

## Detalhes da fonte
http://ww2.montesclaros.mg.gov.br:82/pronimtb/index.asp?acao=1&item=2
É de nosso interesse o html da página acima, e o html das respostas a buscas contendo como filtro órgão = todos, unidade gestora como consolidada e prefeitura municipal e com os anos variando de 2013 até 2021. 

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram as informações de interesse da página:
![licitacao1](https://user-images.githubusercontent.com/34161223/125632444-06e3b89d-e119-4314-a2be-7c8c1c2b3c5b.png)
![licitacao2](https://user-images.githubusercontent.com/34161223/125632471-2de0f4a0-fc86-4702-b350-fdeeb2665847.png)
![licitacao4](https://user-images.githubusercontent.com/34161223/125632477-74ccbca3-21c9-498e-b7fe-b14cc35a35fd.PNG)

**Comment by matheusfebarbosa** [comment]
Olá, @RitaRez! A coleta dessa fonte foi realizada e os dados encontram-se em /datalake/ufmg/webcrawlerc01/MontesClaros/licitacoes 
Caso haja algum problema com a coleta, favor informar por meio desta issue.
