### ISSUE TITLE
Coleta da Legislação de Montes Claros

### ISSUE THREAD

**Issue by asafeclemente** [MPMG-DCC-UFMG/C01#599]
## Comportamento Esperado
Extração dos arquivos referentes as legislação de Montes Claros.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
**(e.g. /datalake/ufmg/crawler/webcrawlerc01/Montes Claros).**

## Detalhes da fonte
http://www.infraestrutura.montesclaros.mg.gov.br/pagina/legislacao

É de nosso interesse o html da página acima e o todos os arquivos que estão disponíveis nessa página. Para isso é necessário apenas clicar em cada um dos links e obter o PDF gerado.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links

![Screenshot from 2021-07-15 09-48-08](https://user-images.githubusercontent.com/54844202/125790628-bed6e605-7dd2-4b5b-b136-68fbbeb8a4c8.png)

**Comment by aluiza22** [comment]
@asafeclemente  os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/Montes_Claros/legislacao. Caso haja algum problema com a coleta, informe por meio dessa issue.
