### ISSUE TITLE
Documentação da wiki de "[1] Instalação e Execução"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#615]
# Comportamento Esperado
Deseja-se ter uma documentação extensa e completa de como deve ser feita a instalação e execução do sistema. Essa documentação deve ter screenshots com ilustrações de cada etapa e deve incluir as observações necessárias para cada uma das situações. Caso possível, essa documentação deve ser validada através da instalação em diferentes sistemas e da verificação da execução correta do sistema. Para isso, deve ser atualizar a página da wiki relativa a isso

# Comportamento Atual
Hoje, embora exista uma instrução para instalação, ela não inclui screenshots e detalhes desejados como sistemas operacionais suportados.

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by rennancordeiro** [comment]
@elvesrodrigues e @brenomatos, podem conferir, por favor?

**Comment by elvesrodrigues** [comment]
@rennancordeiro Para mim está ótimo. 

O único ponto a mencionar é que o trecho "siga as instruções de instalação da Java Runtime para o sistema desejado" na seção `Instalação` pode dar a entender que ele é um link para a instalação do Java para o sistema do leitor ou que há uma seção dedicada a isso, mas, aparentemente, esse não é o caso.

Além disso, "instruções" está escrito como "instruições", na primeira linha da seção `Execução com Docker`.

**Comment by brenomatos** [comment]
Está ótimo. Apenas algumas observações:

* Acho que seria bom adicionar o passo de baixar o repositório (seja clone ou baixando diretamente o zip), ainda mais supondo que essa documentação ficará como referência.
* Pequeno erro de digitação: alterar "mantar" para "manter" no primeiro parágrafo da instalação
* Adicionar observação de que é necessário criar a pasta 'data' no último passo da instalação via docker. Caso contrário, o comando não funciona.

**Comment by rennancordeiro** [comment]
Olá @elvesrodrigues e @brenomatos, obrigado pelas sugestões, acabei de fazer as correções. Podem verificar novamente, por favor?

**Comment by elvesrodrigues** [comment]
Para mim, está ótimo!

**Comment by brenomatos** [comment]
Tudo OK por mim !
