### ISSUE TITLE
Documentação da wiki de "[2] Entendendo a interface"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#616]
# Comportamento Esperado
Deseja-se ter uma documentação extensa e completa de como funciona a interface do sistema. Isto é, o que cada página significa, o que cada botão significa, em especial, numa visão de mais alto nível. Essa documentação deve ter screenshots com ilustrações de cada etapa e deve incluir as observações necessárias para cada uma das situações. 
As páginas a serem documentadas devem incluir as seguintes seções e suas respectivas partes (barras laterais, barras superiores etc):

- Coletores
- Criação de coletor 
- Página de um coletor

Para isso, deve ser atualizar a página da wiki relativa a isso

# Comportamento Atual
Está página está em branco, inclui apenas a estrutura, atualmente e, portanto não é possível ajudar os usuários

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by elvesrodrigues** [comment]
@aluiza22 e @lucasaug, vocês podem revisar a página [[2] Entendendo a interface](https://github.com/MPMG-DCC-UFMG/C01/wiki/%5B2%5D-Entendendo-a-interface), por favor?

**Comment by aluiza22** [comment]
Oi @elvesrodrigues ! Revisei a página e fiz alguns mini ajustezinhos de texto, mas tá tudo certinho 😊

**Comment by elvesrodrigues** [comment]
Obrigado, @aluiza22!

**Comment by lucasaug** [comment]
Boa tarde @elvesrodrigues! Também tomei a liberdade de alterar alguns detalhes que achei relevantes, mas podemos desfazer se acharem melhor. Fora isso, está tudo certo!

**Comment by elvesrodrigues** [comment]
@lucasaug obrigado!
