### ISSUE TITLE
Documentação da wiki de "[3] Criando um coletor"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#617]
# Comportamento Esperado
Deseja-se uma página da wiki que demonstre a configuração de um coletor simples, que utilize os mecanismos mais simples possíveis (ferramentas mais complexas devem ser documentadas em outras páginas). Esse coletor deve incluir o passo a passo que deve ser seguido e deve incluir uma screenshot para cada um deles, além disso, deve-se incluir a explicação para cada um desses passos, ou seja, o que cada um "faz" e qual é o propósito. Deve ser feito uma validação desse coletor com sua configuração e execução de fato.

# Comportamento Atual
Está página está em construção e alguns pontos podem ser completados e/ou melhorados.

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by brenomatos** [comment]
@matheusfebarbosa @aluiza22 Podem, por favor, conferir o texto que criei para essa issue na wiki? Caso esteja tudo de acordo, vou fechar a issue

**Comment by matheusfebarbosa** [comment]
> @matheusfebarbosa @aluiza22 Podem, por favor, conferir o texto que criei para essa issue na wiki? Caso esteja tudo de acordo, vou fechar a issue

Parece tudo ok. A única coisa que eu percebi, é que o final tem overlap com a próxima [parte](https://github.com/MPMG-DCC-UFMG/C01/wiki/%5B4%5D-Iniciando-e-Monitorando-uma-Coleta) da wiki.

**Comment by aluiza22** [comment]
Notei o overlap, mas tentei dar um seguimento disso no [4], não repetindo mas também citando o botão Começar. Fica a seu critério tirar ou não essa parte. Mas, por mim também está ok.

**Comment by brenomatos** [comment]
Ok pessoal, obrigado. Vou manter como está então. Se preciso, reabro a issue.
