### ISSUE TITLE
Documentação da wiki de "[4] Iniciando e Monitorando uma Coleta"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#618]
# Comportamento Esperado
Nesse ponto, deve se documentar os procedimentos de executar uma coleta e de monitorar sua execução. Isso deve envolver as seguintes explicações

- Como executar e parar uma coleta
- Elementos da interface de execução (como saber se o coletor já executou, como interpretar logs, como interpretar as instâncias)
- Onde os dados foram gerados e como estão armazenados/organizados (demonstração da estrutura de diretórios criadas)
- Como identificar os erros ocorridos na coleta. E caso a coleta tenha dado certo, como verificar que ocorreu corretamente, demonstrando os possíveis logs dentro dos diretórios e os dados coletados de fato

Todos esses pontos devem acompanhar explicações e screenshots.

# Comportamento Atual
Está página está em construção e alguns pontos podem ser completados e/ou melhorados. O coletor dessa página deve ser o mesmo da página [3] Criando um coletor

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by aluiza22** [comment]
Ei, @caiocvsilva e @brenomatos, vocês podem dar uma lida nessa página da wiki pra conferir se o que escrevi está ok, por favorzinho?

**Comment by brenomatos** [comment]
@aluiza22 ficou ótimo. Uma sugestão apenas seria explicitar que o nome dos arquivos de log são o seu ID de coleta (não sei se isso fica óbvio para quem nunca usou a ferramenta).

**Comment by caiocvsilva** [comment]
Concordo com o @brenomatos . De resto está tudo ótimo.

**Comment by aluiza22** [comment]
Ajuste feito! Obrigada.
