### ISSUE TITLE
Documentação da wiki de "[5] Caso de Uso: Configurações de passos e processamento dinâmico"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#619]
# Comportamento Esperado
Nesse ponto, deve se documentar os procedimentos de configurar uma coleta com processamento dinâmico. Deve incluir o passo a passo para essa configuração e todos esses pontos devem acompanhar explicações e screenshots. Além disso, deve incluir uma documentação completa de cada um dos passos e da interface de passos, com explicações de como eles funcionam, suas entradas e saídas e possíveis situações em que devem ser usados.

# Comportamento Atual
Está página está em branco por isso não existe documentação desse mecanismo

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by caiocvsilva** [comment]
O texto está ótimo! Fiz algumas pequenas correções. Você pensa ser valido explicar que o "Salvar Página" 'redireciona' para o coletor estático? Não sei se ficou bem claro, pode dar a entender que ele salva a página de forma independente de como é feito no estático.

**Comment by rennancordeiro** [comment]
> O texto está ótimo! Fiz algumas pequenas correções. Você pensa ser valido explicar que o "Salvar Página" 'redireciona' para o coletor estático? Não sei se ficou bem claro, pode dar a entender que ele salva a página de forma independente de como é feito no estático.

Obrigado. Adicionei mais explicações sobre o "Salvar Página", incluindo esse detalhe!

**Comment by matheusfebarbosa** [comment]
O texto está muito bom mesmo. Uma única sugestão, seria linkar alguma fonte tipo [essa](https://www.w3schools.com/xml/xpath_syntax.asp), pra ter de referência de como Xpath funciona. Seria bom principalmente na parte do wildcard (*), que eu acho que pode ser mais confusa de entender.

**Comment by rennancordeiro** [comment]
Olá @matheusfebarbosa e @caiocvsilva, fiz as correções pedidas e segui as sugestões, podem dar uma olhada novamente, por favor?

**Comment by caiocvsilva** [comment]
Por mim está ótimo!

**Comment by matheusfebarbosa** [comment]
Dei uma passada de novo, e parece tudo ok!
