### ISSUE TITLE
Documentação da wiki de "[6] Caso de Uso: Explorando Links com Opções Avançadas"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#620]
# Comportamento Esperado
Essa página inclui um coletor que utiliza as ferramentas de exploração avançada de links. Para essa documentação, deve ser feita uma validação da coleta que está documentada, para verificar se ainda está funcionando corretamente e se a página alvo ainda está como esperada.

Além disso, a documentação pode ser mais completa, com a inclusão de uma melhor explicação da ferramenta e de um passo a passo mais detalhado da configuração da coleta, ou seja, o que completar em cada parte, quais devem ser os passos a serem seguidos para reproduzí-la.

# Comportamento Atual
Está página está com a documentação já bem avançada, mas que pode ser revisitada e possíveis atualizações devem ser feitas

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/620?planning-poker) with ZenHub @brenomatos @aluiza22 @matheusfebarbosa

**Comment by louisaturn** [comment]
Desculpa, não devia ter fechado, não sei se foi aprovado haha
