### ISSUE TITLE
Documentação da wiki de "[7] Caso de Uso: Detecção de formulários e injeção de parâmetros"

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#621]
# Comportamento Esperado
Nesse ponto, deve se documentar os procedimentos de configurar uma coleta com formulários. Deve incluir o passo a passo para essa configuração e todos esses pontos devem acompanhar explicações e screenshots. Além disso, deve incluir uma documentação completa de cada dos elementos da interface, com explicações de como eles funcionam. Além disso, deve ter explicações de cada um dos injetores, seus valores possíveis e situações em que devem ser usados.

# Comportamento Atual
Está página está em branco por isso não existe documentação desse mecanismo

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by lucasaug** [comment]
Olá @louisaturn e @rennancordeiro, vocês podem revisar o meu texto por favor? Podem colocar quaisquer sugestões aqui e me marcar, que em seguida eu respondo e altero o que for necessário.

**Comment by rennancordeiro** [comment]
Para mim parece tudo certo, ficou muito bom! @lucasaug

**Comment by louisaturn** [comment]
Olá, Lucas! Peguei no seu pé, hehe, mas acho que as alterações ficaram ótimas! Estou fechando a issue.
