### ISSUE TITLE
BUG - Páginas dinâmicas sendo salvas antes do carregamento.

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/C01#626]
### Comportamento Esperado

Espera-se que as páginas dinâmicas sejam salvas apenas após o carregamento total do seu conteúdo.

### Comportamento Atual

Foi identificado a presença de  páginas dinâmicas sem o conteúdo carregado, isto é, que está sendo salva antes da renderização completa.

### Localização

- /datalake/ufmg/crawler/webcrawlerc01/concursos_governador_valadares/data/raw_pages/0a953c7b7af7cd393b99671879929e7b.html

- /datalake/ufmg/crawler/webcrawlerc01/concursos_governador_valadares/data/raw_pages/0e4ddfd191a8b71e8f061b51472bd726.html

- /datalake/ufmg/crawler/webcrawlerc01/concursos_governador_valadares/data/raw_pages/4aaa937e8aa28a6299c4fe208a9ca52d.html

### Detalhes da fonte

Não se aplica

### Detalhes da trilha

Trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

### Screenshots e links (caso necessário)

Não se aplica.

**Comment by rennancordeiro** [comment]
Olá @CinthiaS, obrigado pela abertura da issue! Contudo, observei que ela não está seguindo o formato definido nesse template: https://github.com/MPMG-DCC-UFMG/C01/wiki/Template-de-Issue-(outros-trilhas). Você poderia editar para adaptar isso, por favor?

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/626?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by rennancordeiro** [comment]
Tarefa foi resolvida com a PR [#869](https://github.com/MPMG-DCC-UFMG/C01/pull/869)
