### ISSUE TITLE
Coleta de dados da TAG licitações do portal de transparência de Ipatinga.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#630]
## Comportamento Esperado
Requisição da extração do arquivo contendo tabelas referentes às licitações da cidade de Ipatinga. A extração tem o objetivo de obter informações como número e objeto, edital, data e secretaria. 

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Ipatinga).

## Detalhes da fonte
https://transparencia.ipatinga.mg.gov.br/licitacoes
São de nosso interesse todas as licitações de disponibilizadas no arquivo.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram o download das licitações.
![passo1](https://user-images.githubusercontent.com/72928223/126337811-bcedf27b-fd89-4f03-af6a-1c78dbb94ae2.png)

**Comment by caiocvsilva** [comment]
Os dados requisitados desta coleta se encontram em /datalake/ufmg/webcrawlerc01/licitacoes_ipatinga/data/files/.
Caso haja algum problema com a coleta, por favor entre em contato.
