### ISSUE TITLE
Coleta de dados geral do portal de transparência de Uberaba.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#636]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Uberaba. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Uberaba.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Uberaba).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Uberaba, nos seguintes links:
•http://www.uberaba.mg.gov.br/portal/principal
•http://www.uberaba.mg.gov.br/portal/conteudo,37644

E todos os html das primeiras páginas alcançáveis a partir de:
•http://www.uberaba.mg.gov.br/portal/conteudo,37644

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by aluiza22** [comment]
Olá, @carbo6ufmg! A coleta dessa fonte foi realizada e os dados encontram-se em /datalake/ufmg/webcrawlerc01/Uberaba/, separados em /prefeitura e /transparencia.
Caso haja algum problema com a coleta, favor informar por meio desta issue.
