### ISSUE TITLE
Coleta de dados das Leis Orçamentárias e Leis de Responsabilidade Fiscal de Varginha. 

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#639]
## Comportamento Esperado
Requisição da extração da página e dos arquivos referentes às Leis Orçamentárias e Relatórios Fiscais de Varginha. A extração tem o objetivo de obter dados como PPA - Plano Plurianual, LDO - Lei de Diretrizes Orçamentárias e LOA - Lei Orçamentária Anual, Relatório de Gestão Fiscal e Relatório Resumido de Execução Orçamentária.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Varginha).

## Detalhes da fonte
http://portal.contaspublicas.topdata-info.com.br/prefeituras/index.php?municipios=varginha&ano=2021&titulo=Lei%20Federal%209755/98

É de nosso interesse o html da página e os arquivos que tenham sua url na página acima. 

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram as informações de interesse da página:
![passo1](https://user-images.githubusercontent.com/72928223/126495919-059d4a0d-58df-4ba9-8080-0609d5d8fd51.png)

**Comment by aluiza22** [comment]
Olá, @carbo6ufmg ! Os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/Varginha/leis_orca_resp. Caso haja algum problema com a coleta, informe por meio desta issue.
