### ISSUE TITLE
Coleta de dados de RGF e RREO da prefeitura de Congonhas.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#652]
## Comportamento Esperado
Requisição da extração da página e dos arquivos referentes aos Relatórios Fiscais de Congonhas. A extração tem o objetivo de obter dados como Relatório de Gestão Fiscal e Relatório Resumido de Execução Orçamentária.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Congonhas).

## Detalhes da fonte
https://e-gov.betha.com.br/transparencia/01037-113/con_contaspublicas.faces?mun=LNi8NILt9yXKIwLr4Jtjywcr_yQdDTy1

É de nosso interesse o html da página e os arquivos que tenham sua url na página acima. 

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram as informações de interesse da página:
![passo1](https://user-images.githubusercontent.com/72928223/126776930-5d622396-3ea4-4dfc-8ca3-c45f108a33dd.png)
![passo2](https://user-images.githubusercontent.com/72928223/126776936-8145679e-4ebf-486e-aaea-54fe73b059ea.png)
![passo3](https://user-images.githubusercontent.com/72928223/126776944-2354c0e7-6904-458b-a538-b411e241d973.png)

**Comment by caiocvsilva** [comment]
Segundo @CinthiaS, essa coleta não é mais necessária. Por este motivo, será fechada.
