### ISSUE TITLE
Filtrar tipos de arquivos em coletas de páginas dinâmicas.

### ISSUE THREAD

**Issue by elvesmrodrigues** [MPMG-DCC-UFMG/C01#654]
## Comportamento esperado

Desejamos realizar coletas de apenas arquivos que atendem os formatos especificados na configuração do coletor, igual para o caso de coletas estáticas.

## Comportamento atual

O recurso não é suportado em coletas de arquivos dinâmicos.

## Passos para reproduzir o erro

- Crie um coletor dinâmico que deve restringir o tipo dos arquivos baixados e o execute.
- Note que arquivos de qualquer tipo são baixados pelo coletor, ignorando complemente o filtro de tipos de arquivos de sua configuração.

## Sistema

Todos.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/654?planning-poker) with ZenHub @louisaturn @matheusfebarbosa

**Comment by rennancordeiro** [comment]
Olá @louisaturn e @matheusfebarbosa, acredito que essa issue tenha 3 pontos, pois, o código de filtro já existe,  oque precisariamos fazer é adaptá-lo para o código de processamento dinâmico. O desafio seria detectar o tipo de arquivo, mas isso já é feito atualmente.

**Comment by louisaturn** [comment]
Esta issue está sendo fechada porque a issue https://github.com/MPMG-DCC-UFMG/C01/issues/4794 já cobre o que está sendo especificado (sobre filtragem de arquivos em coletas dinâmicas)
