### ISSUE TITLE
Download centralizado de arquivos em páginas dinâmicas

### ISSUE THREAD

**Issue by elvesrodrigues** [MPMG-DCC-UFMG/C01#661]
## Comportamento esperado

Por o sistema ser distribuído, é necessário adaptar a versão standalone de download de arquivos em páginas dinâmicas considerando que spiders estarão em máquinas diferentes e que o webdriver é o responsável por baixar esses arquivos.

## Comportamento atual

Ao executar instâncias do módulo `spider_manager` de maneira distribuída, cada um deles armazenará no sistema de arquivos local os dados que ele coletou.

## Passos para reproduzir

- Faça o clone da branch `distributed-system`
- Instancie cada um de seus módulos independentemente. 
- Instancie o módulo `spider_manager` (com as devidas configurações) em máquinas diferentes.
- Execute uma coleta distribuída que possua arquivos a serem baixados e note que cada instância do módulo `spider_manager` executando irá salvar no sistema local de arquivos os dados baixados por eles, fragmentando a coleta geral.

## Sistema

Branch `distributed-system`.

**Comment by elvesrodrigues** [comment]
Acho uma boa ideia...

**Comment by rennancordeiro** [comment]
@lucasaug e @elvesrodrigues, após a discussão, concordo com vocês. Alterei minha pontuação para 5 e coloquei a estimativa como 5, como determinado no nosso protocolo.

**Comment by elvesrodrigues** [comment]
@lucasaug e @rennancordeiro  Eu acredito que essa issue está resolvida pela PR da issue #789, não acham? Inclusive, o merge já foi até feito. 

Uma vez que todos containers têm acesso a uma pasta comum, eles então escreverão no mesmo local, mesmo sendo instância de uma mesmo módulo (`spider_manager`, no caso).

Talvez possamos arquivar essa issue por hora...

**Comment by elvesrodrigues** [comment]
Ou, pelo menos, não acho que seja o caso dessa issue ser prioritária para a Epic que elá está atribuída (#790).

**Comment by lucasaug** [comment]
@elvesrodrigues Fiquei na dúvida mas também pensei se fechamos essa issue. A princípio pensei em deixá-la só como uma tarefa de validação, pra confirmar com certeza que esse ponto específico está funcionando. Assim que alguém fizesse essa validação, acho que poderia fechar. Mas se acharem que não vale a pena por ser algo bem simples (a princípio), podemos fechar de uma vez também.

**Comment by elvesrodrigues** [comment]
Por mim podemos deixar sim...

**Comment by lucasaug** [comment]
Fiz alguns testes na branch `distributed-system` e não tive problemas ao executar o download de arquivos em coletas dinâmicas. Encontrei um erro em uma página que testei, mas parece não ser relacionado com essa questão em si. Estou discutindo com o @elvesrodrigues e provavelmente criaremos uma issue separada para tratar esse ponto.
