### ISSUE TITLE
Coleta de dados das licitações do portal de transparência de Uberaba

### ISSUE THREAD

**Issue by marianaossilva** [MPMG-DCC-UFMG/C01#667]
## Comportamento esperado

Requisição da extração dos arquivos referentes às licitações da cidade de Uberaba. 

## Comportamento Atual

Não se aplica.

## Localização

Não possui nenhuma coleta atualmente. 

Para fins de organização separar dados a nível de município (e.g. /datalake/ufmg/crawler/webcrawlerc01/Uberaba).

## Detalhes da fonte

[http://www.uberaba.mg.gov.br/portal/conteudo,29557](http://www.uberaba.mg.gov.br/portal/conteudo,29557)

São de nosso interesse todos os arquivos das licitações de todas as modalidades e anos. 

Para isso é necessário acessar a página *Licitações, Contratos e Convênios > Licitações online*

Em seguida, selecionar "Todas as modalidades" e fazer a coleta dos arquivos por ano.

## Detalhes da trilha

Os dados aqui solicitados são de interesse da trilha M03, sob coordenação de Iago Domingues ([iagoadvaz@gmail.com](mailto:iagoadvaz@gmail.com)).

## Screenshots e Links

> 1️⃣ Primeiro, selecionar `Licitações, Contratos e Convênios`  
![primeiro_passo](https://user-images.githubusercontent.com/14806188/127198016-d270f9ab-06fe-4ced-9b18-6becb20b2834.jpg)

> 2️⃣ Em seguida, selecionar `Licitações e Contratos`
![segundo_passo](https://user-images.githubusercontent.com/14806188/127198047-586029ca-8b51-42c7-bc77-43923c09f604.jpg)

> 3️⃣ Selecionar `Todas as modalidades` por ano.
>
> 4️⃣ Coletar todos os arquivos de cada ano.
![terceiro_passo](https://user-images.githubusercontent.com/14806188/127198247-9fe55f53-bdb2-4723-b6d0-8338aa998682.jpg)

**Comment by aluiza22** [comment]
Olá, @marianaossilva ! Os dados desta coleta já se encontram disponíveis em /datalake/ufmg/webcrawlerc01/Uberaba/licitacoes_m03. Caso haja algum problema pode re-abrir e informar por essa issue mesmo.
