### ISSUE TITLE
Opção de duplicar blocos na configuração de passos

### ISSUE THREAD

**Issue by aluiza22** [MPMG-DCC-UFMG/C01#671]
## Comportamento Esperado
Uma funcionalidade interessante seria a possibilidade duplicar um bloco e seus filhos dos passos dinâmicos. Em algumas situações, como na #624 , é preciso repetir ações em páginas diferentes e hoje temos que recriar todos os blocos em loops separados.

## Comportamento Atual
Hoje é possível apenas reordenar, identar e remover um bloco de passo dinãmico.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/671?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn
