### ISSUE TITLE
Coleta de dados das licitações do portal de transparência de Itabirito

### ISSUE THREAD

**Issue by amandafagundes** [MPMG-DCC-UFMG/C01#673]
## Comportamento Esperado

Requisição da extração de arquivos contendo dados referentes às licitações da cidade de Itabirito. 

## Comportamento Atual

Não se aplica.

## Localização

Não possui nenhuma coleta atualmente.

Para fins de organização separar dados a nível de município

(e.g. /datalake/ufmg/crawler/webcrawlerc01/Itabirito).

## Detalhes da fonte

[https://www.itabirito.mg.gov.br](https://www.itabirito.mg.gov.br)

São de nosso interesse todos os arquivos das licitações de todas as modalidades e anos.

Para isso é necessário acessar a página *Licitações*, onde é possível filtrar os resultados.

Para a extração, selecionar as seguintes opções:

- Ano: necessário selecionar todos os anos disponíveis

## Detalhes da trilha

Os dados aqui solicitados são de interesse da trilha M03, sob coordenação de Iago Domingues (iagoadvaz@gmail.com).

## Screenshots e Links

Os screenshots a seguir mostram como acessar as informações de interesse da página:

1. Primeiro, é necessário selecionar a opção "Licitações" na página inicial.

![Captura de Tela 2021-07-27 às 22 50 06](https://user-images.githubusercontent.com/38862621/127251034-8b34f721-c104-44fa-88bd-3a5fdb2cac23.png)

2. Em seguida, realizar a busca para cada ano disponível

![Captura de Tela 2021-07-27 às 22 48 01](https://user-images.githubusercontent.com/38862621/127251067-7815848d-1bbd-413e-b227-b2676b1be727.png)

3. Para cada resultado, clicar na opção de download ao lado dos documentos listados.

![Captura de Tela 2021-07-27 às 22 51 46](https://user-images.githubusercontent.com/38862621/127251125-72814fec-6aab-4067-9546-09c64cb5137e.png)

**Comment by louisaturn** [comment]
Coleta disponível em `/datalake/ufmg/webcrawlerc01/licitacoes_itabirito`.

**Comment by louisaturn** [comment]
Coleta disponível em `/datalake/ufmg/webcrawlerc01/itabirito`.
