### ISSUE TITLE
 Documentação da wiki de "[8] Caso de Uso: Injeção em URLs Parametrizadas"

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#678]
# Comportamento Esperado
Nesse ponto, deve se documentar os procedimentos de configurar uma coleta com URLs parametrizadas. Deve incluir o passo a passo para essa configuração e todos esses pontos devem acompanhar explicações e screenshots. Além disso, deve incluir uma documentação completa de cada dos elementos da interface, com explicações de como eles funcionam. Deve referenciar a seção de tipos de injetores e validadores.

# Comportamento Atual
Está página está em branco, por isso não existe documentação desse mecanismo

# Passos para reproduzir o erro
Não se aplica

# Especificações da Coleta
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by lucasaug** [comment]
Olá @aluiza22 e @matheusfebarbosa, vocês podem revisar o meu texto por favor? Podem colocar quaisquer sugestões aqui e me marcar, que em seguida eu respondo e altero o que for necessário.

**Comment by aluiza22** [comment]
Oi, @lucasaug ! Pra mim parece que está tudo certinho, só os links pra outras seções da wiki que parecem estar quebrados pra mim. E tenho uma sugestão, a ultima frase, com o arquivo de configuração (que o link funciona), me pareceu meio perdida. Acho que ainda não temos a funcionalidade de importar na interface ou um tutorial sobre importar configurações, talvez seria bom dar mais uma explicada de como aquilo poderia ser utilizado, ou então, comentar essa frase por enquanto, não sei.

**Comment by lucasaug** [comment]
@aluiza22 Obrigado pelas observações! Olhei aqui e consertei os links para outras seções da Wiki. E sobre a parte de importação, também adicionei um texto dando um pouco mais de contexto, você acha que dessa forma ficou melhor? Acho que incluir o arquivo de configuração seria legal pra facilitar pro usuário.

**Comment by matheusfebarbosa** [comment]
Olá @lucasaug! Dei uma olhada também, e parece ótimo. Bem clara e concisa a explicação. Porém percebi que ainda tem alguns links quebrados na página - Exemplo: um link da wiki aponta para este [link](https://github.com/MPMG-DCC-UFMG/C01/%5B7%5D-Caso-de-Uso:-Detec%C3%A7%C3%A3o-de-formul%C3%A1rios-e-inje%C3%A7%C3%A3o-de-par%C3%A2metros#tipos-de-injetores), ao inves [desse](https://github.com/MPMG-DCC-UFMG/C01/wiki/[7]-Caso-de-Uso:-Detec%C3%A7%C3%A3o-de-formul%C3%A1rios-e-inje%C3%A7%C3%A3o-de-par%C3%A2metros#tipos-de-injetores).

Sobre a questão do arquivo de configuração, eu acho que seria legal manter, mesmo que a função de importar ainda não esteja pronta. Acho que facilita um pouco ter acesso a ele, e quando a função estiver pronta já estará ali pra quem quiser usar.

**Comment by lucasaug** [comment]
@matheusfebarbosa Resolvi novamente a coisa do link. O problema é que eu estava tentando usar links relativos pra ficar mais flexível, mas eles são bem imprevisíveis então acho que não tá valendo a pena. Mudei pra links absolutos e acho que agora está funcionando.

Sobre a questão da importação, na verdade acho que não entendi muito bem. A importação não está na interface? Porque esse código já está incluído na master, então eu já estava considerando integrado. Todas as branches que estou mexendo aqui também tem essa funcionalidade.

**Comment by aluiza22** [comment]
Agora tá tudo certinho pra mim também! E concordo em ser melhor já deixar o arquivo de config lá.

**Comment by lucasaug** [comment]
Beleza, obrigado pelo feedback! Nesse caso vou fechar a issue.
