### ISSUE TITLE
Especificação de coleta geral do portal de transparência de Ipatinga.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#681]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Ipatinga. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Ipatinga.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Ipatinga).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Ipatinga, nos seguintes links:
•https://www.ipatinga.mg.gov.br/
•https://transparencia.ipatinga.mg.gov.br/

E todos os html das primeiras páginas alcançáveis a partir de:
•https://transparencia.ipatinga.mg.gov.br/

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by aluiza22** [comment]
Olá, @carbo6ufmg! A coleta dessa fonte foi realizada e os dados encontram-se em /datalake/ufmg/webcrawlerc01/Ipatinga/, separados em /prefeitura e /transparencia.
Caso haja algum problema com a coleta, favor informar por meio desta issue.

**Comment by carbo6ufmg** [comment]
Coleta apresenta bug descrito na issue #627.
/Ipatinga/transparencia/data/raw_pages/0d366bec88b7ec73737b459fbdb978c8.html
