### ISSUE TITLE
Especificação de coleta geral do portal de transparência de Pouso Alegre.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#682]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Pouso Alegre. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Pouso Alegre.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Pouso Alegre).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Pouso Alegre, nos seguintes links:
•https://www.pousoalegre.mg.gov.br/
•https://pousoalegre.atende.net/?pg=transparencia#!/

E todos os html das primeiras páginas alcançáveis a partir de:
•https://pousoalegre.atende.net/?pg=transparencia#!/

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by caiocvsilva** [comment]
A coleta desa fonte foi realizada. Os dados encontram-se em /datalake/ufmg/webcrawlerc01/Pouso_Alegre/, separados em prefeitura e transparencia. Caso haja algum problema com a coleta, favor informar por meio da issue.

**Comment by carbo6ufmg** [comment]
Coleta apresenta bug descrito na issue #627.
/Pouso_Alegre/transparencia/data/raw_pages/0b99b30ed5eed6f9cc137aed4d6fbf1d.html
