### ISSUE TITLE
Especificação de coleta geral do portal de transparência de Teófilo Otoni.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#683]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Teófilo Otoni. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Teófilo Otoni.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Teófilo Otoni).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Teófilo Otoni, nos seguintes links:
•https://teofilootoni.mg.gov.br/
•https://transparencia.teofilootoni.mg.gov.br/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2

E todos os html das primeiras páginas alcançáveis a partir de:
•https://transparencia.teofilootoni.mg.gov.br/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by caiocvsilva** [comment]
A coleta dessa fonte foi realizada. Os dados encontram-se em /datalake/ufmg/webcrawlerc01/Teofilo_Otoni/, separados em prefeitura e transparencia. Caso haja algum problema com a coleta, favor informar por meio da issue.
