### ISSUE TITLE
Especificação de coleta geral do portal de transparência de Varginha.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#685]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Varginha. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Varginha.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Varginha).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Varginha, nos seguintes links:
•https://www.varginha.mg.gov.br/
•https://leideacesso.etransparencia.com.br/varginha.prefeitura.mg/TDAPortalClient.aspx?416

E todos os html das primeiras páginas alcançáveis a partir de:
•https://leideacesso.etransparencia.com.br/varginha.prefeitura.mg/TDAPortalClient.aspx?416

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by aluiza22** [comment]
Olá, @carbo6ufmg ! A coleta da página da prefeitura já foi feita e pode ser encontrada em /datalake/ufmg/webcrawlerc01/Varginha/prefeitura/, caso haja algum problema com a coleta, favor informar por meio da issue.

A coleta do portal de transparência tem uma complexidade maior e ainda não conseguimos resolvê-la.
On hold pela issue #722

**Comment by aluiza22** [comment]
Olá, @carbo6ufmg ! Os arquivos solicitados já se encontram em /datalake/ufmg/webcrawlerc01/Varginha/portal. 
Caso haja algum problema com a coleta, favor informar por meio desta issue.
