### ISSUE TITLE
Especificação de coleta geral do portal de transparência de Congonhas.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#687]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Congonhas. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Congonhas.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Congonhas).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Congonhas, nos seguintes links:
•https://www.congonhas.mg.gov.br/
•https://www.congonhas.mg.gov.br/index.php/portal-transparencia-prefeitura/

E todos os html das primeiras páginas alcançáveis a partir de:
•https://www.congonhas.mg.gov.br/index.php/portal-transparencia-prefeitura/

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by caiocvsilva** [comment]
A coleta desa fonte foi realizada. Os dados encontram-se em /datalake/ufmg/webcrawlerc01/Congonhas/, separados em prefeitura e transparencia. Caso haja algum problema com a coleta, favor informar por meio da issue.

**Comment by carbo6ufmg** [comment]
Coleta apresenta bug descrito na issue #627.
/Congonhas/transparencia/data/raw_pages/b5b3c5852f8255976575d946d344cb82.html
