### ISSUE TITLE
Adicionar caixa de pesquisa de coletores na página inicial

### ISSUE THREAD

**Issue by elvesrodrigues** [MPMG-DCC-UFMG/C01#690]
# Comportamento esperado 

Quando há muitos coletores, fica difícil localizar aquele de interesse na página inicial. Adicionar funcionalidade de pesquisa por nome do coletor ou identificador, poderia ajudar nisso. 

# Comportamento atual

Não existe essa funcionalidade.

# Passos para reproduzir o erro

Não se aplica.

# Especificações da coleta

Não se aplica.

# Sistema (caso necessário)

Não se aplica.

# Screenshots (caso necessário)

Não aplica.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/690?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn

**Comment by caiocvsilva** [comment]
Como a issue #3053  já incluiu uma filtragem na tela inicial, acredito não ser mais necessária a busca por coletores. Caso haja a necessidade, esta issue poderá ser reaberta.
