### ISSUE TITLE
Logs da extração de links de arquivos

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#707]
## Comportamento Esperado
Ao executar uma coleta que extraia links de arquivos, é esperado que uma mensagem seja exibida no log toda vez que esses links forem encontrados, informando quantos foram encontrados em cada página.

## Comportamento Atual
O sistema não exibe a quantidade de arquivos extraídos em cada página. Para que a coleta extraia links de arquivos, é necessário especificar a regex de links de arquivos tanto na seção de extração de links quanto na de extração de arquivos. Não sei se isso tem alguma ligação com a causa do problema atual, mas vale investigar.

## Passos para reproduzir o erro

  1. Usar a funcionalidade de importação de configuração para importar a coleta cujo arquivo está anexado.
  2. Executar a coleta
  3. Abrir o log de saída do coletor e observar que, para todas as páginas, a mensagem "+0 small files detected..." é exibida.

## Especificações da Coleta

  - Usar o arquivo de configuração fornecido: [muriae.txt](https://github.com/MPMG-DCC-UFMG/C01/files/6971569/muriae.txt)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/707?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by elvesrodrigues** [comment]
@caiocvsilva e @matheusfebarbosa eu dei **8 pontos** nessa issue erroneamente. Também acredito que ela seja simples. Então irei alterar a pontuação por mim dada para 3, fazendo que, pela regra que definimos para o planning poker, a issue tenha 3 pontos.

**Comment by lucasaug** [comment]
@caiocvsilva Tentei executar essa coleta no sistema distribuído (atualizando a configuração de coleta) mas ela termina precocemente, e nem chega a coletar os arquivos, portanto não pude olhar a fundo o problema em si. Ainda sim, o que você descreveu é **precisamente** o problema em questão. Os arquivos eram baixados mas o log fica incorreto, sempre informando que 0 arquivos foram detectados.

**Comment by caiocvsilva** [comment]
Aparentemente essa issue já se encontra resolvida, provavelmente devido a outras atualizações do backend. O log anexo apresenta a informação de que 17 arquivos foram baixados, sendo o valor correto. Caso necessário, incluí também o json que resultou no log coletado.

![log](https://user-images.githubusercontent.com/8015073/215227470-6a82dcd8-4efd-4415-8fed-7769f3997f77.png)


[LogResultante.txt](https://github.com/MPMG-DCC-UFMG/C01/files/10523919/1674863026747.txt)
[jsonConfiguracaoLogArquivo.txt](https://github.com/MPMG-DCC-UFMG/C01/files/10523921/logArquivo.txt)
