### ISSUE TITLE
Aprimorar detecção de arquivos e extensões

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#7089]
## Comportamento Esperado
Ao configurar uma coleta que faz download de arquivos é esperado que os arquivos corretos sejam encontrados e filtrados, independentemente do formato das URLs que apontam para esses arquivos. A filtragem deve ser feita por algum mecanismo robusto, por exemplo:

- Enviar uma requisição HEAD para a URL e analisar o `Content Type` ou `Content Disposition` retornados
- Enviar uma requisição GET para a URL e analisar o início da resposta para determinar o tipo de dado

Outros métodos podem existir, uma investigação é necessária. O método escolhido deve ser utilizado tanto na primeira filtragem para definir as URLs elegíveis para extração de arquivos, quanto na filtragem de extensões configuradas pelo usuário.

## Comportamento Atual
O sistema atual filtra para que URLs que tenham extensão `.html` ou `.php` não sejam consideradas na busca por arquivos. Quaisquer outras URLs são mantidas para as próximas etapas da filtragem. A seguir, o sistema verifica se as URLs possuem extensões permitidas pela configuração inserida pelo usuário. Essa etapa, porém, remove automaticamente todas as URLs que não tem uma extensão no final (o que é comum em páginas que carregam o arquivo dinamicamente), o que acaba forçando o usuário a deixar o campo vazio, possivelmente baixando tipos de arquivo não desejados.

## Passos para reproduzir o erro

  1. Importar a coleta abaixo
  2. Executar a coleta e verificar que nenhum arquivo é baixado
  3. Alterar o campo de "Extensões de arquivo permitidas" para que ele fique vazio
  4. Re-executar a coleta e verificar que agora os arquivos são baixados

## Especificações da Coleta

```
{
    "source_name": "Itabirito",
    "base_url": "http:\/\/api.conectbr.com.br\/Licitacao\/Busca\/?token=XEOk3i50lCa5IcpiNG7vXQ==",
    "obey_robots": false,
    "crawler_description": "Teste",
    "crawler_type_desc": "Contratos",
    "crawler_issue": 0,
    "data_path": "itabirito",
    "sc_scheduler_persist": true,
    "sc_scheduler_queue_refresh": 10,
    "sc_queue_hits": 10,
    "sc_queue_window": 60,
    "sc_queue_moderated": true,
    "sc_dupefilter_timeout": 600,
    "sc_global_page_per_domain_limit": null,
    "sc_global_page_per_domain_limit_timeout": 600,
    "sc_domain_max_page_timeout": 600,
    "sc_scheduler_ip_refresh": 60,
    "sc_scheduler_backlog_blacklist": true,
    "sc_scheduler_type_enabled": true,
    "sc_scheduler_ip_enabled": true,
    "sc_scheduler_item_retries": 3,
    "sc_scheduler_queue_timeout": 3600,
    "sc_httperror_allow_all": true,
    "sc_retry_times": 3,
    "sc_download_timeout": 10,
    "antiblock_download_delay": 2,
    "antiblock_autothrottle_enabled": false,
    "antiblock_autothrottle_start_delay": 2,
    "antiblock_autothrottle_max_delay": 10,
    "antiblock_ip_rotation_enabled": false,
    "antiblock_ip_rotation_type": "tor",
    "antiblock_max_reqs_per_ip": 10,
    "antiblock_max_reuse_rounds": 10,
    "antiblock_proxy_list": "",
    "antiblock_user_agent_rotation_enabled": false,
    "antiblock_reqs_per_user_agent": 100,
    "antiblock_user_agents_list": "",
    "antiblock_insert_cookies_enabled": false,
    "antiblock_cookies_list": "",
    "captcha": "none",
    "has_webdriver": false,
    "webdriver_path": "",
    "img_xpath": "",
    "sound_xpath": "",
    "dynamic_processing": true,
    "browser_type": "chromium",
    "skip_iter_errors": false,
    "browser_resolution_width": 1280,
    "browser_resolution_height": 720,
    "explore_links": false,
    "link_extractor_max_depth": null,
    "link_extractor_allow_url": "",
    "link_extractor_allow_domains": "",
    "link_extractor_tags": "",
    "link_extractor_attrs": "",
    "link_extractor_check_type": false,
    "link_extractor_process_value": "",
    "download_files": true,
    "download_files_allow_url": "^(http:\\\/\\\/api.conectbr.com.br\\\/Licitacao\\\/AbreArquivo\\\/.*)",
    "download_files_allow_extensions": "pdf,doc",
    "download_files_allow_domains": "",
    "download_files_tags": "",
    "download_files_attrs": "",
    "download_files_process_value": "",
    "download_files_check_large_content": true,
    "download_imgs": false,
    "steps": "{\"step\":\"root\",\"depth\":0,\"children\":[{\"step\":\"espere\",\"depth\":1,\"arguments\":{\"segundos\":\"3\"}},{\"step\":\"clique\",\"depth\":1,\"arguments\":{\"elemento\":\"'\/\/*[@id=\\\"formDados\\\"]\/fieldset\/div\/div[7]\/input'\"}},{\"step\":\"espere\",\"depth\":1,\"arguments\":{\"segundos\":\"3\"}},{\"step\":\"screenshot\",\"depth\":1,\"arguments\":{}},{\"step\":\"salva_pagina\",\"depth\":1,\"arguments\":{}}]}",
    "encoding_detection_method": 1,
    "expected_runtime_category": "medium",
    "templated_url_parameter_handlers": [],
    "templated_url_response_handlers": [],
    "instance_id": "166569197657643",
    "crawler_id": 4
}
```

**Comment by caiocvsilva** [comment]
As soluções sugeridas nesta issue já se encontram implementa das ou então foram testadas, porém o problema continua ocorrendo, necessitando assim de uma analise mais profunda e custosa. Tendo em vista que, a princípio, esta issue afeta apenas um site, e não está impedindo outras coletas, a mesma será fechada, para que outras com uma maior prioridade seja, realizadas. Caso haja alguma novidade em relação a coletas ou soluções que tenham relação com essa issue, a mesma poderá ser reaberta.
