### ISSUE TITLE
Nova coleta de dados da TAG licitações do portal de transparência de Ipatinga.

### ISSUE THREAD

**Issue by carbo6ufmg** [MPMG-DCC-UFMG/C01#715]
## Comportamento Esperado
Requisição da extração do html da página e arquivo e o contendo tabelas referentes às licitações da cidade de Ipatinga. A extração tem o objetivo de obter informações como número e objeto, edital, data e secretaria. 

## Comportamento Atual
Os dados atuais são referentes a todas licitações "em andamento".

## Localização
Atualmente os dados estão localizados em:
 /datalake/ufmg/webcrawlerc01/licitacoes_ipatinga/data/files/
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/crawler/webcrawlerc01/Ipatinga).

## Detalhes da fonte
https://transparencia.ipatinga.mg.gov.br/licitacoes
São de nosso interesse o html da página e todas as licitações disponibilizadas no arquivo, depois de filtrar o status para "Todos".

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Os screenshots a seguir mostram o download das licitações.
![passo1](https://user-images.githubusercontent.com/72928223/130096049-8f2d1ca7-6021-40ef-b141-df8b957e3655.png)
![passo2](https://user-images.githubusercontent.com/72928223/130096055-bf2e681c-1958-4e97-a8f9-e4a64882dc5d.png)

**Comment by aluiza22** [comment]
Olá, @carbo6ufmg! A coleta dessa fonte foi realizada e os dados encontram-se em /datalake/ufmg/webcrawlerc01/Ipatinga/licitacoes_ipatinga.
Caso haja algum problema com a coleta, favor informar por meio desta issue.
