### ISSUE TITLE
Adicionar mecanismos de debug ao coletor dinâmico

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#718]
## Comportamento Esperado
O sistema deve possuir ferramentas adequadas para acompanhar e debugar o funcionamento do coletor dinâmico durante sua execução. É desejável a inclusão de um passo de "screenshot", e também deve ser permitida a execução do Pyppeteer no modo headful.

## Comportamento Atual
Os mecanismos descritos estão ausentes do sistema.

## Passos para reproduzir o erro
Não aplicável.

## Especificações da Coleta
Não aplicável.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/718?planning-poker) with ZenHub @louisaturn @matheusfebarbosa

**Comment by lucasaug** [comment]
O passo de screenshot já foi adicionado, e a execução em modo headful não está sendo investigada no momento, portanto outra issue será aberta para esse ponto.

**Comment by lucasaug** [comment]
A issue #886 foi criada para tratar o modo headful.
