### ISSUE TITLE
Erro  500 - Internor server error

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#723]
## Comportamento Esperado
Salvar a página como um html sem erros, pois não existe nenhum erro ao abrir a página no navegador.

## Comportamento Atual
Ao tentar coletar uma página de Juiz de Fora, o coletor falha devido a um erro 500 do servidor:
```
[scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://www.pjf.mg.gov.br/secretarias/cpl/editais/pregao_eletronico/2020/index.php> (failed 3 times): 500 Internal Server Error
```

## Passos para reproduzir o erro

  1. Coletor estático da página 'https://www.pjf.mg.gov.br/secretarias/cpl/editais/pregao_eletronico/2020/index.php'
  2. Nenhum passo dinâmico ou configurarão avançada é necessária

## Especificações da Coleta

  - Fonte: https://www.pjf.mg.gov.br/secretarias/cpl/editais/pregao_eletronico/2020/index.php

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/723?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by caiocvsilva** [comment]
Esta issue foi resolvida ao implementar na interface o controle de user-agent. Por este motivo, ela será fechada.
