### ISSUE TITLE
Adaptação e criação de Dockerfiles para novos módulos do sistema distribuído.

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#728]
## Comportamento esperado

Desenvolver dockerfiles para cada um dos módulos na coleta distribuída, como Writer e CrawlerManager. Além disso, deve integrar os dockerfiles atuais a coleta distribuída e adaptar o docker-compose, para execução do sistema.

## Comportamento atual

Alguns do módulos da coleta distribuída não tem Dockerfiles correspondentes e os dockerfile atuais não estão encaixados na coleta distribuída.

## Passos para reproduzir o erro

Não se aplica.

## Especificações da Coleta

Não se aplica.

**Comment by elvesrodrigues** [comment]
Essa issue é a mesma que a #720.
