### ISSUE TITLE
Desenvolver mecanismo de comparação de coletas para controle incremental de recoletas.

### ISSUE THREAD

**Issue by rennancl** [MPMG-DCC-UFMG/C01#734]
## Comportamento esperado

Dado que o mecanismo de versionamento e registro de operações está pronto em #735. É Desejável que se tenha um mecanismo de coleta incremental, ou seja, a nova coleta não precisa começar do zero, e sim adicionar apenas dados novos em relação a outra versão. Esse controle pode ser tanto através do impedimento de requisições repetidas, como também através da comparação dos arquivos anteriores e novos. Essa issue pode conversar também com o mecanismo de recoleta #733 

## Comportamento atual

Atualmente, as coletas são executadas através de instâncias que possuem apenas um período de execução, e executam todas as requisições possíveis do zero, sem que se tenha a informação de uma coleta anterior.

## Passos para reproduzir o erro

Não se aplica.

## Especificações da Coleta

Não se aplica.

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/734?planning-poker) with ZenHub @elvesrodrigues @lucasaug

**Comment by lucasaug** [comment]
Faria sentido atribuir a #735 como dependência dessa issue?

**Comment by elvesrodrigues** [comment]
@lucasaug Eu acredito que sim, pois muito provavelmente nos basearemos na issue mencionada para resolver essa.

**Comment by lucasaug** [comment]
@elvesrodrigues Vou atribuir a dependência então, caso haja alguma objeção, podem mandar aqui que alteramos de acordo.
