### ISSUE TITLE
Tornar as páginas do sistema responsivas

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#739]
## Comportamento Esperado
Ao abrir as páginas do sistema que elas se adaptassem ao tamanho da tela.

## Comportamento Atual
Em alguns equipamentos o site abre muito maior, necessitando de rolagem, mesmo tendo espaço em branco sobrando, ou textos que poderiam ser quebrados em mais de uma linha para uma melhor visibilidade.

## Screenshots (caso necessário)
![image](https://user-images.githubusercontent.com/8015073/132731090-22064f34-e09b-41cb-9b3f-318cdd9f381a.png)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/739?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn
