### ISSUE TITLE
Documentar uma FAQ na nossa issue para orientação sobre decisões de configuração de coleta

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#742]
## Comportamento esperado
Desejamos ter uma página com perguntas frequentes que auxiliem os usuários a entenderem as fontes a serem coletadas e qual a melhor abordagem usar para coletar as páginas. Essa página pode conter também boas práticas.

## Comportamento atual

Hoje, a wiki funciona como um guia inicial para instalar e utilizar o sistema e suas ferramentas, mas não dá nenhum direcionamento sobre boas práticas de coleta e como criar uma configuração possível para cada tipo de fonte.

## Passos para reproduzir o erro

Não se aplica

## Especificação da coleta 

Não se aplica

**Comment by rennancordeiro** [comment]
@louisaturn, @aluiza22 e @matheusfebarbosa, poderiam ler a FAQ e revisar, por favor?

**Comment by aluiza22** [comment]
ei, @rennancordeiro achei que ficou ótimo! 
talvez poderíamos adicionar no item da estrutura de pastas o padrão preferível: [raiz das coletas]/[Município]/[alvo da coleta]? daria de colocar um exemplo e talvez a dica de dar uma olhada se já não existem esses diretórios, pra não acabar sobrescrevendo outra coleta parecida ou até reaproveitar o trabalho já feito. Mas como essas questões são mais relacionadas a nossa logística interna, não sei se caberia no FAQ, mas enfim.. vê o que você acha melhor heheheh 
mas fora essa sugestão, já está muito bom! 😊

**Comment by rennancordeiro** [comment]
> ei, @rennancordeiro achei que ficou ótimo! talvez poderíamos adicionar no item da estrutura de pastas o padrão preferível: [raiz das coletas]/[Município]/[alvo da coleta]? daria de colocar um exemplo e talvez a dica de dar uma olhada se já não existem esses diretórios, pra não acabar sobrescrevendo outra coleta parecida ou até reaproveitar o trabalho já feito. Mas como essas questões são mais relacionadas a nossa logística interna, não sei se caberia no FAQ, mas enfim.. vê o que você acha melhor heheheh mas fora essa sugestão, já está muito bom! blush

Olá @aluiza22, irei fazê-lo! Obrigado pela revisão. @matheusfebarbosa e @louisaturn, algum comentário?

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/742?planning-poker) with ZenHub @brenomatos @aluiza22 @matheusfebarbosa

**Comment by louisaturn** [comment]
Para mim, ficou ótimo! O esquema de boas práticas ficou como eu estava imaginando mesmo!

**Comment by matheusfebarbosa** [comment]
Dei uma lida e achei ótimo tambem.
