### ISSUE TITLE
Corrigir bug com coleta dinâmica no modo de execução com Docker

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#743]
## Comportamento Esperado

Desejamos que o processamento dinâmico funcione também no modo de execução em Docker.

## Comportamento Atual

No docker, ao executar uma coleta com processamento dinâmico, o sistema trava e não avança na coleta.

## Passos para reproduzir o erro

  1. Executar o sitema no docker
  2. Configurar e executar uma coleta com processamento dinâmico.

## Especificações da Coleta

Qualquer uma que utiliza passos.

## Sistema (caso necessário)

Execução em Docker

## Screenshots (caso necessário)
![image](https://user-images.githubusercontent.com/22959153/133254973-646cfe73-afb2-4c55-a80a-e69bc313428c.png)

A pista que temos é esse erro:
![image](https://user-images.githubusercontent.com/22959153/133254991-05a8bfd1-2ecb-4a0e-8016-29f99a5a2b7d.png)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/743?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by elvesrodrigues** [comment]
Na versão atual do sistema distribuído, que está com docker, esse problema não ocorre. Mas me recordo de ter tido problemas parecidos com os do screenshot. Então muito possivelmente já será resolvida ao se integrar a solução distribuída na master.
