### ISSUE TITLE
Resolver carregamento infinito de formulários devido a bug no JQuery.

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#744]
## Comportamento Esperado

Desejamos que a requisição de formulários funcione corretamente.

## Comportamento Atual

Ao fazer uma requisição para os formulários de uma página, o modal de seleção de campos apresenta um carregamento infinito, que nunca para. Ao observar o console, é possível ver erros no JQuery

## Passos para reproduzir o erro

  1. Abrir interface de configuração de coletores
  2. Preencher com informações básicas
  3. Entrar na aba de formulários e pedir para carregá-los

## Especificações da Coleta

O experimento seguiu a coleta de exemplo na página 07 da wiki.  

## Sistema (caso necessário)

Qualquer sitema.

## Screenshots (caso necessário)

![image](https://user-images.githubusercontent.com/22959153/133255690-3262cac4-9d51-4e3c-84cf-4ed40a252532.png)

**Comment by lucasaug** [comment]
Investigando o erro descobrimos que se trata apenas de um erro na atualização da cache do navegador, que armazenava uma versão antiga dos códigos Javascript. Atualizando a página com `Ctrl + Shift + R` é possível limpar essa cache, e o erro é resolvido.
