### ISSUE TITLE
Coleta geral do portal de transparência de Pouso Alegre. #682 

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#751]
## Comportamento Esperado
Requisição da extração de páginas html do portal da prefeitura de Pouso Alegre. A extração tem o objetivo de obter dados para a criação de validadores para identificar a presença de itens no portal de transparência da prefeitura de Pouso Alegre.

## Comportamento Atual
Uma [issue ](https://github.com/MPMG-DCC-UFMG/C01/issues/682) já havia sido criada previamente e os dados coletados, contudo é necessário que a coleta seja realizada novamente pois a atual apresenta problemas com caracteres especiais.  

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
(e.g. /datalake/ufmg/webcrawlerc01/realizacaof01/pouso_alegre).

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal da prefeitura de Pouso Alegre, nos seguintes links:
•https://www.pousoalegre.mg.gov.br/
•https://pousoalegre.atende.net/?pg=transparencia#!/

E todos os html das primeiras páginas alcançáveis a partir de:
•https://pousoalegre.atende.net/?pg=transparencia#!/

Para essa coleta, é necessário aguardar o carregamento de cada página.

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by carbo6ufmg** [comment]
A coleta dessa fonte foi realizada. Os dados encontram-se em /datalake/ufmg/webcrawlerc01/realizacaof01/pouso_alegre, separados em prefeitura e transparencia. Caso haja algum problema com a coleta, favor informar por meio da issue.
