### ISSUE TITLE
Travamento do scrapy em coletas dinâmicas - "Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)"

### ISSUE THREAD

**Issue by matheusfebarbosa** [MPMG-DCC-UFMG/C01#764]
## Comportamento Esperado
Fazer coletas dinâmicas que envolvam loops e abrir novas abas.

## Comportamento Atual
Recentemente foi percebido um comportamento estranho em coletas dinâmicas que envolvem a utilização de loops e multiplas abas.  No caso, a coleta começa a rodar normalmente e após um tempo executando simplesmente trava, e o log de erro começa a mostrar repetidamente uma mensagem como essa:

`2021-09-22 05:08:56 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)`

## Passos para reproduzir o erro

Basta produzir alguma coleta dinamica que possua um loop que executa diversas vezes, ou que utilize o mecanismo de abrir novas abas.

Um exemplo é a seguinte [coleta](https://drive.google.com/file/d/1EAE0fDuyy4UPR48Ww32kwaUe8JW6_46d/view?usp=sharing).

**Comment by aluiza22** [comment]
Também percebi em algumas coletas esse comportamento quando tento usar o passo de abas.

**Comment by aluiza22** [comment]
Seguem os prints e configuração de duas coletas que apresentaram esse problema:

![photo5050887643700766951](https://user-images.githubusercontent.com/20428782/134554073-ff73508d-b101-4f0a-a6d4-83aaed9a6534.jpg)

`{ 
  "source_name": "Licita\u00e7\u00f5es de Ilic\u00ednea", 
  "base_url": "http://ilicinea.mg.gov.br/licitacao/?idStatusLicitacao=1", 
  "obey_robots": false, 
  "data_path": "/home/ana/coletas/Ilicinea/licitacoes_ilicinea", 
  "request_type": "GET", 
  "form_request_type": "POST", 
  "antiblock_download_delay": 2, 
  "antiblock_autothrottle_enabled": false, 
  "antiblock_autothrottle_start_delay": 2, 
  "antiblock_autothrottle_max_delay": 10, 
  "antiblock_mask_type": "none", 
  "antiblock_ip_rotation_type": "tor", 
  "antiblock_proxy_list": "", 
  "antiblock_max_reqs_per_ip": 10, 
  "antiblock_max_reuse_rounds": 10, 
  "antiblock_reqs_per_user_agent": null, 
  "antiblock_user_agents_file": "", 
  "antiblock_cookies_file": "", 
  "antiblock_persist_cookies": false, 
  "captcha": "none", 
  "has_webdriver": false, 
  "webdriver_path": "", 
  "img_xpath": "", 
  "sound_xpath": "", 
  "dynamic_processing": true, 
  "explore_links": false, 
  "link_extractor_max_depth": null, 
  "link_extractor_allow_url": "", 
  "link_extractor_allow_domains": "", 
  "link_extractor_tags": "", 
  "link_extractor_attrs": "", 
  "link_extractor_check_type": false, 
  "link_extractor_process_value": "", 
  "download_files": false, 
  "download_files_allow_url": "", 
  "download_files_allow_extensions": "", 
  "download_files_allow_domains": "", 
  "download_files_tags": "", 
  "download_files_attrs": "", 
  "download_files_process_value": "", 
  "download_files_check_large_content": false, 
  "download_imgs": false, 
  "steps": "{\"step\":\"root\",\"depth\":0,\"children\":[{\"step\":\"espere\",\"depth\":1,\"arguments\":{\"segundos\":\"10\"}},{\"step\":\"para_cada\",\"depth\":1,\"iterator\":\"lic\",\"children\":[{\"step\":\"abrir_em_nova_aba\",\"depth\":2,\"link_xpath\":\"lic\",\"children\":[]},{\"step\":\"espere\",\"depth\":2,\"arguments\":{\"segundos\":\"10\"}},{\"step\":\"salva_pagina\",\"depth\":2,\"arguments\":{}},{\"step\":\"fechar_aba\",\"depth\":2,\"arguments\":{}}],\"iterable\":{\"call\":{\"step\":\"localiza_elementos\",\"arguments\":{\"xpath\":\"\\\"/html/body/div[2]/div[3]/div/div/div[2]/table[*]/tbody/tr[4]/td/center/a\\\"\"}}}}]}", 
  "encoding_detection_method": 1, 
  "templated_url_parameter_handlers": [], 
  "static_form_parameter_handlers": [], 
  "templated_url_response_handlers": [], 
  "static_form_response_handlers": [], 
  "crawler_id": 32, 
  "instance_id": "163175420351855" 
}`

![photo5050887643700766953](https://user-images.githubusercontent.com/20428782/134554365-fdc17e76-a5b4-4eca-a6df-4ef35cb41d30.jpg)

`{ 
  "source_name": "Licita\u00e7\u00f5es de Par\u00e1 de Minas", 
  "base_url": "https://transparencia.parademinas.mg.gov.br/licitacoes", 
  "obey_robots": false, 
  "data_path": "/home/ana/coletas/Para_de_Minas/licitacoes", 
  "request_type": "GET", 
  "form_request_type": "POST", 
  "antiblock_download_delay": 2, 
  "antiblock_autothrottle_enabled": false, 
  "antiblock_autothrottle_start_delay": 2, 
  "antiblock_autothrottle_max_delay": 10, 
  "antiblock_mask_type": "none", 
  "antiblock_ip_rotation_type": "tor", 
  "antiblock_proxy_list": "", 
  "antiblock_max_reqs_per_ip": 10, 
  "antiblock_max_reuse_rounds": 10, 
  "antiblock_reqs_per_user_agent": null, 
  "antiblock_user_agents_file": "", 
  "antiblock_cookies_file": "", 
  "antiblock_persist_cookies": false, 
  "captcha": "none", 
  "has_webdriver": false, 
  "webdriver_path": "", 
  "img_xpath": "", 
  "sound_xpath": "", 
  "dynamic_processing": true, 
  "explore_links": false, 
  "link_extractor_max_depth": null, 
  "link_extractor_allow_url": "", 
  "link_extractor_allow_domains": "", 
  "link_extractor_tags": "", 
  "link_extractor_attrs": "", 
  "link_extractor_check_type": false, 
  "link_extractor_process_value": "", 
  "download_files": false, 
  "download_files_allow_url": "", 
  "download_files_allow_extensions": "", 
  "download_files_allow_domains": "", 
  "download_files_tags": "", 
  "download_files_attrs": "", 
  "download_files_process_value": "", 
  "download_files_check_large_content": false, 
  "download_imgs": false, 
  "steps": "{\"step\":\"root\",\"depth\":0,\"children\":[{\"step\":\"espere\",\"depth\":1,\"arguments\":{\"segundos\":\"10\"}},{\"step\":\"para_cada\",\"depth\":1,\"iterator\":\"lic\",\"children\":[{\"step\":\"abrir_em_nova_aba\",\"depth\":2,\"link_xpath\":\"lic\",\"children\":[]},{\"step\":\"espere\",\"depth\":2,\"arguments\":{\"segundos\":\"10\"}},{\"step\":\"salva_pagina\",\"depth\":2,\"arguments\":{}},{\"step\":\"fechar_aba\",\"depth\":2,\"arguments\":{}}],\"iterable\":{\"call\":{\"step\":\"localiza_elementos\",\"arguments\":{\"xpath\":\"\\\"/html/body/div[1]/div/form/div[4]/div/div[2]/div/div[2]/div[3]/div[4]/div/ul[*]/li/div/h3/a\\\"\"}}}}]}", 
  "encoding_detection_method": 1, 
  "templated_url_parameter_handlers": [], 
  "static_form_parameter_handlers": [], 
  "templated_url_response_handlers": [], 
  "static_form_response_handlers": [], 
  "crawler_id": 28, 
  "instance_id": "163175441303406" 
}`

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/764?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa
