### ISSUE TITLE
Uniformização de versões de JQuery e bibliotecas de interface

### ISSUE THREAD

**Issue by rennancl** [MPMG-DCC-UFMG/C01#770]
## Comportamento Esperado

Desejamos que a interface funcione corretamente de forma uniforme.

## Comportamento Atual

Temos uma versão do JQuery que funciona em partes da interface enquanto outras não. Dependendo da versão, partes da interface funciona ou não de maneira não coesa. Para entender a discussão, verificar os comentários nessa thread: 

https://github.com/MPMG-DCC-UFMG/C01/pull/326/files/97a8da6fb0f1483f08047aa6984f031fe5608629#r716976548

## Passos para reproduzir o erro

Não se aplcia

## Especificações da Coleta

Não se aplica

## Sistema (caso necessário)

Não se aplica

## Screenshots (caso necessário)
Cada uma das versões abaixo funcionam em partes diferentes.
![image](https://user-images.githubusercontent.com/22959153/135138346-08867701-f196-4ed8-bc74-9b2a20866971.png)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/770?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa

**Comment by elvesrodrigues** [comment]
@caiocvsilva e @matheusfebarbosa eu dei **3 pontos** para essa issue por acreditar que, como será preciso mexer em apenas um arquivo, o `base.html`, e há um pequeno número de bibliotecas que usamos, identificar aquela correta seria relativamente simples de resolver, até mesmo por tentativa e erro.

**Comment by matheusfebarbosa** [comment]
@elvesrodrigues eu dei 8 pontos pensando em possíveis conflitos que poderiam ocorrer ao mudar a versão em alguns módulos. Porém reconsiderando, parece que é uma situação que nao tem muita chance de ter conflito mesmo, então por enquanto vou alterar e entrar em concordancia com o Caio mudando para um 5.
