### ISSUE TITLE
Problema na digitação em campos com mecanismo de passos

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#7758]
## Comportamento Esperado
Ao utilizar o passo "digite" do mecanismo de passos, é esperado que os caracteres sejam inseridos corretamente, sendo o mais robusto possível para diferentes tipo de campo.

## Comportamento Atual
Em algumas coletas o passo "digite" insere os caracteres incorretamente, preenchendo o campo com um valor inválido.

## Passos para reproduzir o erro
Testar as seguintes coletas:

- [Realização-F01] Coleta de Receitas de Perdizes
- [Realização-F01] Coleta de Acesso à Informação de Perdizes
- [Realização-F01] Coleta de Contratos de Serra do Salitre

Os screenshots da coleta após digitar as datas nos campos exibe o problema descrito.

## Especificações da Coleta

Disponíveis nas configurações de coleta no MP.  

## Screenshots

Exemplo da coleta de Acesso à Informação de Perdizes:

![digite](https://user-images.githubusercontent.com/1329255/200060151-22d109be-7bb4-4d32-84bb-0699c5342e85.png)

**Comment by elvesrodrigues** [comment]
Obs.: Para o coletor Serra do Salitre, a url inicial mudou para http://138.186.222.129:8444/transparencia/
