### ISSUE TITLE
Erro em coleta de despesas de pagamentos de Jequitinhonha

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#7767]
## Comportamento Esperado
As páginas no coletor dinâmico deve ser consistentes com o que observamos ao abrir a mesma página no navegador.

## Comportamento Atual
A página inicial da coleta difere do que é observado no navegador. Isso impede a execução do restante da coleta.

## Passos para reproduzir o erro
Testar a coleta "[Realização-F01] Coleta de Despesas - Pagamentos de Jequitinhonha".

**Comment by caiocvsilva** [comment]
Não pude encontrar uma issue intitulada "[Realização-F01] Coleta de Despesas - Pagamentos de Jequitinhonha" para teste e correção. Todas as issues de Jequitinhonha foram finalizadas e aparentemente sem problemas. Caso haja a necessidade, esta issue pode ser reaberta com mais informações.
