### ISSUE TITLE
Ajustar a ordenação da listagem de coletores

### ISSUE THREAD

**Issue by aluiza22** [MPMG-DCC-UFMG/C01#783]
## Comportamento Esperado
Os coletores com instâncias em execução ou modificados recentimente ficam no topo da listagem

## Comportamento Atual
Os coletores são ordenados apenas por ordem de criação, então se um coletor mais antigo estiver sendo utilizado, é preciso fazer um scroll e encontrar ele na lista, que pode ser longa.

## Passos para reproduzir o erro

  1. Ter vários coletores cadastrados
  2. Trabalhar com um coletor antigo

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/783?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn
