### ISSUE TITLE
Mudar redirecionamento após salvar um coletor

### ISSUE THREAD

**Issue by aluiza22** [MPMG-DCC-UFMG/C01#784]
## Comportamento Esperado
Após criar ou editar um coletor, a página de detalhes do mesmo deveria ser apresentada, ficando mais fácil dar seguimento a execução da mesma.

## Comportamento Atual
Quando um coletor é criado ou editado, o usuário é redirecionado para a listagem de coletores, que então precisa encontrar o coletor em questão e clicar pra ver seus detalhes.

## Passos para reproduzir o erro

  1. Criar ou editar/salvar um coletor

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/784?planning-poker) with ZenHub @brenomatos @aluiza22 @louisaturn
