### ISSUE TITLE
Coleta de dados dos pagamentos de Teófilo Otoni

### ISSUE THREAD

**Issue by RitaRez** [MPMG-DCC-UFMG/C01#793]
## Comportamento Esperado
Requisição da extração de arquivos referentes aos pagamentos da cidade de Teófilo Otoni, a extração tem o objetivo de obter os arquivos html disponíveis dos pagamentos.

## Comportamento Atual
Não se aplica.

## Localização
Não possui nenhuma coleta atualmente.
Para fins de organização separar dados a nível de município
 (e.g./datalake/ufmg/webcrawlerc01/realizacaof01/teofilo_otoni/pagamentos).

## Detalhes da fonte
https://transparencia.teofilootoni.mg.gov.br/portalcidadao/#78c3e513dd43cb27d8a3e2f376196ffc656d7ea577b2c6fb1cb17c%C4%B19146ff524ae4a79fe1723a6d0fda3be4821fad75c57b9fd50f604078d1c8dfe7ebbe74a6b7308c2ff6f90cba938cd235c84796711fe7a23eb9f19dbc76c872fb21a188e9e0f8f3d2d265661ae31ae5dd7867f02377ee660ea8f05c7446c62137249051396651c2030652a6938925f013a4b6b4fc8fecfe3b3557d694b29f8f57ee6ce5d3822fb92671766dc1d15ecb7b8e3c0e8cac97bfcf5356c5439d345edc6ee0ce5450c54d9db9ee0c2606074ede0150d6b5edb40dc58ddfbbdc6cf2c54d7f523fea5364f0a04259107b5c3fb113d91ab6287

É de nosso interesse o html da página acima e o html resultante de todas as buscas. Para isso é necessário realizar uma busca para cada ano de 2013 até 2021 adicionando como período um ano completo, de 01/01/ano até 31/12/ano.

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica

**Comment by carbo6ufmg** [comment]
Fonte de coleta instável ou não carrega.
