### ISSUE TITLE
Inclusão do passo while na interface

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#798]
# Comportamento Esperado
Deseja-se a possibilidade de configurar o passo de while a partir da interface. Para isso, deve se alterar as chamadas Javascript responsáveis por gerar o json de passos e por mostrar os passos na interface.

# Comportamento Atual
Embora o código em Python para executá-lo já exista, ainda não existe a definição de como deve ser processado na interface;

# Passos para reproduzir o erro
Não se aplica

# Sistema (caso necessário)
Não se aplica

# Screenshots (caso necessário)
Não se aplica

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/798?planning-poker) with ZenHub @louisaturn @matheusfebarbosa

**Comment by rennancordeiro** [comment]
Olá @louisaturn e @matheusfebarbosa dei 5 pontos, pois acredito que esse deve ser um passo simples de ser implementado. Imagino que o código final deve ser semelhante à implementação atual do passo "Para cada", dessa maneira, bastaríamos duplicar o código e fazer as adaptações necessárias, sem muitos desafios envolvidos.

**Comment by matheusfebarbosa** [comment]
Resolvido por #975
