### ISSUE TITLE
Coleta reclame aqui

### ISSUE THREAD

**Issue by yohangumiel** [MPMG-DCC-UFMG/C01#842]
**Comportamento Esperado**

Requisição da extração das reclamações dos consumidores presentes na plataforma reclame aqui, focando nos relatos envolvendo empresas.

A coleta tem o objetivo de obter todos os relatos de consumidores para cada empresa coletada. Sendo assim é de suma importância obter todas as reclamações para cada empresa. Cada reclamação tem um link html próprio, este contendo todas as informações necessárias. 

**Comportamento Atual**

Não se aplica.

**Objetivo**

Obter o html de todas as reclamações do reclame aqui. Dentre as empresas buscadas obter todos os htmls, um exemplo de html para uma reclamação do ifood (https://www.reclameaqui.com.br/ifood/nao-me-entregaram-nem-metade-do-pedido_QlFA25w6BFSm5f6J/).

Para chegar nas reclamações é necessário acessar a página de cada empresa, como do ifood (https://www.reclameaqui.com.br/empresa/ifood/lista-reclamacoes/). Para chegar na página de cada empresa sugiro utilizar o campo de busca e utilizar uma lista de nomes de empresa (que podemos fornecer) ou testar diferentes combinações de caracteres (“aa”, “ab”, etc). A segunda alternativa pode ter certas limitações principalmente relacionada a quantidade de empresas mostradas após a busca (parece ter um limite).

**Localização**

Site do reclame aqui (https://www.reclameaqui.com.br/)

Buscar determinada empresa (exemplo do ifood: https://www.reclameaqui.com.br/empresa/ifood/)

Dentro das reclamações acessar “todas as reclamações” através do botão.

Obter todas as htmls de todas as reclamações para cada empresa buscada. 

**Detalhes da fonte/Screenshots**

Para chegar na página da empresa sugiro duas abordagens: (1) usar uma lista de nomes e (2) testar diferentes combinações de caracteres.

Inicialmente buscar a empresa no campo de busca (https://www.reclameaqui.com.br/)

![issuereclameaqui1](https://user-images.githubusercontent.com/50462141/138750781-807a8f21-1822-47c2-b705-f910ca348ad2.png)

Quando se busca uma determinada empresa ou combinação de caracteres (dois ou mais) aparecem empresas. No exemplo abaixo foi buscado o termo ifood e na lista de resultados está a empresa ifood.

![issuereclameaqui2](https://user-images.githubusercontent.com/50462141/138750823-30a2c406-7260-441b-924b-0611dd21c70a.png)

O próximo passo é clicar na empresa, redirecionando para a própria página da empresa. Considerando o formato do endereço que somos direcionados (exemplo para o ifood: https://www.reclameaqui.com.br/empresa/ifood/), alguma abordagem que automaticamente gere estes endereços pode ser interessante (lista de empresas e/ou combinações de palavras/caracteres).

Na página da empresa clique para ver todas as reclamações.

![issuereclameaqui3](https://user-images.githubusercontent.com/50462141/138750886-41e07364-934c-4d82-bc32-c6158884737c.png)

Para cada reclamação obter o endereço html para cada uma das reclamações encontradas.

![issuereclameaqui4](https://user-images.githubusercontent.com/50462141/138750919-3f2c522a-ae7f-479c-a9c8-e62dcf4424cb.png)

Exemplo de reclamação.

![issuereclameaqui5](https://user-images.githubusercontent.com/50462141/138750947-7d472323-0640-4089-a8a7-ba56e09d148a.png)

**Detalhes da trilha**

Coleta pedida pelos Professores Rodrygo Santos e Marcos Gonçalves. Relacionado com as trilhas F06 e P03.

Membros para contato:

Yohan Bonescki Gumiel
E-mail: yohan.gumiel@gmail.com
Discord: YoGumiel#9701
Github: https://github.com/yohangumiel/

Felipe Costa
E-mail: felipealco@gmail.com
Discord: felipealco#5580

**Comment by caiocvsilva** [comment]
Olá, @yohangumiel, se você puder fornecer a lista de empresas que estão interessados, acredito que a coleta desta fonte poderá ser realizada de forma mais rápida.

**Comment by yohangumiel** [comment]
Olá @caiocvsilva
Segue uma lista das empreas, grato!

Acentra
Acredicoop
Ademilar Consórcio de Investimento Imobiliário
Adidas
Águas Alta Floresta
Águas Andradina
Águas Canarana
Águas Castilho
Águas Colíder
Águas Comodoro
Águas Cuiabá
Águas da Condessa
Águas das Agulhas Negras
Águas de Araçoiaba
Águas de Jahu
Águas de Juturnaíba
Águas de Manaus
Águas de Nova Friburgo
Águas de Paraty
Águas de Timon
Águas de Votorantim
Águas do Imperador
Águas do Rio
Águas Guariroba
Águas Piquete
Águas Pontes e Lacerda
Ailos Corretora de Seguros
Airbnb
Ajinomoto do Brasil
Alelo - Veloe - Pede Pronto
Alfa Arrendamento Mercantil
Alfa Corretora
Aliança da Bahia
Aliança Móveis
ALM Seguradora
Alpargatas (Havaianas, Osklen, Dupé)
Amazonas by Viverde
Americanas
Angelus Seguros
Aplicap Capitalização
APLUB Capitalização
APLUB (DESATIVADA)
Aruana Seguradora
Assaí Atacadista
Atradius Crédito y Caución
Austral Lineas Aereas - Cielos del Sur
AUX
Avior Airlines
AXA Corporate Solutions Seguros
Backseg
Bahamas Cred
Banco ABC
Banco Arbi
Banco Bari
Banco BV (antigo Banco Votorantim)
Banco Fibra
Banco Inbursa
Banco Master (antigo Banco Máxima)
Banco Next
Banco Pine
Banco SmartBank
Banco Voiter
Banco XP
Banestes Seguros
Bayer - Divisão Agrícola
Bayer - Saúde Ambiental
B.blend Máquinas e Bebidas
BCV (DESATIVADA - atual Banco BMG)
BeeFitness.com.br
Beleza na Web Pro
Bem Brasil Alimentos
Benx Incorporadora
Berkley Brasil Seguros 
Betânia Lácteos
Big Bompreço
Bil Intercâmbios
Blockbuster (DESATIVADA)
Blockbuster online (DESATIVADA)
BMG Seguros
BobStore - Loja Online
Boehringer Ingelheim - Saúde Animal
Boehringer Ingelheim - Saúde Humana
Booking.com
Bradesco Leasing
Breitkopf Caminhões
Breitkopf Veículos
BRK Ambiental Maranhão
BRK Ambiental Tocantins (Saneatins)
BTG Pactual Seguros
BTG Pactual Vida e Previdência
Buser Brasil
BV Financeira (DESATIVADA)
BV Leasing (DESATIVADA)
Caedu
Cagece
Cagepa
Capemisa Capitalização
Caramuru Alimentos
Care Plus Medicina Assistencial
Cartão Cencosud GBarbosa
Cartola
Casa do Crédito
Casan - Companhia Catarinense de Águas e Saneamento
CEEE Distribuição
Célebre 
Centauro-ON Vida e Previdência
Centro Universitário Fundação Santo André - FSA
Cerim
Cesan
Chevrolet Serviços Financeiros (Banco GM)
Cia de Automóveis Slaviero - Curitiba
Ciclic
City Lar (DESATIVADA)
Civia
Clinipam
Clube de Saúde 
Cocel - Companhia Campolarguense de Energia
Colchões Gazin
Colégio Copérnico
Combate
Compesa
Comprei Pontuei (DESATIVADA)
Comprev Seguradora
Condor
Consórcio Gazin
Consórcio Nacional Chevrolet
Consórcio Realiza (DESATIVADA)
Consórcio Remaza
Consórcio Reserva
Consórcio Unilance (DESATIVADA)
CoopCorreios
CooperJohnson
Coopernapi
Cosesp
Cotação
CPFL Piratininga
CPFL Santa Cruz
CredCrea
Credelesc
Credicitrus
Credicomin
Credifoz
Creditas
Crefisa Seguros
Crevisc
Cruz Azul Saúde
Cyrela
DAE Jundiaí
Danymotos
Dayprev Vida e Previdência
Deezer
Direcional Engenharia
DIX Amico (DESATIVADA)
DMCard
Drogaria Nova Esperança
Dudalina (DESATIVADA)
Duoflex Travesseiros
Duracell
Edelweiss Air
Editora Abril
Educa Mais Brasil Programas Educacionais
Eletro Aquila
Eletro Shopping (DESATIVADA)
Eletrocar - Centrais Elétricas de Carazinho
Eletrosol Materiais Elétricos (DESATIVADA)
Elevadores Atlas Schindler
Ellus - Loja Online
Emotion Seguros
Empresa de Saneamento de Palestina - ESAP
Empresa Luz e Força Santa Maria - ELFSM
Energisa Borborema
Energisa Mato Grosso do Sul 
Energisa Nova Friburgo
Energisa Paraíba
Energisa Sergipe
Enjoei
EQ Seguros (antiga Equatorial Seguradora)
Equatorial Alagoas
Equatorial Previdência
Escola Metropolitana de Ribeirão Preto
Essor Seguros
Etna
Eudora (Interbelle)
Evolua
Ezze Seguros
Facebook / Instagram
Facta Seguradora
Fairfax Brasil
Fairway Seguros (antiga Travelers Seguros Brasil)
Farmamed Drogaria (DESATIVADA)
FATECE
Fator Seguradora
Ferrero do Brasil
Financeira BRB
Flexform
Futon Company
Futuro Previdência Privada
Gama Saúde
Gás Natural Serviços (Naturgy Soluções)
Gazin Seguros
Gazincred
GBarbosa
GEAP (DESATIVADA)
General Mills (Yoki, Kitano, Mais Vita, Haagen Dazs, Betty Crocker)
Globoplay
Gree
Grife Relógios
Guten Bier
Harald
HDI Global Seguros
Hello Study
Hering
Hospital Águas Claras
HS Seguros
HSBC (DESATIVADA)
IE Intercâmbio
Ilunato
ImpressorAjato.com
Incepa
Indiana Seguros
Infracommerce
Insinuante (DESATIVADA)
Instituto Mix de Profissões
Intelig
Interconnect Exchange Brasil
Interep
ITA Bank
Itambé
Itapemirim Transportes Aéreos
Itapoá Saneamento
Iu-á Hotel
JBL Turismo
JNS Seguros
Jocar
Kalunga
Karsten
Kellogg's / Parati
Kian Iluminação
Komeco
Kovr Capitalização (antiga Invest Cap)
Kovr Previdência (antiga Investprev Seguros e Previdência)
Kovr Seguradora (antiga Invest Seguradora)
Lactalis (Président Parmalat Elegê Batavo Cotochés Poços de Caldas Balkis Boa Nata Dobon Galbani)
Lalamove
Lancers Administradora
Laser Eletro
Lebes.com.br
Living
Localiza Meoo
Localiza Seminovos
Localiza Zarp
Loft
Loggi
Loja Brazil
Lojas Dona do Lar
Lojas Koerich
Lojas Salfer (DESATIVADA)
Lojas Sipolatti
L’Oréal Brasil
Luxottica
L4B Logística (Loggi XD)
MadeiraMadeira
Magic City
Mapfre Capitalização
Mapfre Investimentos
Mapfre Saúde
Marabraz.com
Marelli - Móveis para Escritório
Maternidade Brasília
Maxxi Atacado
Menu Móveis
Mercadinhos São Luiz - Ceará
Mercadorama
Mercantil Rodrigues
Metlife Administradora de Fundos Multipatrocinados (MultiPrev)
MG Seguros
MGW Ativos
Midway (Riachuelo)
Mistertech
Momenta Farmacêutica
Móveis Gazin
Multi B
Multilaser
Nacional
Natália Jóias
Neoenergia Brasília (CEB)
Neoenergia Coelba
Neoenergia Cosern
Neoenergia Elektro
Neoenergia Pernambuco (Celpe)
Net Catanduva (DESATIVADA)
Netbabys
Netfarma (DESATIVADA)
Newe Seguros
O Boticário (Interbelle)
OfficeTotalShop
OLX
OLX Pay
Omint Seguros
OMNI Informática
Óticas Carol
OUi Paris
Oxxy Seguradora
Paranaguá Saneamento
Paranair
Pater Seguros
Pecúlio União Previdência Privada
Pefisa
Perfu.me (DESATIVADA)
Perini
Perkus
Philips Avent e Cuidados Pessoais
Philips Walita
Pier Seguradora
Pincred
Piracanjuba
Plena Saúde
PointGres (DESATIVADA – atual Perkus)
Politorno (DESATIVADA)
Pottencial Seguradora
Poupecredi
Premiere
Previmax Previdência Privada e Seguradora
Prezunic
Procter & Gamble (P&G)
QBE Brasil Seguros (DESATIVADA – atual Zurich Seguros)
QI Tech
Qsaúde
Recíproca Assistência
Renault On Demand
Rinnai
Rio Grande Capitalização
Rio Grande Seguros e Previdência
Rio Verde Engenharia
Roraima Energia
Royal Canin do Brasil
Safra Seguros Gerais
Safra Vida e Previdência
Salinas - Loja Online
Salvador Norte Shopping
Salvador Shopping
Samsung - Loja Online
Saneago
Saneamento de Mirassol - Sanessol
Santa Helena Saúde
Santinvest
Seguros Atual
Seguros Honda
Seven Boys
Shipp - Americanas Delivery
Shopee Brasil
Shopping Jardins Aracaju
Shopping Riomar Aracaju
Shopping Riomar Fortaleza
Shopping Riomar Kennedy
Shopping Riomar Recife
Shoptime Viagens
Sinaf Seguros
Sinosserra Financeira
Sinosserra Seguros
Smartfit
SOBAM Centro Médico
Sociedade Caxiense de Mútuo Socorro
Sompo Saúde 
Sonda Supermercados
Spirit Ventiladores
Starbucks @ home
Starr Brasil Seguradora
SudaVida (antiga Sudamerica Vida)
Suhai Seguradora
SulAmérica Capitalização
SULGIPE – Companhia Sul Sergipana de Eletricidade
SumUp
Sunglass Hut
Supera Farma
Superbompreço
Supermed
Supermercadinhos Santa Rita - Ceará
Supermercado Nidobox 
Supermercado Now
Supermercados Mundial
Supermercados Super Lagoa
Surinam Airways
Swiss Re Corporate Solutions Brasil Seguros
Systemcred
The Body Shop
Tickets For Fun
Todo Dia Supermercados
Tok&Stok - Loja Online
Toyoville
Transpocred
Tribanco Seguros
Triunfo Transbrasiliana
TTL Transportes
Tudus
Turbo Fitness
Two Flex Aviação Inteligente
UCB Biopharma
Unesul
União Seguradora
Uniconsult Administradora de Benefícios
Unidas Rent a Car
Unifique
Unilos
Unimed Apucarana
Unimed Blumenau 
Unimed Brusque
Unimed Cariri
Unimed Centro Oeste Paulista
Unimed Costa Oeste
Unimed Curitiba
Unimed de Pindamonhangaba
Unimed de Sobral
Unimed de Votuporanga
Unimed do Ceará
Unimed do Oeste do Paraná
Unimed Fortaleza
Unimed Guarapuava
Unimed Litoral
Unimed Londrina
Unimed Maranhão do Sul
Unimed Marquês de Valença
Unimed Noroeste do Paraná
Unimed Noroeste/RS
Unimed Norte Pioneiro - PR
Unimed Nova Iguaçu
Unimed Paraná
Unimed Pato Branco (DESATIVADA)
Unimed Patos de Minas
Unimed Piracicaba
Unimed Planalto Norte de Santa Catarina
Unimed Porto Alegre
Unimed Presidente Prudente 
Unimed Regional Campo Mourão
Unimed Ribeirão Preto
Unimed Santa Catarina
Unimed São José dos Campos
Unimed Seguros Patrimoniais
Unimed Sorocaba
Unimed Três Rios
Unimed Vale do Sepotuba
Unimed/RS Federação
UPL do Brasil
UPOFA - União Previdencial
UP.P
Usebens Seguradora
Uze
Vanguardacap Capitalização
VB Serviços
Venturi, Falmec, Smeg e Arix
Viação Continental
Viação Santa Cruz
Viacredi
Viacredi Alto Vale
Vistual (DESATIVADA)
Vitreo DTVM
Vivara
Vivaz
Viver Previdência
voulevar
VR Collezioni - Loja Online
Walmart (DESATIVADA)
Walmart.com (DESATIVADA)
Will Bank (antigo Meu Pag!)
Wiser Educação (Wise Up, Number One, MeuSucesso.com e Buzz Editora)
World Study
XS2 Vida e Previdência
XS4 Capitalização
Zema Seguros
Zoop
123 Milhas
88i Seguradora Digital
Oi Fixo
Tim
Serasa Experian 
Oi Celular
Vivo - Telefônica (GVT)
Caixa Econômica Federal
Claro Celular
Mercado Livre
SKY
NET
Americanas.com
Latam Airlines (Tam)
Samsung
Mercado Pago
Casasbahia.com
Banco Santander
Banco Bradesco
Vivo - Telefônica
Banco Itaú Unibanco
Decolar.com
Banco do Brasil
Gol Linhas Aéreas
Azul Linhas Aéreas
Cemig
Pontofrio.com
Itaucard
Magazineluiza.com
Banco Pan 
Claro TV 
Banco BMG
Boa Vista Serviços - SCPC (Serviço Central de Proteção ao Crédito)
Bradescard
Extra.com
Submarino
Banco Santander Cartões
Vivo - Telefônica 
Carrefour.com
Banco Cetelem
Bradesco Cartões
Smiles
Shoptime
Banco Inter (Banco Intermedium)
Netshoes
Ourocard
Banco C6 Consignado (Banco Ficsa)
Copasa - Companhia de Saneamento de Minas Gerais
Uber
Claro Fixo - Embratel
Itaú Consignado
Banco Safra
Cartão Carrefour
Banco Olé Consignado
BV Financeira
LG Electronics
Ricardo Eletro.com
Tudo Azul
Magazine Luiza
Ativos S.A
TAP Air Portugal
Recovery do Brasil Consultoria 
Casas Bahia
Submarino Viagens
Walmart.com
Algar Fixo
Cartões Riachuelo (Midway Financeira)
Pernambucanas Cartões
Correios
Credicard
Luizacred
Banco Mercantil do Brasil
Livelo
Losango
Bradesco Promotora 
ViajaNet
Centauro.com.br
Riachuelo - Loja Online
Santander Financiamentos (Aymoré)
Zattini
Faculdade Pitágoras
MaxMilhas
Centauro
Apple
Avon
Algar Celular
KaBuM!
SPC Brasil
Avianca - Oceanair
Pagseguro
Nubank
Pernambucanas
Multiplus 
Dafiti
Brastemp
Universidade Estácio de Sá
Natura
Dotz
American Express - Amex
C6 Bank
Marisa - Loja Online
CVC Viagens
C&A
O Boticário
Cartão Submarino
Ponto Frio
Electrolux - Linha Branca
Banco Daycoval
Caixa Seguradora
Crefisa
Amil
Banco Original
Itaú Unibanco Consignado
Ame Digital
Paraná Banco
Bradesco Financiamentos
Lojas Renner
Mondial
Consul
Privalia
GVT
Philco
iFood
Motorola
Banco Agibank (Agiplan)
Ebanx
Banco Digio
Lojas Americanas
Ricardo Eletro
Banco Votorantim 
PayPal do Brasil
Amazon.com.br
Mobly
Cielo
Nextel
Itauleasing
Omni Financeira
Bradesco Vida e Previdência
Hughes
Peixe Urbano
Itaú BMG Consignado
Getnet
Cartão Americanas.com
Pag!
Hoteis.com
Rappi
Bahamas Card
Carrefour
Mundial Editora
Bradesco Consórcio
Cartões Renner (Realize CFI)
Avianca - Oceanair (DESATIVADA)
BrasilCard
Banrisul
Porto Seguro Cartões e Financiamentos
Copa Airlines
Fast Shop
Volkswagen
Itaú Consórcio
Sem Parar
Dell
Magazine Luiza - Loja Online
MRV Engenharia
Trigg
Itaú Seguros
Eudora
Odontoprev
Iberia Lineas Aereas
Zurich Seguros
Banco CBSS
Cartão de Todos
Zurich Minas Brasil Seguros
Extra 
Polishop.com.br
Mapfre Seguros
Sou barato
Loja Electrolux
Seguradora Líder dos Consórcios do Seguro DPVAT
Lojas Marisa
Leroy Merlin
Avianca - Voos internacionais
Bradesco Saúde
Bradesco Auto/RE
Positivo Informática
Faculdade Unopar
Lenovo Informática
Aliança Administradora 
Energisa Minas Gerais
Compra Certa
Alitalia
Qualicorp
Philips TV e Monitores
Azul Viagens
Universo Online - UOL
Cartão Atacadão
BB Seguro Auto
Credsystem
99App
Latam Travel
Cardif Seguros e Garantias
Itaú Unibanco Crédito Imobiliário
Banco Renner
Hipercard
BB Consórcios
Britânia
Banco Pan (Panamericano)
Tam
Kanui
Algar TV
Tricard
Air France
Philips Walita, Avent, Saeco e Sonicare
Agibank Financeira
Postos Shell
Banco Intermedium
Luizaseg
Consórcio Nacional Volkswagen
Loja Brastemp
Google
Polishop
American Airlines
Droga Raia
Passaredo Linhas Aéreas
Nestlé
Alpargatas
Lufthansa
Banco BS2
United Airlines
Asus
Livraria Cultura
Aeromexico
Aerolíneas Argentinas
99Food
Wine
Tricae
Sabemi Seguradora
AOC
Consórcio Embracon
PicPay
Monetizze
Faculdade Anhanguera
Beleza na Web
KLM
Drogasil
Avianca - Aerovias
Caixa Consórcios
Moip / Wirecard
HSBC
Zema Financeira
Editora Globo
Oster do Brasil
Portal Terra 
Consórcio Zema
Caixa Capitalização
Ipiranga
Financeira Itaú Americanas
Banco Volkswagen
Eletrosom
Assurant Seguradora
Bancoob
Itaú Unibanco Capitalização
Porto Seguro Cia de Seguros Gerais
Cartão Shoptime
Elo7
HDI Seguros
Camicado
BRB - Banco de Brasília
CDL Porto Alegre
Facta Financeira
Ricardo Eletro.com (DESATIVADA)
GA.MA Italy
Itaú Seguros Auto e Residência
Banco Semear
Época Cosméticos
Renault
Clear Corretora
SEMP TCL
Netflix
Girafa.com.br
Expedia.com.br
Panini
Aliança do Brasil
SulAmérica Saúde
Banco Renault/Credi Nissan
QuintoAndar
Aigle Azur
Enel Distribuição Rio (Ampla)
Ford
Nescafé Dolce Gusto
Citibank
Dacasa Financeira
Positivo Tecnologia
Sorocred 
Itapeva Recuperação de Créditos
SulAmérica Seguros de Pessoas e Previdência
Consórcio Fiat
Delta Air Lines
Bradesco Capitalização
HP Brasil
Pão de Açúcar 
British Airways
Caixa Vida e Previdência
Consórcio Luiza
Ingresso.com
Air Europa
Banco24Horas (TecBan)
Brasilprev Seguros e Previdência
Loja Consul
Banco do Nordeste
Cadence Eletrodomésticos
Lojas Riachuelo
Previsul
Moto Honda
Ingresso Rápido
Toyota
Ethiopian Airlines
Sympla
Lojas Colombo.com
Rede
Atlas Eletrodomésticos
GVT (DESATIVADA)
Zurich Santander Vida e Previdência
Philips Áudio e Vídeo
Caixa Previdência
Zurich Vida e Previdência
Esmaltec
Banco Honda
Caixa Seguros
Sicredi
Beautybox
Electrolux - Eletroportáteis
Tokio Marine
Portocred Financeira
Qatar Airways
Banco Yamaha
SulAmérica Auto, Residencial, Empresarial e Condomínio
Credz
Jequiti Cosméticos
Chevrolet
Hyundai Motor Brasil
Bradesco Seguros
Iplace
Gestora de Inteligência de Crédito
BV Leasing
Air Canada
Allianz Seguros
Black & Decker
Eventim Brasil
Zurich Santander Seguros
Royal Air Maroc
Hotmart
Atlântico Fundo de Investimento
ConectCar 
Rico Investimentos
XP Investimentos
Azul Seguros Cia de Seguros Gerais
Prudential do Brasil
Unimed Norte Nordeste
Purificador de Água Brastemp
Emirates
Enel Distribuição Goiás (CELG)
BB Seguros
Grão de Gente
Flytour Viagens
Marabraz - Lojas Físicas
Nespresso
Norwegian
SulAmérica Auto
Porto Seguro Consórcios
Liberty Seguros
Sky Airline
Multiplus (DESATIVADA)
Nissan
Bretas
Banco Digimais (antigo Banco Renner)
Enel Distribuição São Paulo (Eletropaulo)
Moip
Unimed Seguradora 
Icatu Seguros
Agiplan
Sompo Seguros
South African Airways
CCB Brasil Crédito, Financiamentos e Investimentos
Light
Semp - TCL - Toshiba
Santander Financiamentos
Banco Modal
Generali
Swiss
EL AL
Brasilseg (BB Seguros)
Banco Fiat
Magazine Luiza - Loja Física
Aliança do Brasil (BB Seguros)
Chubb Seguros
Turkish Airlines
Epson do Brasil
JetSMART Airlines
Consórcio Nacional Honda
Dia Supermercados
Novo Mundo
Honda Automóveis
Central Nacional Unimed
Latina Eletrodomésticos
Centrape – Central Nacional dos Aposentados e Pensionistas do Brasil
Consórcio Realiza
Itaú Vida e Previdência
Localiza Rent a Car
Brasilcap
Youse Seguradora
Capemisa Seguradora
CPFL Energia
Banco Toyota
quem disse, berenice?
BRBCard
Cartão Cencosud Bretas
Garantec
SuperMuffato.com
Santander Capitalização
Icatu Capitalização
BR Distribuidora (Petrobras)
Alfa Seguradora
Banco Alfa
Walmart
GEAP
Lojas Colombo
Compaq
Coelba
Gazin.com.br
Semp Toshiba
MAP Linhas Aéreas
Golden Cross
KitchenAid
Air China
Banco Cifra
Garoto
Sabemi Previdência Privada
Banco Ficsa
Enel Distribuição Ceará (Coelce)
Bemol
D-Link
Ultrafarma
Egali Intercâmbio
CEDAE
Seguros Sura
Fini - Loja Online
Centro Universitário FMU
Senff
Estadão (Jornal O Estado de S. Paulo)
Algar TV (DESATIVADA)
Netfarma
DME Distribuição
Mapfre Previdência
Panasonic
Latam Cargo
Axa Seguros
Abastece Aí - Km de Vantagens
BuscaPé
Universidade Anhembi Morumbi
TAAG - Linhas Aéreas de Angola
TRIGG
Metlife Seguros e Previdência Privada
Youcom
Banco Máxima
EDP Espírito Santo
Unicred
Sabesp
Guichê Virtual
Frigelar
Cardif Vida
Vult Cosmética
Elektro
Zurich Santander Seguro Auto
Dewalt
Energisa Sul-Sudeste 
Copanor
Banco PSA
Too Seguros (antiga PAN Seguros)
Dental Uni
Banco Sofisa
Just
QBE Brasil Seguros
Estrela Mineira 
Financeira Alfa
HS Financeira
MegaMamute
Ágora Investimentos
Mongeral Aegon Seguros e Previdência - MAG
Sam´s Club
TAP Air Portugal (DESATIVADA)
Mapfre Consórcios
Ultragaz
BIG
Copel Telecom
SulAmérica Odontológico
Herval Móveis e Colchões
Lexmark
Shopfato.com
Consórcio Primo Rossi ABC
Lojas TaQi
Mueller Fogões
Farfetch
Caixa Seguros Saúde
Celpe
DL Eletrônicos
Âncora Consórcios
Cabo Verde Airlines
MBM Previdência Complementar
Koin
Caixa Residencial 
Lenovo Celular (DESATIVADA)
Avianca (Vôos Internacionais)
Naturgy (antiga Gás Natural Fenosa)
Banco BS2 (Banco Bonsucesso)
CCE (Digibrás)
Parati Financeira
Malwee
Fortbrasil
Citibank (DESATIVADA - atual Itaú Unibanco)
Banco Rendimento
Dako
HSBC (DESATIVADO)
Boliviana de Aviación - BoA
Chilli Beans (DESATIVADA)
Consórcio Unilance
Unimed Seguros Saúde
Comprei Pontuei
Unimed Divinópolis
Studio Z
Banco Crefisa
Banestes
Mitsui Sumitomo Seguros
Oi Paggo Administradora de Crédito
Liderança Capitalização (Tele Sena)
Ticket360
Metlife Planos Odontológicos
Drogaria Onofre
AIG Seguros
Procorrer
CI Central de Intercâmbio Viagens
Fischer
Porto Seguro Capitalização
Águas de Pará de Minas
Energisa Mato Grosso
Telhanorte
Panvel Farmácias
Amazonas Energia
Palácio das Ferramentas
TACA Airlines
EDP São Paulo
Porto Seguro Saúde e Odonto
Allcare Administradora de Benefícios
3corações
Fiat Rivel - Blumenau, Brusque e Tijucas
Eurofarma
Comgás - Companhia de Gás de São Paulo
ParPerfeito
China Construction Bank (CCB Brasil)
The Beauty Box
Mapfre Vida
Lojas Avenida
Banco Bonsucesso
Faculdade Metropolitana de Ribeirão Preto
Tribanco
Dpaschoal
Evidence Previdência
Flybondi
Aqbank Pagamentos
Mercantil do Brasil Financeira
MBM Seguros
Afinz (Sorocred)
STB - Student Travel Bureau
CEMAR
Sicoob Seguradora
Consórcio Nacional Govesa
Energisa Tocantins
Gás Natural Fenosa
Unimed Uberlândia
Equatorial Pará (CELPA)
BancoSeguro
Livepass
Administradora de Consórcios Sicredi
Santander Auto
Docol Metais Sanitários
Agaxtur Viagens
Santana Financeira
Americanas Viagens
TIGRE 
Banco BTG Pactual
Creditas Soluções Financeiras
Benevix
Belfix
Nadir Figueiredo - Marinex - Copo Americano - SM - Duralex - Colorex - Sempre
Audi Center - Blumenau, Criciúma, Florianópolis, Joinville
Calçados Manuel
Amaszonas Línea Aérea
NotreDame Intermédica
Banco Cifra (DESATIVADA - atual Banco BMG)
EDE Editora e Distribuidora Educacional
Credicenm
Fiat Rivel - Blumenau, Brusque e Tijucas (DESATIVADA)
Sancor Seguros
Faculdade UNIME
Linca - Net Foz
Caboimagem TV e Internet Caraguá (DESATIVADA)
Valejet.com
Stanley
Sudaseg Seguradora
Azul Cargo
CPFL Paulista
Corretora de Seguros Carrefour
Crediare
Águas de Niterói
Energisa Rondônia (Ceron)
TAM Viagens
Unimed Fesp
Argo Seguros
Camil
GBOEX
Eletrobrás Distribuição Rondônia (Ceron)
Odonto Empresas
Iugu
Eletro Shopping
Mueller Eletrodomésticos
Credipar
Nextel (DESATIVADA - atual Claro)
Virginia Surety Seguros
Investprev Seguros e Previdência
Termolar
Banco Barigui
Asbapi - Associação Brasileira de Aposentados, Pensionistas e Idosos
Linea
Unimed Cascavel
Randon Administradora de Consórcios
HS Consórcios
Unimed Paulistana (DESATIVADA)
Agillitas
Lojas Lebes
Invest Seguradora
Rota Perdida
Unimed Odonto
Fundação Habitacional do Exército - FHE
Via Certa Financiadora
Grupo Editorial Beco dos Poetas & Escritores 
Banco Hyundai Capital Brasil
Hyundai Caoa
CEB Distribuição
Celesc
ASAAS
BCV
Purina
Consórcio Nacional Embracon
Editora Escala
 Aruana Seguradora
Fomento Paraná - Agência de Fomento do Paraná
Excelsior Seguros
Richards - Loja Online
Hiper Bompreço
Sanepar
Aspecir Previdência
Mars Brasil (Masterfoods)
Just (DESATIVADA)
Coop Cooperativa de Consumo
Finamax
Super do Povo
Bayer - Divisão Humana
Unimed Belém
RGE - Rio Grande Energia
Tam Cargo
Paulista Serviços
NBC Bank
Farmamed Drogaria
Travelmate Intercâmbio & Turismo
Prudential do Brasil Vida em Grupo
Unimed Paulistana
Aspecir Sociedade de Crédito
Bimbo do Brasil (Pullman, Plusvita, Ana Maria, Nutrella, Rap10, Crocantíssimo)
Gente Seguradora
Expresso Itamarati
QI Escolas
Lojas Quero-Quero
Fini
Equatorial Maranhão (CEMAR)
Cinemark
Cartão Caedu (Administradora de Cartão de Crédito Palma)
Conseg Consórcios
Unimed São José do Rio Preto
Yasuda Marítima Seguros
Roca
Poupex
Porto Seguro Previdência
XP Vida e Previdência
Banco Industrial do Brasil (BIB)
Senac - Santa Catarina
Unimed Assis
Virgin Atlantic Airways (DESATIVADA)
Hershey's
Lojas Becker
Zoom
Jocar.com.br
Artezanal
Net Angra
Vip Telecom
Drogal
Modal Mais
Aigle Azur (DESATIVADA)
Móveis Romera
Previmil Vida e Previdência
Hospital de Olhos Santa Luzia - Recife/PE 
mony mony
Caboimagem TV e Internet Ubatuba (DESATIVADA)
City Lar
SJ Administração de Imóveis - Ceará
Banese - Banco do Estado de Sergipe
Caboimagem TV e Internet Caraguá
SAAE Sorocaba
Unimed Maceió
Deville Hotéis
Banco da Amazônia
Águas do Paraíba
Faculdade Unic
Associação Comercial de Sorocaba 
Consórcio Breitkopf
Faculdade FAMA
Banco Alfa de Investimento
Zurich Capitalização
Embasa
Copel - Companhia Paranaense de Energia
Ibyte
OvelhaNegraMusical.com.br
UP Promotora
Lojas MM - Mercadomóveis
STB Travel Shop
Comprev Vida e Previdência
Ampla
Equatorial Piauí
Banpará
Single Care
Energisa Acre (Eletroacre)
Banco Paulista
Unimed Grande Florianópolis
Atacadão
Cosern
Becker Financeira
Bayer - Divisão Animal
Sorriso Operadora Odontológica
Agemed Planos de Saúde
Cartão Quero-Quero VerdeCard
American Life Seguros
Banco Neon (DESATIVADA)
Santher
Stix
Wickbold
Gontijo
Contabilista Papelaria e Informática
Banco Neon
Brisanet Telecom
AL5 Bank
Alfa Previdência e Vida

**Comment by yohangumiel** [comment]
[reclameAqui_companies (1).csv](https://github.com/MPMG-DCC-UFMG/C01/files/8234296/reclameAqui_companies.1.csv)

**Comment by caiocvsilva** [comment]
@yohangumiel os dados ainda estão sendo coletados, mas já podem ser pré-visualizados. O coletor teve que ser divido em diversas partes para que não houvesse uma sobrecarga no sistema. Os dados estão sendo salvos em '/datalake/ufmg/webcrawlerc01/reclameaqui/'. Está pasta irá conter todas as partes necessárias do coletor.

**Comment by caiocvsilva** [comment]
O site ReclameAqui foi coletado, com as empresas desejadas. Entretanto, por uma questão do servidor do site, as páginas começaram a ter uma alta demora na resposta para o coletor o que ocasionou no travamento dos mesmos. Como uma coleta inicial, acredito que tenha sido o suficiente, mas essa coleta pode ser refeita no futuro se houver uma melhor resposta dos servidores do ReclameAqui.  Os dados foram salvos em '/datalake/ufmg/webcrawlerc01/reclameaqui/'.
