### ISSUE TITLE
Bug na interface do mecanismo de passos

### ISSUE THREAD

**Issue by matheusfebarbosa** [MPMG-DCC-UFMG/C01#848]
## Comportamento Esperado

Os botões de manipulação de passos (escolher passo, mover, excluir, etc) devem funcionar sem interferência nos outros passos.

## Comportamento Atual

Foi encontrado um bug na versão atual em que ao excluir (e as vezes modificar) um passo do lado de fora de um grupo [abrir em nova aba, fechar aba], os passos no interior do grupo são modificados. O comportamento mais comum é o que o passo simplesmente some, inclusive da lista de passos selecionáveis (vide prints abaixo).

## Passos para reproduzir o erro

- Importar [esta](https://drive.google.com/file/d/1bQU9z1gjOHWdB1-J1G2FnTOMGSM0K8g0/view?usp=sharing) configuração
- Ir na seção de coleta dinâmica e modificar os passos no interior da estrutura de Para Cada (experimente excluir o passo de screenshot)

## Screenshots (caso necessário)

**Antes de remover o passo de screenshot**
![antes](https://user-images.githubusercontent.com/28073797/139126861-2196e4d7-193b-4c3a-b14e-e378f99e4e49.png)
**Após remover**
![depois](https://user-images.githubusercontent.com/28073797/139126871-59d04e10-b913-4c75-9775-05c5552fa8c5.png)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/848?planning-poker) with ZenHub @caiocvsilva @elvesrodrigues @matheusfebarbosa
