### ISSUE TITLE
Tratamento para URLs com espaço

### ISSUE THREAD

**Issue by elvesrodrigues** [MPMG-DCC-UFMG/C01#872]
## Comportamento Esperado

Queremos que o sistema colete todos os dados especificados para ele coletar, porém, algumas URLs possuem espaços, como `http://www.uberaba.mg.gov.br/portal/acervo//portal_transparencia/arquivos/2018/prestacao_contas/Anexo IV - Demonstrativo das Receitas e Despesas com Acoes e Servicos Publicos de Saude.pdf` que acabem sendo vistas com inválidas pelo filtro de "URLs quebradas". 

## Comportamento Atual

URLs com espaço não recebem tratamento, de modo que são vistas como inválidas e, portanto, não são coletadas.

## Passos para reproduzir o erro

1. Configure uma coleta estática para o site: http://www.uberaba.mg.gov.br/portal/conteudo,36761
2. Habilite download de arquivos.
3. Note as URLs dos arquivos são barradas por serem vistas com inválidas pelo filtro de "URLs quebradas".

## Sistema

O problema foi identificado na branch `distributed-system`, mas acredita-se que ele seja válido para todas outras branches.

**Comment by elvesrodrigues** [comment]
Essa issue será arquivada pois ela se mostrou desnecessária após testes (o problema era outro).

**Comment by rennancordeiro** [comment]
Fechada devido arquivamento documentado acima.
