### ISSUE TITLE
Correção da exceção: '_UnixSelectorEventLoop' object has no attribute '_closed' em coletas dinâmicas

### ISSUE THREAD

**Issue by elvesmrodrigues** [MPMG-DCC-UFMG/C01#873]
## Comportamento Esperado

O sistema deve executar sem nenhum tipo de exceção, porém, como apontado na descrição da issue #782, em algumas coletas essa exceção é gerada. Embora seja ignorada pelo sistema.

## Comportamento atual

A exceção citada ocorre em algumas coletas, conforme apontado na issue #782.

## Passos para reproduzir o erro

Instancie uma das coletas apontadas na issue #782 onde ocorre essa exceção na solução distribuída.

## Sistema

Branch `distributed-system`.

**Comment by lucasaug** [comment]
Acho que vale colocar essa issue dentro de alguma Epic!

**Comment by louisaturn** [comment]
Não houve nenhum problema de timeout e todas as 7 páginas foram coletadas. Acreditamos que isso seja um erro que deixou de existir na transição do Pyppeteer para o Playwright.
