### ISSUE TITLE
Execução do coletor dinâmico em modo headful

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#886]
## Comportamento Esperado
É desejável que seja possível executar o coletor dinâmico em modo "headful", onde o sistema abra uma janela do navegador para o usuário e execute os passos nessa janela.

## Comportamento Atual
Esse mecanismo não existe no sistema.

## Passos para reproduzir o erro
Não aplicável.

## Especificações da Coleta
Não aplicável.

**Comment by lucasaug** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/886?planning-poker) with ZenHub @louisaturn @matheusfebarbosa @rennancordeiro

**Comment by louisaturn** [comment]
Percebemos que a implantação da ferramenta de debug _post-mortem_ "Trace Viewer" (Playwright) pode ser mais eficaz do que execução em modo headfull. Por isso, resolvemos por fechar essa issue e criar uma nova nesse sentido.
