### ISSUE TITLE
Erro ao coletar dados de transparência de Betim no sistema distribuído

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#894]
## Comportamento Esperado
As coletas devem funcionar igualmente na master e no sistema distribuído.

## Comportamento Atual
Ao executar a coleta em questão na branch `distributed-system`, a barra de progresso indica quatro páginas a coletar, mas apenas uma é coletada. O coletor fica ocioso por algum tempo e encerra, e a página coletada apresenta um erro HTTP 500. Na master, várias páginas são coletadas, e essa primeira página não apresenta o erro 500.

## Passos para reproduzir o erro

  1. Importar o coletor anexado
  2. Iniciar a coleta
  3. Observar que apenas um arquivo é coletado
  4. Abrir arquivo coletado e observar que é uma página de erro HTTP 500

## Especificações da Coleta

O [arquivo de configuração](https://drive.google.com/file/d/1yB16vK_kyVU3y_tLtXKOFgJNHsIoZqjc/view) pode ser usado para importar a coleta especificada.

## Sistema

  - MP ou local: local
  - Branch específica: distributed-system

**Comment by lucasaug** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/894?planning-poker) with ZenHub @elvesrodrigues @rennancordeiro

**Comment by elvesrodrigues** [comment]
@pep8speaks pep8ify
