### ISSUE TITLE
Tratamento da exceção `[...] Future <Future pending> attached to a different loop` em coletas dinâmicas

### ISSUE THREAD

**Issue by elvesmrodrigues** [MPMG-DCC-UFMG/C01#895]
## Comportamento esperado

Exceções devem ocorrer raramente, porém, essa sempre ocorre ao realizar coletas dinâmicas. Indicando um possível ponto de melhoria para evitar que o erro ocorra com tanta frequência.

## Comportamento atual

A exceção é sempre gerada ao executar coletas dinâmicas.

## Passos para reproduzir o erro

Reproduzir os passos da issue #843 que permitiu descobrir o erro.

Notar que essa exceção é sempre gerada pelo método `_parse_request` do módulo `scrapy_puppeteer/middleware.py` ao executar o comando `page = await self.browser.newPage()`.

## Sistema

Branch `master`.

**Comment by elvesrodrigues** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/895?planning-poker) with ZenHub @lucasaug @rennancordeiro

**Comment by louisaturn** [comment]
Esta issue é dada como concluída, pois não conseguimos reproduzir o erro, nem no coletor de exemplo, nem nos [coletores de teste da versão distribuída](https://docs.google.com/spreadsheets/d/1Id0AB9LWtvJEN1lEBhqV89nXKoYTSoFMrjQiok25ukU/edit#gid=0).
