### ISSUE TITLE
Seleção: Desenvolver mecanismos para submissão de formulários e processamento assíncrono de resultados via Javascript

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C01#9]
Mecanismos para lidar com casos onde a submissão do formulário, paginação e detalhamento de informações ocorre de maneira assíncrona, ou seja, usando AJAX.

**Comment by TalesPanoutsos** [comment]
Essa issue foi arquivada pois estáva duplicada com a #150 (mecanismo de step by step) e todas as issue relacionadas a essa.
