### ISSUE TITLE
Coleta de dados das licitações do portal de transparência de Uberlândia/MG

### ISSUE THREAD

**Issue by miabrandao** [MPMG-DCC-UFMG/C01#912]
## Comportamento Esperado
Requisição de nova coleta dos documentos e arquivos relacionados aos processos licitatórios do município de Uberlândia/MG. É esperado que a coleta contenha os HTML das páginas coletadas e os arquivos em si, como já existe hoje para outros municípios nos arquivos dos diretório `data/raw_pages` e `data/files`, respectivamente. Também precisamos do arquivo file_description.jsonl corretamente preenchido.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da fonte
Os processos licitatórios da cidade de Uberlândia são obtidos a partir da página a seguir:
https://www.uberlandia.mg.gov.br/portal-da-transparencia/licitacoes-e-contratos/

## Detalhes da trilha
Os dados aqui solicitados são de interesse da trilha M03, sob coordenação de Pedro Brum (pedrovaladares.pvb@gmail.com ).

## Screenshots e links (caso necessário)
 Não se aplica.

**Comment by rennancordeiro** [comment]
Olá @miabrandao, pode verificar essa outra issue https://github.com/MPMG-DCC-UFMG/C01/issues/538 por favor? Acredito que esta está duplicada.

**Comment by miabrandao** [comment]
Olá @rennancordeiro, boa tarde! Ao olhar a issue #538, parece que o site para coleta da cidade de  Uberlândia apresenta algumas dificuldades. Acha que será possível a coleta desta cidade? Posso fechar essa issue e acompanhar pela outra. Abs, Michele
