### ISSUE TITLE
Investigar possível condição de corrida ao iniciar spiders

### ISSUE THREAD

**Issue by elvesrodrigues** [MPMG-DCC-UFMG/C01#922]
## Comportamento esperado

Desejamos ter a garantia que a execução de que todos módulos ocorram corretamente.

## Comportamento atual

Foi identificado por @lucasaug uma possível condição de corrida no módulo `spider_manager` no momento da criação de seus spiders. Onde o arquivo base de configuração deles é alterado dinamicamente para cada novo spider, potencialmente gerando condições de corrida. 

## Passos para reproduzir o erro

Não se aplica.

## Sistema

Branch `distributed-system`;

**Comment by elvesrodrigues** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/922?planning-poker) with ZenHub @lucasaug @rennancordeiro

**Comment by elvesrodrigues** [comment]
Oi, @lucasaug!  Como foi sua ideia a criação dessa issue, acho que seria interessante que a gente discutisse ela aqui.

Se me lembro bem, seu ponto foi que a reescrita desse arquivo [settings.py](https://github.com/MPMG-DCC-UFMG/C01/blob/distributed-system/spider_manager/src/settings.py) dinamicamente nesse [trecho de código](https://github.com/MPMG-DCC-UFMG/C01/blob/1960612932cd894202984fb97d650e14db9b90ee/spider_manager/src/executor.py#L84-L91) de acordo com cada coletor poderia gerar uma condição de corrida pois esse arquivo é lido no momento de criação de cada `spider`. 

Pelo menos na versão do Scrapy usada no Scrapy-Cluster, `1.5.0`, dá a entender que o (1) arquivo é lido somente uma vez. Segui esses passos:

a)  As configurações são obtidas por meio de `from scrapy.conf import setting`.
b) A variável importada é definida [aqui](https://github.com/scrapy/scrapy/blob/71ba1ffeab4cc38c819a1e3237034169c76a6e04/scrapy/conf.py#L8). Chamando o método `get_project_settings()`, definido [aqui](https://github.com/scrapy/scrapy/blob/71ba1ffeab4cc38c819a1e3237034169c76a6e04/scrapy/utils/project.py#L60).
c) Pelo código de `get_project_settings()`, ele executa a leitura do arquivo de configuração e retorna uma instância de `Settings`.

(2) Se pegarmos tanto o `PID` da [engine](https://github.com/scrapy/scrapy/blob/1.5/scrapy/core/engine.py) do `Scrapy`, que, no meu entender, é onde tudo começa, e se também pegarmos o `PID` do [scheduler](https://github.com/MPMG-DCC-UFMG/C01/blob/distributed-system/spider_manager/src/crawling/distributed_scheduler.py) do `Scrapy-Cluster`, podemos notar que cada `spider` iniciado possui esses recursos exclusivos. Ou seja, aparentemente, não há compartilhamento de recursos/espaço de memória entre processos executando uma `spider` e outra.

Além disso, considerando que (3) o comando de criação de `spiders` é processado sequencialmente pelo `spider_manager` e que (4) há somente uma instância de `spider_manager` executando em um mesmo `container`, tudo isso me faz pensar que nessas condições (e é a que o sistema foi projetado), não haveria condições de corrida, uma vez que uma vez que um spider é iniciado, o arquivo de configuração `settings.py` é lido uma única vez para ele e os dados ficam na memória reservada do processo que está executando o spider.

Mas posso estar errado. O que acha?

**Comment by lucasaug** [comment]
Olá @elvesrodrigues. Acho que agora entendi melhor, eu pensei que a criação de uma spider pelo `spider_manager` era feita de forma assíncrona, e portanto poderíamos ter duas execuções no mesmo container tentando criar duas spiders diferentes ao mesmo tempo. Acredito que a questão (2) não influencie tanto, porque tendo PIDs diferentes, os processos a princípio não compartilhariam memória RAM, mas o sistema de arquivos ainda seria o mesmo. Mas pra mim a questão que não estava clara é o ponto (3). Então só pra confirmar: quando o comando de iniciar uma spider é recebido, todo o processamento é feito de forma síncrona, desde a escrita do arquivo `settings.py` até sua leitura em outro processo e retorno do procedimento de volta para a espera de nova mensagem do Kafka? Novas requisições de criação de spider ficam aguardando até o fim desse procedimento, não sendo processadas em paralelo?
Porque se for isso mesmo, estou de acordo, acredito que a condição de corrida que eu pensei não existe! Lendo o código aqui, a única possibilidade problemática que pensei seria se a thread principal processar duas criações de spider em sequência: caso a thread da primeira spider demore a fazer a leitura do `settings.py`, e antes que isso aconteça a thread principal escreva o `settings.py` da próxima spider. Faz sentido? Se fizer acho que pode ficar como uma issue de aprimoramento, pois é um caso mais específico.

**Comment by elvesrodrigues** [comment]
Oi, Lucas! Sobre sua primeira pergunta, estou me baseando [nesse trecho](https://github.com/MPMG-DCC-UFMG/C01/blob/1960612932cd894202984fb97d650e14db9b90ee/spider_manager/src/command_listener.py#L53-L61) para dizer que as o processamento é síncrono. O `spider manager` obtêm escala ao iniciar novos containers. E cada container executa uma única instância de `spider manager`.

Entendi seu ponto sobre as threads. E realmente faz sentido sua preocupação e acredito que ela possa sim ocorrer. 

Uma possível solução seria garantir que o comando de criação de threads (subprocessos) só retorne após garantir que a thread/subprocesso tenha sido iniciado. 

O que acha?

**Comment by lucasaug** [comment]
Oi Elves, concordo! Só tem que ficar claro que pro nosso contexto a definição de "subprocesso ter sido iniciado" significa que o arquivo `settings.py` já foi lido e não será lido novamente. Admito que não tenho muita ideia de como isso pode ser feito, mas acho que podemos ter uma issue separada para investigar exatamente como fazer.

**Comment by elvesrodrigues** [comment]
Concordo. Você pode criar a issue?

**Comment by lucasaug** [comment]
Claro, criei a issue #998 para esse problema. Se tiver alguma sugestão de alteração na descrição, fique a vontade para fazer.
Como essa investigação inicial, ao meu ver, está finalizada, e criamos uma issue nova para a resolução concreta do problema, estou fechando essa issue. Caso achem que há mais discussões a serem feitas, podemos reabrir.
