### ISSUE TITLE
Disparidade entre número de requisições e páginas salvas e screenshots

### ISSUE THREAD

**Issue by isabel-elise** [MPMG-DCC-UFMG/C01#931]
## Comportamento Esperado

Salvar cada uma das páginas visitadas pelo coletor, como indicado nos screenshots e com isso obter uma quantidade semelhante de páginas salvas e screenshots.

No caso em específico referente à issue #885, a coleta foi feita a partir desta URL: https://www.varginha.mg.gov.br/portal/editais/1. Para cada opção no select ao final da página, o coletor deveria clicar em cada item, o que abre uma nova página com os links para download dos detalhes de cada licitação. Por isso há dois loops: Um que itera sobre as opções do select e outro que itera sobre cada caixinha da página. Os screenshots deveriam registrar cada página do select e, para cada uma dessas, cada página relativa a uma caixinha de item em particular.

## Comportamento Atual

No caso em específico da coleta #885, o coletor deveria visitar cerca de 1997 páginas. No entanto, em algum momento ocorreu um erro de conexão que parou a coleta. Os Screenshots mostram apenas perto de 1200 páginas e na pasta raw_pages aparecem somente 437 arquivos html. 

## Passos para reproduzir o erro

#885 é um exemplo de coleta cujo número de páginas salvas não se aproxima do número de screenshots.

1. Importar a configuração abaixo (e trocar o save path)
2. Executar
3. Observar o número de screenshots
4. Observar o número de arquivos html na raw_pages

## Especificações da Coleta

Configuração de exemplo da coleta #885:

```json
{
  "source_name": "[Realiza\u00e7\u00e3o-F01] Coleta de licita\u00e7\u00f5es de Varginha",
  "base_url": "https://www.varginha.mg.gov.br/portal/editais/1",
  "obey_robots": false,
  "data_path": "/datalake/ufmg/webcrawlerc01/realizacaof01/varginha/licitacao",
  "request_type": "GET",
  "form_request_type": "POST",
  "antiblock_download_delay": 2,
  "antiblock_autothrottle_enabled": false,
  "antiblock_autothrottle_start_delay": 2,
  "antiblock_autothrottle_max_delay": 10,
  "antiblock_ip_rotation_enabled": false,
  "antiblock_ip_rotation_type": "tor",
  "antiblock_max_reqs_per_ip": 10,
  "antiblock_max_reuse_rounds": 10,
  "antiblock_proxy_list": "",
  "antiblock_user_agent_rotation_enabled": false,
  "antiblock_reqs_per_user_agent": 100,
  "antiblock_user_agents_list": "",
  "antiblock_insert_cookies_enabled": false,
  "antiblock_cookies_list": "",
  "captcha": "none",
  "has_webdriver": false,
  "webdriver_path": "",
  "img_xpath": "",
  "sound_xpath": "",
  "dynamic_processing": true,
  "explore_links": false,
  "link_extractor_max_depth": null,
  "link_extractor_allow_url": "",
  "link_extractor_allow_domains": "",
  "link_extractor_tags": "",
  "link_extractor_attrs": "",
  "link_extractor_check_type": false,
  "link_extractor_process_value": "",
  "download_files": true,
  "download_files_allow_url": "",
  "download_files_allow_extensions": "",
  "download_files_allow_domains": "",
  "download_files_tags": "",
  "download_files_attrs": "",
  "download_files_process_value": "",
  "download_files_check_large_content": true,
  "download_imgs": false,
  "steps": "{\"step\":\"root\",\"depth\":0,\"children\":[{\"step\":\"espere\",\"depth\":1,\"arguments\":{\"segundos\":\"10\"}},{\"step\":\"salva_pagina\",\"depth\":1,\"arguments\":{}},{\"step\":\"espere\",\"depth\":1,\"arguments\":{\"segundos\":\"5\"}},{\"step\":\"para_cada\",\"depth\":1,\"iterator\":\"pagina\",\"children\":[{\"step\":\"selecione\",\"depth\":2,\"arguments\":{\"xpath\":\"\\\"/html/body/div[2]/div/div/div[3]/div[5]/div/select\\\"\",\"opcao\":\"pagina\"}},{\"step\":\"espere\",\"depth\":2,\"arguments\":{\"segundos\":\"2\"}},{\"step\":\"screenshot\",\"depth\":2,\"arguments\":{}},{\"step\":\"para_cada\",\"depth\":2,\"iterator\":\"link\",\"children\":[{\"step\":\"espere\",\"depth\":3,\"arguments\":{\"segundos\":\"5\"}},{\"step\":\"clique\",\"depth\":3,\"arguments\":{\"elemento\":\"link\"}},{\"step\":\"espere\",\"depth\":3,\"arguments\":{\"segundos\":\"5\"}},{\"step\":\"screenshot\",\"depth\":3,\"arguments\":{}},{\"step\":\"espere\",\"depth\":3,\"arguments\":{\"segundos\":\"5\"}},{\"step\":\"salva_pagina\",\"depth\":3,\"arguments\":{}},{\"step\":\"espere\",\"depth\":3,\"arguments\":{\"segundos\":\"5\"}},{\"step\":\"retorna_pagina\",\"depth\":3,\"arguments\":{}}],\"iterable\":{\"call\":{\"step\":\"localiza_elementos\",\"arguments\":{\"xpath\":\"\\\"/html/body/div[2]/div/div/div[3]/div[4]/div[*]/a/div/div[1]\\\"\"}}}}],\"iterable\":{\"call\":{\"step\":\"opcoes\",\"arguments\":{\"xpath\":\"\\\"/html/body/div[2]/div/div/div[3]/div[5]/div/select\\\"\"}}}}]}",
  "encoding_detection_method": 1,
  "templated_url_parameter_handlers": [],
  "static_form_parameter_handlers": [],
  "templated_url_response_handlers": [],
  "static_form_response_handlers": [],
  "crawler_id": 193,
  "instance_id": "16365838991375"
}`
```

## Screenshots

![issue_nova_0.png](https://images.zenhubusercontent.com/6164879d09cd97647a92c1ce/a02b2df1-2c2e-44e7-aa08-dab1cacd3081)

![issue_nova_1.png](https://images.zenhubusercontent.com/6164879d09cd97647a92c1ce/9fa232aa-e28b-4997-801d-c247ad7f3642)

![issue_nova_2.png](https://images.zenhubusercontent.com/6164879d09cd97647a92c1ce/1f72f337-dd20-43e7-9bf0-5f2ab47a7cc6)

![issue_nova_3.png](https://images.zenhubusercontent.com/6164879d09cd97647a92c1ce/069afa2e-2e0b-4c65-864b-e12b0b38722b)

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/931?planning-poker) with ZenHub @aluiza22 @caiocvsilva

**Comment by caiocvsilva** [comment]
@isabel-elise este erro continua acontecendo ou você conseguiu concluir a coleta? Eu tentei executar a sua coleta, mas percebi que a mesma apresenta problemas, possivelmente por uma atualização na estrutura da página. Você poderia atualizar a configuração da coleta, caso o erro ainda aconteça?

**Comment by caiocvsilva** [comment]
@isabel-elise, como todos os bugs desta issue não puderam ser devidamente recriados, e não houve uma resposta se o problema continua acontecendo com seu coletor, iremos fechá-la. Caso o problema ainda persista, favor nos contactar com mais informações, para reabrirmos.
