### ISSUE TITLE
Coleta de Licitações de Belo Horizonte

### ISSUE THREAD

**Issue by isabel-elise** [MPMG-DCC-UFMG/C01#939]
## Comportamento Esperado
Requisição da extração de html e arquivos disponíveis com informações a respeito de licitações de Belo Horizonte.

## Comportamento Atual
Não se aplica.

## Localização
Não se aplica.

## Detalhes da Fonte
Os dados a serem extraídos podem ser encontrados no portal de transparência da prefeitura de Belo Horizonte no link https://prefeitura.pbh.gov.br/licitacoes).

## Detalhes da Trilha
Os dados aqui solicitados são de interesse da trilha F01, sob coordenação de Rodrygo Santos (rodrygo@gmail.com).

## Screenshots e Links
Não se aplica.

**Comment by miabrandao** [comment]
Olá, bom dia!! Nós analisamos os documentos de licitação coletados para cidade de Belo Horizonte e há apenas 252 documentos. Entretanto, alguns são escaneados, após removê-los, ficamos com 192 documentos. Houve algum problema na coleta? Por BH ser capital, imaginávamos que teriam mais documentos e mais diversos. Podem verificar, por favor? Abs, Michele

**Comment by isabel-elise** [comment]
Olá! Boa tarde! Realmente, apenas uma pequena parte dos dados da página foi coletada! Estou refazendo o coletor para corrigir esse problema!

**Comment by isabel-elise** [comment]
> Olá, bom dia!! Nós analisamos os documentos de licitação coletados para cidade de Belo Horizonte e há apenas 252 documentos. Entretanto, alguns são escaneados, após removê-los, ficamos com 192 documentos. Houve algum problema na coleta? Por BH ser capital, imaginávamos que teriam mais documentos e mais diversos. Podem verificar, por favor? Abs, Michele

Olá! Boa tarde! Realmente, apenas uma pequena parte dos dados da página foi coletada! Estou refazendo o coletor para corrigir esse problema!

**Comment by isabel-elise** [comment]
> Olá, bom dia!! Nós analisamos os documentos de licitação coletados para cidade de Belo Horizonte e há apenas 252 documentos. Entretanto, alguns são escaneados, após removê-los, ficamos com 192 documentos. Houve algum problema na coleta? Por BH ser capital, imaginávamos que teriam mais documentos e mais diversos. Podem verificar, por favor? Abs, Michele

Boa noite! Conferi os dados coletados e a quantidade de arquivos baixados passa dos 3000, sendo a maioria em formato pdf. Eles se encontram no caminho em  realizacaof01/belo_horizonte/licitacao/data/files.

**Comment by miabrandao** [comment]
Olá @isabel-elise, eu olhei o diretório "/datalake/ufmg/crawler/crawler/webcrawlerc01/realizacaof01", mas há apenas o município itacarambi. É esse diretório mesmo?

**Comment by isabel-elise** [comment]
> Olá @isabel-elise, eu olhei o diretório "/datalake/ufmg/crawler/crawler/webcrawlerc01/realizacaof01", mas há apenas o município itacarambi. É esse diretório mesmo?

Bom dia, @miabrandao! O caminho dos arquivos baixados dessa coleta foi especificado como `/datalake/ufmg/webcrawlerc01/realizacaof01/belo_horizonte/licitacao/data/files` no coletor! Acessando pela F01, podemos chegar ao mesmo caminho com `/datalake/ufmg/crawler/webcrawlerc01/realizacaof01/belo_horizonte/licitacao/data/files`.

**Comment by isabel-elise** [comment]
O

> Olá @isabel-elise, eu olhei o diretório "/datalake/ufmg/crawler/crawler/webcrawlerc01/realizacaof01", mas há apenas o município itacarambi. É esse diretório mesmo?

Bom dia, @miabrandao! Enviei uma resposta por meio do Discord!

**Comment by isabel-elise** [comment]
> Olá @isabel-elise, eu olhei o diretório "/datalake/ufmg/crawler/crawler/webcrawlerc01/realizacaof01", mas há apenas o município itacarambi. É esse diretório mesmo?

Bom dia, @miabrandao! Enviei uma resposta por meio do Discord!

**Comment by miabrandao** [comment]
Obrigada!
