### ISSUE TITLE
Adição de suporte a coletas por API

### ISSUE THREAD

**Issue by rennancordeiro** [MPMG-DCC-UFMG/C01#982]
## Comportamento Esperado
Desejamos uma nova funcionalidade na plataforma, o suporte a requisições a API. Essa funcionalidade deve permitir ao usuário preencher os parâmetros desejados e controlar as requisições através de uma configuração de coletor, da mesma maneira que as outras funcionalidades estão integradas. Para isso, é necessária uma investigação e avaliação inicial da melhor maneira de implementar esse módulo (com validação pelo resto da equipe). É possível que ele aproveite o que já foi desenvolvido em outras partes da plataforma, como os spiders e a geração de parâmetros e requisições. Essa é uma issue inicial e foca na exploração das possibilidade e no desenvolvimento de uma solução inicial, por conta disso, caso seja necessário, outras issues podem ser abertas para incluir especificidades e questões que são descobertas no processo natural de desenvolvimento.

## Comportamento Atual
Não temos suporte a coletas por API

## Passos para reproduzir o erro
Não se aplica

## Especificações da Coleta
Não se aplica
  

## Sistema (caso necessário)
Não se aplica

## Screenshots (caso necessário)
Não se aplica

**Comment by rennancordeiro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Coletas-615f2ad8da8aaa0014e7affb/issues/MPMG-DCC-UFMG/C01/982?planning-poker) with ZenHub @elvesrodrigues @lucasaug

**Comment by lucasaug** [comment]
Olá @rennancordeiro. Se a funcionalidade é o que estou pensando, já temos uma API prototipal no sistema. Tem um bom tempo que ela não é utilizada, e portanto está bem desatualizada, mas quem pegar essa tarefa pode avaliar o quanto é possível reaproveitar a API existente ou se é melhor começar do zero.

**Comment by lucasaug** [comment]
As APIs solicitadas podem ser coletadas utilizando apenas requisições GET. A inserção de parâmetros é feita na própria URL, portanto o gerador de URL parametrizada, que já está implementado, resolve esse caso. Não identificamos até o momento nenhuma API de interesse cuja coleta necessite de requisições POST. Dessa forma, o sistema atual é capaz de coletar as APIs.

Segue uma configuração a título de exemplo, referente aos dados de licitação de Manhuaçu no período de 2015 a 2020.

```
{
  "source_name": "Manhua\u00e7u",
  "base_url": "https://manhuacu-mg.portaltp.com.br/api/transparencia.asmx/json_licitacoes?ano={}&mes={}",
  "obey_robots": false,
  "data_path": "<preencher>",
  "request_type": "GET",
  "form_request_type": "POST",
  "antiblock_download_delay": 2,
  "antiblock_autothrottle_enabled": false,
  "antiblock_autothrottle_start_delay": 2,
  "antiblock_autothrottle_max_delay": 10,
  "antiblock_ip_rotation_enabled": false,
  "antiblock_ip_rotation_type": "tor",
  "antiblock_max_reqs_per_ip": 10,
  "antiblock_max_reuse_rounds": 10,
  "antiblock_proxy_list": "",
  "antiblock_user_agent_rotation_enabled": true,
  "antiblock_reqs_per_user_agent": 100,
  "antiblock_user_agents_list": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246",
  "antiblock_insert_cookies_enabled": false,
  "antiblock_cookies_list": "",
  "captcha": "none",
  "has_webdriver": false,
  "webdriver_path": "",
  "img_xpath": "",
  "sound_xpath": "",
  "dynamic_processing": false,
  "explore_links": false,
  "link_extractor_max_depth": null,
  "link_extractor_allow_url": "",
  "link_extractor_allow_domains": "",
  "link_extractor_tags": "",
  "link_extractor_attrs": "",
  "link_extractor_check_type": false,
  "link_extractor_process_value": "",
  "download_files": false,
  "download_files_allow_url": "",
  "download_files_allow_extensions": "",
  "download_files_allow_domains": "",
  "download_files_tags": "",
  "download_files_attrs": "",
  "download_files_process_value": "",
  "download_files_check_large_content": true,
  "download_imgs": false,
  "steps": "",
  "encoding_detection_method": 1,
  "templated_url_parameter_handlers": [
    {
      "injection_type": "templated_url",
      "parameter_key": "",
      "parameter_label": "",
      "filter_range": false,
      "cons_misses": 100,
      "parameter_type": "number_seq",
      "first_year_proc_param": null,
      "last_year_proc_param": null,
      "segment_ids_proc_param": "",
      "court_ids_proc_param": "",
      "origin_ids_proc_param": "",
      "first_num_param": 2015,
      "last_num_param": 2020,
      "step_num_param": 1,
      "leading_num_param": false,
      "length_alpha_param": null,
      "num_words_alpha_param": null,
      "no_upper_alpha_param": false,
      "date_format_date_param": "",
      "start_date_date_param": null,
      "end_date_date_param": null,
      "frequency_date_param": "D",
      "value_const_param": "",
      "value_list_param": ""
    },
    {
      "injection_type": "templated_url",
      "parameter_key": "",
      "parameter_label": "",
      "filter_range": false,
      "cons_misses": 100,
      "parameter_type": "number_seq",
      "first_year_proc_param": null,
      "last_year_proc_param": null,
      "segment_ids_proc_param": "",
      "court_ids_proc_param": "",
      "origin_ids_proc_param": "",
      "first_num_param": 1,
      "last_num_param": 12,
      "step_num_param": 1,
      "leading_num_param": false,
      "length_alpha_param": null,
      "num_words_alpha_param": null,
      "no_upper_alpha_param": false,
      "date_format_date_param": "",
      "start_date_date_param": null,
      "end_date_date_param": null,
      "frequency_date_param": "D",
      "value_const_param": "",
      "value_list_param": ""
    }
  ],
  "static_form_parameter_handlers": [],
  "templated_url_response_handlers": [],
  "static_form_response_handlers": [],
  "crawler_id": 28,
  "instance_id": "164486734417480"
}
```
