### ISSUE TITLE
Erro ao executar coleta de Leis Orçamentárias de Uberaba

### ISSUE THREAD

**Issue by lucasaug** [MPMG-DCC-UFMG/C01#996]
## Comportamento Esperado
As coletas no sistema distribuído devem funcionar da mesma maneira que na master.

## Comportamento Atual
Ao executar a coleta indicada, nenhuma página é salva, e nem os screenshots.

## Passos para reproduzir o erro

  1. Importar a configuração [leis_orcamentarias_uberaba.json](https://drive.google.com/file/d/12fk1CxDA3-NvAnou7LfP42iXof6Zf7r6/view)
  2. Executar a coleta
  3. Observar que nenhuma página ou screenshot foram salvos.

## Especificações da Coleta
Conforme arquivo de configuração.  

## Sistema
Branch `distributed-system`.

**Comment by lucasaug** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/C01---Desenvolvimento-61649e0e5cf22f00120ceee2/issues/MPMG-DCC-UFMG/C01/996?planning-poker) with ZenHub @elvesrodrigues @rennancordeiro

**Comment by elvesrodrigues** [comment]
Oi, @lucasaug! Essa configuração de coleta, embora liste todos os passos de uma coleta dinâmica, o botão "Processamento dinâmico" não está habilitado.

Você pode testar novamente observando isso? Aqui tive problemas na hora de executar na master também, mas pode ser por causa da internet (`pyppeteer.errors.TimeoutError`). Com o sistema distribuído, tenho o erro: `net::ERR_CONNECTION_RESET`.

**Comment by lucasaug** [comment]
@elvesrodrigues Nossa, não tinha reparado isso! Acho que só importei a coleta direto do Drive e testei sem abrir cada seção individual pra verificar. Vou executar novamente e retorno!

**Comment by elvesrodrigues** [comment]
@lucasaug e esse erro `net::ERR_CONNECTION_RESET` na solução distribuída é aparentemente resolvida ao desabilitar aqueles interceptadores de requisição no midleware `scrapy_puppetter`.
